// sceneData.ts — pure data file, no React imports

export interface Scene {
  id: string
  title: string
  narration: string
  example: string
  tip: string
  keyFacts: string[]
  animation: string
  duration: number
}

export const SKILL_SCENES: Record<string, Scene[]> = {

  // -------------------------------------------------------------------------
  // 1. MONEY & TRANSACTIONS — 12 scenes
  // -------------------------------------------------------------------------
  money_transactions: [
    {
      id: 'mt_s1', title: 'What is Money?',
      narration: 'Money is what we use to pay for things we need. In Kenya we use Kenya Shillings, written as KES.',
      example: 'You give the shopkeeper KES 20 and they give you a loaf of bread.',
      tip: 'Always know how much money you have before you go to the shop.',
      keyFacts: ['Kenya uses Kenya Shillings (KES)', 'Money is swapped for goods and services', 'Without money you cannot buy food, medicine, or transport'],
      animation: 'coins-fall', duration: 15000,
    },
    {
      id: 'mt_s2', title: 'Kenyan Coins',
      narration: 'Kenya has coins worth KES 1, 5, 10, 20, and 50. Each coin is a different size and colour to help you tell them apart.',
      example: 'The KES 20 coin is gold and bigger. The KES 5 coin is silver and smaller.',
      tip: 'Pick up each coin and feel it. Size and weight help you identify coins quickly.',
      keyFacts: ['Coins: KES 1, 5, 10, 20, 50', 'Gold coloured coins are usually worth more', 'Coins are good for small everyday purchases'],
      animation: 'coins-fall', duration: 15000,
    },
    {
      id: 'mt_s3', title: 'Kenyan Notes',
      narration: 'Kenya has notes worth KES 50, 100, 200, 500, and 1000. Notes are paper money used for bigger amounts.',
      example: 'Buying vegetables at the market for KES 80 — you give the trader a KES 100 note.',
      tip: 'Keep your notes flat in a wallet so you do not lose or damage them.',
      keyFacts: ['Notes: KES 50, 100, 200, 500, 1000', 'Each note has a unique colour and design', 'Notes are used for larger purchases'],
      animation: 'notes-spread', duration: 15000,
    },
    {
      id: 'mt_s4', title: 'Which Amount is More?',
      narration: 'Before you pay, check if the money you have is enough. Compare what something costs with what you have.',
      example: 'A soda costs KES 60. You have KES 100. Since 100 is more than 60, you have enough.',
      tip: 'If unsure, subtract the price from your money. A positive answer means you have enough.',
      keyFacts: ['Compare price to your money before paying', '100 − 60 = 40, so you have KES 40 left', 'Never assume you have enough — always check'],
      animation: 'count-coins', duration: 15000,
    },
    {
      id: 'mt_s5', title: 'Paying for One Item',
      narration: 'When you buy one thing, give the shopkeeper the exact amount or a note bigger than the price. They will give you change.',
      example: 'Milk costs KES 55. You give KES 100. The shopkeeper gives you KES 45 back as change.',
      tip: 'Hand over your money calmly. Wait for your change before leaving.',
      keyFacts: ['Give money equal to or more than the price', 'Change is the money you get back', 'Always wait for your change'],
      animation: 'hand-pay', duration: 15000,
    },
    {
      id: 'mt_s6', title: 'Calculating Change',
      narration: 'Change is what you get back when you pay more than the price. Subtract the price from what you gave.',
      example: 'You give KES 200 for something that costs KES 130. Change = 200 − 130 = KES 70.',
      tip: 'Do the calculation in your head before paying so you know what change to expect.',
      keyFacts: ['Change = Amount given − Price', 'Always calculate before handing over money', 'Count your change before leaving the shop'],
      animation: 'count-coins', duration: 15000,
    },
    {
      id: 'mt_s7', title: 'Checking Your Change',
      narration: 'After receiving change, count it before you leave the shop. Make sure it matches what you calculated.',
      example: 'You expect KES 70. The shopkeeper gives you a KES 50 and KES 20 note. That is correct — 50 + 20 = 70.',
      tip: 'Count your change at the counter, not outside. It is easier to raise a concern immediately.',
      keyFacts: ['Count change before leaving', 'Add up coins and notes to check the total', 'Mistakes happen — always verify'],
      animation: 'count-coins', duration: 15000,
    },
    {
      id: 'mt_s8', title: 'When Change is Wrong',
      narration: 'If your change is wrong, stay calm and politely tell the shopkeeper. You have every right to correct change.',
      example: 'You expected KES 70 but received KES 50. Say: "Excuse me, I think my change is short by KES 20."',
      tip: 'Stay calm and polite. Most shopkeepers will correct the mistake immediately.',
      keyFacts: ['You are entitled to correct change', 'Speak up calmly — do not shout', 'If they refuse, ask to speak to the manager'],
      animation: 'warning-flash', duration: 15000,
    },
    {
      id: 'mt_s9', title: 'Making a Shopping List',
      narration: 'A shopping list helps you remember what to buy and how much it will cost. Write down each item and its price before you go.',
      example: 'List: Bread KES 50, Milk KES 60, Sugar KES 120. Total = KES 230. Bring at least KES 230.',
      tip: 'Add up your list at home so you know exactly how much money to carry.',
      keyFacts: ['A list prevents forgetting items', 'Add up prices before leaving home', 'Carry a little extra in case prices have changed'],
      animation: 'budget-bar', duration: 15000,
    },
    {
      id: 'mt_s10', title: 'Staying Within a Budget',
      narration: 'A budget is a limit on how much you will spend. If your budget is KES 500, you must not spend more than KES 500.',
      example: 'Budget: KES 500. You spend KES 230 on food and KES 150 on transport. Total: KES 380. You are within budget.',
      tip: 'Cross off items on your list as you buy them and keep a running total as you go.',
      keyFacts: ['A budget is your spending limit', 'Track spending as you go', 'Going over budget causes financial problems'],
      animation: 'budget-bar', duration: 15000,
    },
    {
      id: 'mt_s11', title: 'Avoiding Impulse Buying',
      narration: 'Impulse buying means buying something you did not plan for just because it looks nice. This eats into your budget.',
      example: 'You go to buy bread and see sweets on the counter. You buy them too and go over your budget.',
      tip: 'Stick to your list. Ask yourself: "Did I plan to buy this?" If no, put it back.',
      keyFacts: ['Impulse buys are unplanned purchases', 'They can ruin a budget quickly', 'A written list helps you stay on track'],
      animation: 'warning-flash', duration: 15000,
    },
    {
      id: 'mt_s12', title: 'Keeping Your Money Safe',
      narration: 'Keep your money in a safe place like a wallet, purse, or zipped pocket. Be aware of your surroundings when handling cash.',
      example: 'At a busy market, keep your bag in front of you and your wallet in an inside pocket.',
      tip: 'Never count large amounts of money in public. Do it privately before you leave home.',
      keyFacts: ['Keep money in a secure place', 'Be alert in crowded areas', 'Never flash large amounts of cash in public'],
      animation: 'lock-close', duration: 15000,
    },
  ],

  // -------------------------------------------------------------------------
  // 2. TIME & PLANNING — 12 scenes
  // -------------------------------------------------------------------------
  time_planning: [
    {
      id: 'tp_s1', title: 'Parts of a Clock',
      narration: 'A clock has two main hands. The short hand points to the hour. The long hand points to the minutes.',
      example: 'Short hand on 3, long hand on 12 — it is exactly 3 o\'clock.',
      tip: 'Always look at the short hand first to find the hour.',
      keyFacts: ['Short hand = hours', 'Long hand = minutes', 'When the long hand is on 12, it is exactly on the hour'],
      animation: 'clock-tick', duration: 15000,
    },
    {
      id: 'tp_s2', title: 'Reading O\'Clock Times',
      narration: 'When the long hand points straight up to 12, the time is exactly on the hour. We say "o\'clock".',
      example: 'Short hand on 7, long hand on 12 — it is 7 o\'clock.',
      tip: 'Practice with a toy clock or draw clock faces and fill in the hands.',
      keyFacts: ['Long hand on 12 = o\'clock', 'Read the hour from the short hand', 'Examples: 1 o\'clock, 4 o\'clock, 9 o\'clock'],
      animation: 'clock-tick', duration: 15000,
    },
    {
      id: 'tp_s3', title: 'Half Past and Quarter Past',
      narration: 'When the long hand points to 6, it is half past the hour — 30 minutes gone. When it points to 3, it is quarter past — 15 minutes gone.',
      example: 'Short hand between 2 and 3, long hand on 6 — it is half past 2, or 2:30.',
      tip: 'Think of the clock face as a pizza cut into 4 pieces. Each piece is 15 minutes.',
      keyFacts: ['Long hand on 6 = 30 minutes past', 'Long hand on 3 = 15 minutes past', 'Long hand on 9 = 45 minutes past'],
      animation: 'clock-tick', duration: 15000,
    },
    {
      id: 'tp_s4', title: 'AM and PM',
      narration: 'AM is the time from midnight to midday — morning hours. PM is from midday to midnight — afternoon and evening.',
      example: 'School starts at 7:30 AM. Supper is at 7:00 PM. Both say 7 but they are 12 hours apart.',
      tip: 'When setting alarms, always double-check AM or PM — a wrong tap means waking up 12 hours late!',
      keyFacts: ['AM = midnight to midday', 'PM = midday to midnight', 'Always check AM/PM when setting alarms'],
      animation: 'sun-moon', duration: 15000,
    },
    {
      id: 'tp_s5', title: 'Morning Routines',
      narration: 'A morning routine is the set of things you do before leaving the house. Knowing how long each step takes helps you leave on time.',
      example: 'Wake up 6:00 AM. Bath: 20 min. Dress: 10 min. Breakfast: 15 min. Ready by 6:45 AM.',
      tip: 'Time yourself doing morning tasks for one week. You will learn exactly how long you need.',
      keyFacts: ['Know how long your morning tasks take', 'Add them up to find your wake-up time', 'Rushing causes mistakes and stress'],
      animation: 'schedule-reveal', duration: 15000,
    },
    {
      id: 'tp_s6', title: 'Reading a Daily Schedule',
      narration: 'A daily schedule shows what you need to do and at what time. It helps you stay organised and not forget anything.',
      example: '7:30 AM — Arrive at work. 1:00 PM — Lunch. 4:00 PM — Leave. 8:00 PM — Sleep.',
      tip: 'Keep your schedule somewhere visible — on your bedroom wall or saved on your phone.',
      keyFacts: ['A schedule lists tasks with their times', 'It prevents forgetting important activities', 'Check your schedule the night before'],
      animation: 'schedule-reveal', duration: 15000,
    },
    {
      id: 'tp_s7', title: 'Reading a Weekly Schedule',
      narration: 'A weekly schedule covers all 7 days. It shows which activities happen on which days so you can plan ahead.',
      example: 'Monday: Work. Wednesday: Clinic appointment. Friday: Shopping. Saturday: Rest day.',
      tip: 'At the start of each week, look at your whole week so nothing surprises you.',
      keyFacts: ['A weekly view shows 7 days at once', 'Helps you spot busy and free days', 'Allows you to prepare for each day in advance'],
      animation: 'schedule-reveal', duration: 15000,
    },
    {
      id: 'tp_s8', title: 'Planning Backwards',
      narration: 'Planning backwards means starting from the time you need to be somewhere and counting back to find out when to start.',
      example: 'Need to be at the clinic at 9:00 AM. Matatu: 30 min. Walk to stage: 10 min. Start at 8:20 AM.',
      tip: 'Always add 10 extra minutes as a buffer in case something goes wrong.',
      keyFacts: ['Start from your deadline and work backwards', 'Add each task\'s time going backwards', 'Always include travel time'],
      animation: 'clock-reverse', duration: 15000,
    },
    {
      id: 'tp_s9', title: 'How Long Does Something Take?',
      narration: 'Estimating time means guessing how long a task will take. With practice your estimates get more accurate.',
      example: 'Cooking takes 45 minutes. Washing clothes by hand takes 1 hour. Walking to the stage takes 10 minutes.',
      tip: 'When unsure, estimate longer rather than shorter — it is better to be early.',
      keyFacts: ['Estimating time improves with practice', 'Always round your estimates up', 'Track how long tasks take so you learn your own pace'],
      animation: 'clock-tick', duration: 15000,
    },
    {
      id: 'tp_s10', title: 'What Happens When You Are Late',
      narration: 'Being late causes problems — you miss important things, people lose trust in you, and you feel rushed and stressed.',
      example: 'Arriving late to work twice in a week could result in a warning from your supervisor.',
      tip: 'If you know you will be late, call or message ahead. It shows respect and responsibility.',
      keyFacts: ['Lateness affects trust and reputation', 'Repeated lateness can cost you your job', 'Always communicate if you will be late'],
      animation: 'late-rush', duration: 15000,
    },
    {
      id: 'tp_s11', title: 'Setting Reminders and Alarms',
      narration: 'Your phone can remind you of important tasks and appointments. Setting alarms means you do not have to rely only on memory.',
      example: 'Set an alarm for 6:00 AM to wake up. Set a reminder at 8:45 AM to leave for a 9:30 AM appointment.',
      tip: 'Set your alarm 5 minutes earlier than you think you need — just in case.',
      keyFacts: ['Use your phone to set alarms and reminders', 'Set reminders for appointments, medicine, and deadlines', 'Check reminders every morning'],
      animation: 'phone-glow', duration: 15000,
    },
    {
      id: 'tp_s12', title: 'Planning Your Week Ahead',
      narration: 'Taking 10 minutes on Sunday evening to plan your week makes each day easier and less stressful.',
      example: 'Sunday evening: check schedule, prepare work clothes, pack bag, set alarms for the week.',
      tip: 'Write your plan on paper or in your phone notes. A plan in your head is easy to forget.',
      keyFacts: ['Sunday planning sets you up for the whole week', 'Prepare things the night before', 'A written plan is more reliable than memory'],
      animation: 'schedule-reveal', duration: 15000,
    },
  ],




  // -------------------------------------------------------------------------
  // 3. DIGITAL SAFETY — 12 scenes
  // -------------------------------------------------------------------------
  digital_safety: [
    {
      id: 'ds_s1', title: 'What Your Phone Can Do',
      narration: 'Your phone lets you call, send messages, use the internet, and store personal information. It is a powerful tool that needs to be protected.',
      example: 'You use your phone to call family, check M-Pesa, send WhatsApp messages, and take photos.',
      tip: 'Set a PIN or fingerprint lock on your phone so nobody else can access it.',
      keyFacts: ['Phones hold personal and financial information', 'A locked phone protects your data', 'Treat your phone like you treat your wallet'],
      animation: 'phone-glow', duration: 15000,
    },
    {
      id: 'ds_s2', title: 'Making a Phone Call Safely',
      narration: 'Only call numbers you know and trust. When someone calls you, think carefully before sharing any information.',
      example: 'Your doctor calls to confirm your appointment — that is safe. A stranger calls asking for your ID number — that is not safe.',
      tip: 'Save important numbers in your phone so you always know who is calling.',
      keyFacts: ['Only call numbers you know', 'Legitimate callers never ask for your PIN or ID', 'Save trusted numbers in your contacts'],
      animation: 'call-shield', duration: 15000,
    },
    {
      id: 'ds_s3', title: 'Calls from Unknown Numbers',
      narration: 'If someone you do not know calls and asks for personal information, hang up. Real companies and hospitals never ask for your PIN by phone.',
      example: 'A caller says they are from Safaricom and asks for your M-Pesa PIN to "verify your account." This is a scam — hang up.',
      tip: 'If unsure, hang up and call the company directly using a number from their official website.',
      keyFacts: ['No real company asks for your PIN by phone', 'Scammers pretend to be banks and telecoms', 'Hang up and call back on an official number'],
      animation: 'warning-flash', duration: 15000,
    },
    {
      id: 'ds_s4', title: 'Sending Messages on WhatsApp',
      narration: 'WhatsApp lets you send messages, photos, and voice notes. Only chat with people you know in real life.',
      example: 'You message your mum on WhatsApp to say you arrived safely. That is a good use of the app.',
      tip: 'Do not accept messages from unknown numbers. Block and report anyone who makes you uncomfortable.',
      keyFacts: ['Only chat with people you know', 'You can block any number on WhatsApp', 'Do not share your location with strangers'],
      animation: 'chat-bubble', duration: 15000,
    },
    {
      id: 'ds_s5', title: 'What is Personal Information?',
      narration: 'Personal information is anything that identifies you — your name, phone number, home address, school, ID number, and PIN.',
      example: 'Your full name + phone number + where you live = enough for a stranger to find you.',
      tip: 'Think before you share. Once something is sent online, you cannot take it back.',
      keyFacts: ['Personal info: name, phone, address, ID, PIN', 'Sharing it with strangers is dangerous', 'Once shared online, it cannot be deleted'],
      animation: 'lock-close', duration: 15000,
    },
    {
      id: 'ds_s6', title: 'What Never to Share',
      narration: 'Never share your PIN, password, ID number, home address, or school with anyone online — even if they seem friendly or say they need it urgently.',
      example: 'Someone on Facebook says they are your friend\'s cousin and asks for your phone number and estate. Do not share.',
      tip: 'A real friend or family member who genuinely needs your details will ask you in person, not online.',
      keyFacts: ['Never share PIN, password, or ID online', 'Urgency is a trick used by scammers', 'Trusted people ask in person, not online'],
      animation: 'lock-close', duration: 15000,
    },
    {
      id: 'ds_s7', title: 'Recognising a Scam Message',
      narration: 'Scam messages try to trick you into giving money or personal information. They often say you have won something or that your account is in danger.',
      example: '"Congratulations! You have won KES 50,000. Send KES 200 to claim your prize." This is a scam.',
      tip: 'If it sounds too good to be true, it is. Real prizes never require you to pay first.',
      keyFacts: ['Scams promise prizes or create fear', 'Real companies never ask you to pay to claim a prize', 'Delete and block scam messages immediately'],
      animation: 'warning-flash', duration: 15000,
    },
    {
      id: 'ds_s8', title: 'Fake Offers and Prizes',
      narration: 'Scammers create fake offers that look real — fake Safaricom messages, fake job offers, fake lottery wins. Always verify before you act.',
      example: 'You receive a message saying you won a Safaricom data bundle. The sender\'s number is 0712345678 — not Safaricom. It is fake.',
      tip: 'Real Safaricom messages come from the sender name SAFARICOM, not a personal number.',
      keyFacts: ['Check the sender name, not just the message content', 'Official messages come from company names, not phone numbers', 'Verify offers on the company\'s official app or website'],
      animation: 'warning-flash', duration: 15000,
    },
    {
      id: 'ds_s9', title: 'What to Do With a Scam',
      narration: 'When you receive a scam message, do not reply, do not click any links, and do not send any money. Delete the message and block the number.',
      example: 'You get a text: "Your M-Pesa is suspended. Click here to restore." Do not click. Delete it.',
      tip: 'Report scam numbers to Safaricom by forwarding the message to 333.',
      keyFacts: ['Do not reply, click links, or send money', 'Delete and block the number immediately', 'Report scams to Safaricom at 333'],
      animation: 'warning-flash', duration: 15000,
    },
    {
      id: 'ds_s10', title: 'Staying Safe on Social Media',
      narration: 'Social media like Facebook, TikTok, and Instagram are public spaces. Be careful what you post — strangers can see it.',
      example: 'Posting "Going to Nairobi on Friday, house will be empty" tells strangers your house will be unguarded.',
      tip: 'Set your social media accounts to private so only people you approve can see your posts.',
      keyFacts: ['Public posts can be seen by anyone', 'Never post your location or travel plans publicly', 'Set accounts to private for better protection'],
      animation: 'lock-close', duration: 15000,
    },
    {
      id: 'ds_s11', title: 'Reporting Something Wrong',
      narration: 'If you see something online that upsets or worries you, you can report it. All social media platforms have a report button.',
      example: 'Someone sends you an inappropriate photo on WhatsApp. Block them, report the message, and tell a trusted adult.',
      tip: 'You do not have to deal with online problems alone. Always tell a trusted person.',
      keyFacts: ['Every platform has a report button', 'Block people who make you uncomfortable', 'Telling a trusted adult is always the right move'],
      animation: 'call-shield', duration: 15000,
    },
    {
      id: 'ds_s12', title: 'Who to Tell if You Feel Unsafe',
      narration: 'If something online makes you feel scared, uncomfortable, or confused, tell a parent, caregiver, teacher, or trusted adult immediately.',
      example: 'A stranger online keeps messaging you and asking to meet. Tell your caregiver right away.',
      tip: 'You will not get in trouble for reporting. The person trying to harm you is the one who is wrong.',
      keyFacts: ['Trust your instincts — if it feels wrong, it is', 'Tell a trusted adult straight away', 'You are never in trouble for reporting'],
      animation: 'shield-rise', duration: 15000,
    },
  ],

  // -------------------------------------------------------------------------
  // 4. MOBILE MONEY — 12 scenes
  // -------------------------------------------------------------------------
  
  mobile_money: [
    {
      id: 'mm_s1', title: 'What is M-Pesa?',
      narration: 'M-Pesa is a mobile money service by Safaricom. It lets you send money, pay bills, buy goods, and save — all from your phone.',
      example: 'Instead of travelling to the bank, you send your mum KES 500 in seconds from your phone.',
      tip: 'M-Pesa is faster and safer than carrying cash. Use it for everyday transactions.',
      keyFacts: ['M-Pesa is by Safaricom', 'Available on any Safaricom line', 'Used by millions of Kenyans every day'],
      animation: 'mpesa-logo', duration: 15000,
    },
    {
      id: 'mm_s2', title: 'How to Register for M-Pesa',
      narration: 'To register for M-Pesa, visit any Safaricom agent with your national ID or birth certificate. Registration is free.',
      example: 'Go to a Safaricom shop, show your ID, fill a short form, and your M-Pesa account is activated on the spot.',
      tip: 'Choose a PIN you can remember but that others cannot guess. Do not use your birthday.',
      keyFacts: ['Registration requires your national ID', 'Registration is completely free', 'You choose a secret 4-digit PIN'],
      animation: 'mpesa-logo', duration: 15000,
    },
    {
      id: 'mm_s3', title: 'The M-Pesa Menu',
      narration: 'Dial *334# on your phone to open the M-Pesa menu. You will see options like Send Money, Lipa na M-Pesa, Withdraw Cash, and My Account.',
      example: 'To send money: dial *334#, choose Send Money, enter the number and amount, then confirm with your PIN.',
      tip: 'Learn the menu numbers by heart so you can navigate quickly without reading every option.',
      keyFacts: ['Dial *334# to access M-Pesa', 'Main options: Send, Pay, Withdraw, My Account', 'You need your PIN for every transaction'],
      animation: 'send-money', duration: 15000,
    },
    {
      id: 'mm_s4', title: 'Sending Money to a Contact',
      narration: 'To send money, choose Send Money, enter the recipient\'s phone number, enter the amount, confirm the details, then enter your PIN.',
      example: 'Sending KES 300 to 0712 345 678. Steps: Send Money → Enter number → Enter 300 → Confirm → PIN.',
      tip: 'Always double-check the phone number before confirming. A wrong number is hard to reverse.',
      keyFacts: ['Double-check the number before sending', 'You get a confirmation SMS after sending', 'Minimum send amount is KES 10'],
      animation: 'send-money', duration: 15000,
    },
    {
      id: 'mm_s5', title: 'Sending to an Unregistered Number',
      narration: 'You can send money to someone who does not have M-Pesa. They receive an SMS with a code to collect cash from any M-Pesa agent.',
      example: 'Your cousin has no M-Pesa. You send KES 500. They show the SMS code at an agent and collect the cash.',
      tip: 'Tell the recipient to collect the money quickly — uncollected transfers are reversed after a set time.',
      keyFacts: ['Non-M-Pesa users can still receive money', 'They collect using a code from the SMS', 'The sender is charged a small transaction fee'],
      animation: 'send-money', duration: 15000,
    },
    {
      id: 'mm_s6', title: 'Paying via Lipa na M-Pesa',
      narration: 'Lipa na M-Pesa lets you pay shops and businesses using a till number. No cash needed — just your phone.',
      example: 'At a supermarket: Lipa na M-Pesa → Buy Goods → Enter till number → Enter amount → Enter PIN.',
      tip: 'Ask the cashier for the till number if you cannot see it displayed at the counter.',
      keyFacts: ['Lipa na M-Pesa uses a till number', 'Available at most shops, supermarkets, and restaurants', 'You get an SMS confirmation after paying'],
      animation: 'till-pay', duration: 15000,
    },
    {
      id: 'mm_s7', title: 'Paying via Paybill',
      narration: 'Paybill is used to pay bills — like electricity, water, school fees, and insurance. It uses a business number and an account number.',
      example: 'Paying Kenya Power: Lipa na M-Pesa → Paybill → Business no. 888880 → Your meter number → Amount → PIN.',
      tip: 'Keep a record of your Paybill numbers for bills you pay regularly.',
      keyFacts: ['Paybill is for bills and institutional payments', 'You need a business number AND an account number', 'Common uses: electricity, water, school fees'],
      animation: 'till-pay', duration: 15000,
    },
    {
      id: 'mm_s8', title: 'Checking Your Balance',
      narration: 'To check your M-Pesa balance, go to My Account, then Check Balance, and enter your PIN. Your balance appears on screen.',
      example: 'Dial *334# → My Account → Check Balance → Enter PIN → Screen shows: M-Pesa Balance: KES 1,250.',
      tip: 'Check your balance before making a transaction to make sure you have enough money.',
      keyFacts: ['Balance check requires your PIN', 'Check balance before every transaction', 'You can also check via the Safaricom app'],
      animation: 'balance-reveal', duration: 15000,
    },
    {
      id: 'mm_s9', title: 'Withdrawing Cash from an Agent',
      narration: 'M-Pesa agents are shops that let you take out cash from your M-Pesa. Look for the green M-Pesa agent sign.',
      example: 'At an agent: give them your number, they send a withdrawal request, you enter your PIN to confirm, they give you the cash.',
      tip: 'Count your cash before leaving the agent\'s shop — just like counting change at a supermarket.',
      keyFacts: ['Agents display the green M-Pesa sign', 'You enter your PIN to authorise withdrawal', 'A fee is charged for withdrawals'],
      animation: 'mpesa-logo', duration: 15000,
    },
    {
      id: 'mm_s10', title: 'What a Real M-Pesa Message Looks Like',
      narration: 'A real M-Pesa confirmation message comes from the sender name MPESA in capitals. It shows the amount, recipient, date, and your new balance.',
      example: 'MPESA: You have sent KES 300 to JOHN DOE 0712345678 on 20/5/26. New M-PESA balance is KES 950.',
      tip: 'Save a real M-Pesa message on your phone so you can compare future messages against it.',
      keyFacts: ['Real messages come from "MPESA" — not a phone number', 'They include amount, recipient, time, and new balance', 'Always verify the sender name first'],
      animation: 'mpesa-logo', duration: 15000,
    },
    {
      id: 'mm_s11', title: 'Spotting a Fake M-Pesa Message',
      narration: 'Fake M-Pesa messages look like real ones but come from a phone number, not from MPESA. They ask you to call a number or send money.',
      example: '"MPESA ALERT: KES 2000 sent in error. Call 0756 123 456 to reverse." — This is fake. Do not call.',
      tip: 'Check the sender name. If it is a phone number instead of MPESA, it is a scam.',
      keyFacts: ['Fake messages come from phone numbers, not MPESA', 'Real M-Pesa never asks you to call to reverse a transaction', 'Report fake messages to Safaricom at 333'],
      animation: 'warning-flash', duration: 15000,
    },
    {
      id: 'mm_s12', title: 'Sent Money to the Wrong Number?',
      narration: 'If you send money to the wrong number, call Safaricom on 0722 000 100 immediately. They can help reverse the transaction.',
      example: 'You meant to send to 0712 345 678 but typed 0712 345 679. Call Safaricom straight away before the recipient withdraws.',
      tip: 'Act fast — once the recipient withdraws the cash, it is very difficult to recover.',
      keyFacts: ['Call Safaricom on 0722 000 100 immediately', 'Act before the recipient withdraws', 'Always double-check numbers before confirming'],
      animation: 'warning-flash', duration: 15000,
    },
  ],

  // -------------------------------------------------------------------------
  // 5. COMMUNICATION & SELF-ADVOCACY — 12 scenes
  // -------------------------------------------------------------------------
  communication_advocacy: [
    {
      id: 'ca_s1', title: 'What is Self-Advocacy?',
      narration: 'Self-advocacy means speaking up for yourself — knowing what you need and saying it clearly and confidently.',
      example: 'At the clinic, instead of staying silent, you tell the nurse: "I have been waiting for 2 hours. Can someone help me?"',
      tip: 'Speaking up for yourself is not rude. It is your right.',
      keyFacts: ['Self-advocacy means speaking up for yourself', 'You have a right to be heard', 'Practice saying what you need out loud'],
      animation: 'voice-rise', duration: 15000,
    },
    {
      id: 'ca_s2', title: 'Expressing What You Need',
      narration: 'When you need something, say it clearly and directly. Use simple sentences: "I need help with..." or "I do not understand..."',
      example: '"I need help filling in this form." is clear. Staying silent and hoping someone notices is not.',
      tip: 'If you are nervous, practise saying what you need at home first.',
      keyFacts: ['Be direct and clear', 'Use "I need" and "I do not understand"', 'People cannot help you if they do not know what you need'],
      animation: 'voice-rise', duration: 15000,
    },
    {
      id: 'ca_s3', title: 'Asking for Help Without Shame',
      narration: 'Asking for help is a sign of strength, not weakness. Everyone needs help sometimes — including adults.',
      example: 'You do not know which bus to take. You ask someone at the stage: "Excuse me, does this matatu go to Town?"',
      tip: 'Start with "Excuse me" — it is polite and gets people\'s attention.',
      keyFacts: ['Asking for help is normal and brave', 'Start with "Excuse me"', 'Most people are happy to help when asked politely'],
      animation: 'hand-raised', duration: 15000,
    },
    {
      id: 'ca_s4', title: 'Saying No Confidently',
      narration: 'You have the right to say no to anything that makes you uncomfortable. No is a complete sentence — you do not owe anyone an explanation.',
      example: 'A friend asks to borrow your phone. You are not comfortable. You say: "No, I would rather not. Sorry."',
      tip: 'Say no calmly and firmly. You do not need to shout or apologise too much.',
      keyFacts: ['No is a complete sentence', 'You do not need to explain yourself', 'Say it calmly and firmly'],
      animation: 'voice-rise', duration: 15000,
    },
    {
      id: 'ca_s5', title: 'When You Do Not Understand',
      narration: 'If you do not understand something, say so immediately. It is always better to ask than to guess and get it wrong.',
      example: 'The doctor explains your prescription quickly. You say: "I am sorry, could you explain that again more slowly?"',
      tip: 'It is okay to ask the same thing twice. Understanding matters more than seeming smart.',
      keyFacts: ['Say "I do not understand" immediately', 'Ask for things to be repeated or explained differently', 'Never guess when you are unsure'],
      animation: 'hand-raised', duration: 15000,
    },
    {
      id: 'ca_s6', title: 'Talking to a Teacher or Doctor',
      narration: 'Professionals like teachers and doctors are there to help you. Talk to them clearly and honestly about what you are experiencing.',
      example: '"Doctor, I have had a headache for 3 days. It gets worse in the afternoon." This gives the doctor the information they need.',
      tip: 'Write down what you want to say before the appointment so you do not forget.',
      keyFacts: ['Be honest and specific', 'Write notes before important meetings', 'Professionals cannot help if they do not have the full picture'],
      animation: 'two-people', duration: 15000,
    },
    {
      id: 'ca_s7', title: 'Talking to an Employer',
      narration: 'At work, communicate clearly with your supervisor. If you have a concern, raise it professionally and respectfully.',
      example: '"Good morning. I wanted to let you know I will be 20 minutes late today due to a doctor\'s appointment."',
      tip: 'Always inform your supervisor in advance when possible — do not just not show up.',
      keyFacts: ['Communicate issues early, not after', 'Be professional and respectful', 'Give reasons without oversharing personal details'],
      animation: 'two-people', duration: 15000,
    },
    {
      id: 'ca_s8', title: 'Assertive vs Aggressive',
      narration: 'Assertive means confident and respectful. Aggressive means forceful and rude. You want to be assertive, not aggressive.',
      example: 'Assertive: "I expected KES 70 change, not KES 50." Aggressive: "You are cheating me! Give me my money!"',
      tip: 'Keep your voice calm and your words clear. You make a stronger point that way.',
      keyFacts: ['Assertive = confident + respectful', 'Aggressive = forceful + rude', 'Calm assertiveness is more effective than aggression'],
      animation: 'voice-rise', duration: 15000,
    },
    {
      id: 'ca_s9', title: 'Handling Disagreement Calmly',
      narration: 'Disagreements happen. The key is to listen, stay calm, and express your view without attacking the other person.',
      example: '"I see your point, but I disagree because..." keeps the conversation respectful and open.',
      tip: 'Take a breath before responding. A pause prevents you from saying something you regret.',
      keyFacts: ['Listen before you respond', 'Use "I disagree because..." not "You are wrong"', 'A pause before speaking helps you stay calm'],
      animation: 'two-people', duration: 15000,
    },
    {
      id: 'ca_s10', title: 'Knowing Your Rights as a Person',
      narration: 'You have rights simply because you are a human being. The right to be treated with dignity, to access services, and to be safe.',
      example: 'If a shopkeeper refuses to serve you because of how you look, that is discrimination and is not allowed.',
      tip: 'If you feel your rights have been violated, tell a trusted adult or contact a relevant authority.',
      keyFacts: ['You have a right to dignity and respect', 'Discrimination is illegal in Kenya', 'You can report rights violations to relevant authorities'],
      animation: 'shield-rise', duration: 15000,
    },
    {
      id: 'ca_s11', title: 'Knowing Your Rights as a Worker',
      narration: 'Kenyan law protects workers. You have the right to fair pay, safe working conditions, and to not be unfairly dismissed.',
      example: 'Your employer cannot fire you without a valid reason and proper notice. If they do, you can report to the labour office.',
      tip: 'Keep a copy of your employment contract. Know what it says about pay, hours, and notice periods.',
      keyFacts: ['Kenyan law protects all workers', 'You have the right to fair pay and safe conditions', 'Unfair dismissal can be reported to the Labour Office'],
      animation: 'shield-rise', duration: 15000,
    },
    {
      id: 'ca_s12', title: 'Where to Go if Your Rights Are Violated',
      narration: 'If your rights are violated, you do not have to accept it. There are organisations and offices in Kenya that can help you.',
      example: 'Kenya National Commission on Human Rights (KNCHR): 0800 720 627 — free to call.',
      tip: 'Write down what happened, when it happened, and who was involved before making a report.',
      keyFacts: ['KNCHR helpline: 0800 720 627 (free)', 'Labour Office handles workplace violations', 'Document incidents before reporting'],
      animation: 'shield-rise', duration: 15000,
    },
  ],

  // -------------------------------------------------------------------------
  // 6. FINANCIAL PLANNING — 12 scenes
  // -------------------------------------------------------------------------
  financial_planning: [
    {
      id: 'fp_s1', title: 'What is Income?',
      narration: 'Income is the money you receive — from a job, business, or support. It is the money coming in to you.',
      example: 'You earn KES 15,000 per month from your job. That is your monthly income.',
      tip: 'Know your exact income before you plan your spending. You cannot plan what you do not know.',
      keyFacts: ['Income = money coming in', 'Can come from a job, business, or support', 'Know your income before spending any of it'],
      animation: 'income-flow', duration: 15000,
    },
    {
      id: 'fp_s2', title: 'What are Expenses?',
      narration: 'Expenses are the money going out — rent, food, transport, airtime, and everything you pay for.',
      example: 'Rent KES 5,000. Food KES 3,000. Transport KES 1,500. Airtime KES 500. Total expenses: KES 10,000.',
      tip: 'Write down every expense for one month. Most people are surprised how much small purchases add up.',
      keyFacts: ['Expenses = money going out', 'Include all regular costs: rent, food, transport', 'Small daily expenses add up to large monthly amounts'],
      animation: 'expense-track', duration: 15000,
    },
    {
      id: 'fp_s3', title: 'Needs vs Wants',
      narration: 'Needs are things you must have to survive — food, shelter, medicine. Wants are things you would like but can live without.',
      example: 'Need: fare to work. Want: new shoes when your current ones still work fine.',
      tip: 'Before buying, ask: "Do I need this or do I want this?" Needs always come first.',
      keyFacts: ['Needs: food, shelter, medicine, transport', 'Wants: entertainment, fashion, upgrades', 'Always cover needs before spending on wants'],
      animation: 'needs-wants', duration: 15000,
    },
    {
      id: 'fp_s4', title: 'Making a Weekly Budget',
      narration: 'A weekly budget divides your money across 7 days. It tells you how much you can spend each day without running out.',
      example: 'Weekly budget KES 2,000. Food: KES 1,000. Transport: KES 600. Airtime: KES 200. Savings: KES 200.',
      tip: 'Withdraw your weekly amount at the start of the week and stick to it.',
      keyFacts: ['Divide income into weekly amounts', 'Assign money to each category first', 'Put savings in before spending anything else'],
      animation: 'budget-bar', duration: 15000,
    },
    {
      id: 'fp_s5', title: 'What Happens When You Overspend',
      narration: 'Overspending means spending more than you have. It leads to debt, stress, and not having money when you need it most.',
      example: 'You spend KES 12,000 this month but only earned KES 10,000. You are KES 2,000 in debt.',
      tip: 'If you catch yourself overspending mid-month, cut back immediately on wants to recover.',
      keyFacts: ['Overspending creates debt', 'Debt grows if not addressed quickly', 'Cut wants immediately when you overspend'],
      animation: 'warning-flash', duration: 15000,
    },
    {
      id: 'fp_s6', title: 'Tracking Your Spending',
      narration: 'Tracking means writing down every shilling you spend. It shows you where your money goes and where you can cut back.',
      example: 'Monday: Transport KES 60. Lunch KES 100. Airtime KES 50. Total: KES 210.',
      tip: 'Use a notebook or a notes app on your phone. Record purchases immediately — memory is unreliable.',
      keyFacts: ['Record every purchase, no matter how small', 'Review your spending weekly', 'Tracking shows patterns you can improve'],
      animation: 'expense-track', duration: 15000,
    },
    {
      id: 'fp_s7', title: 'Saving Towards a Goal',
      narration: 'Saving means setting aside money regularly for something you want in the future. Small amounts saved consistently grow over time.',
      example: 'Goal: KES 6,000 for new work shoes. Save KES 500 per month. In 12 months you have your goal.',
      tip: 'Save the moment you receive your income — before spending anything. What is left after spending is never saved.',
      keyFacts: ['Save before you spend, not after', 'Small consistent savings beat large irregular ones', 'Set a specific goal and deadline'],
      animation: 'savings-grow', duration: 15000,
    },
    {
      id: 'fp_s8', title: 'How Long to Reach Your Goal?',
      narration: 'To know how long saving will take, divide your goal amount by how much you can save each month.',
      example: 'Goal: KES 3,000. Saving KES 500 per month. 3,000 ÷ 500 = 6 months.',
      tip: 'If the timeline feels too long, look for ways to increase your monthly savings by cutting wants.',
      keyFacts: ['Months to goal = Goal ÷ Monthly savings', 'Increase savings to reach goals faster', 'A written goal is more motivating than a vague idea'],
      animation: 'savings-grow', duration: 15000,
    },
    {
      id: 'fp_s9', title: 'Understanding Interest',
      narration: 'Interest is a percentage charged on borrowed money or earned on saved money. When you save, interest works for you. When you borrow, it works against you.',
      example: 'Save KES 1,000 at 5% interest for a year — you earn KES 50. Borrow KES 1,000 at 10% — you owe KES 1,100.',
      tip: 'Always ask "what is the interest rate?" before borrowing or saving anywhere.',
      keyFacts: ['Interest on savings = money you earn', 'Interest on loans = extra money you must pay', 'Higher savings interest is good. Lower loan interest is good.'],
      animation: 'income-flow', duration: 15000,
    },
    {
      id: 'fp_s10', title: 'M-Shwari Savings',
      narration: 'M-Shwari is a savings and loans service on M-Pesa. You can save small amounts and earn interest without visiting a bank.',
      example: 'Save KES 100 in M-Shwari each week. After 3 months you have KES 1,300 plus interest.',
      tip: 'Access M-Shwari through the M-Pesa menu. It is free to open and there are no charges to save.',
      keyFacts: ['M-Shwari is accessed through M-Pesa', 'You earn interest on savings', 'Minimum deposit is very low — accessible to everyone'],
      animation: 'savings-grow', duration: 15000,
    },
    {
      id: 'fp_s11', title: 'M-Shwari Loans',
      narration: 'M-Shwari also offers small loans. But loans must be repaid on time or your credit score drops and future loans are denied.',
      example: 'You borrow KES 500 from M-Shwari. You must repay KES 507.50 (KES 500 + 1.5% fee) within 30 days.',
      tip: 'Only borrow what you are certain you can repay on time. Defaulting hurts your future access to credit.',
      keyFacts: ['M-Shwari loans charge 1.5% facilitation fee', 'Repay within 30 days', 'Late repayment blocks future loans and harms your credit score'],
      animation: 'warning-flash', duration: 15000,
    },
    {
      id: 'fp_s12', title: 'Building Good Financial Habits',
      narration: 'Good financial habits — budgeting, saving, and tracking spending — compound over time. Start small and stay consistent.',
      example: 'Save KES 200 every week for 5 years. That is KES 52,000 — enough to start a small business.',
      tip: 'The best time to start good money habits is today. The second best time is tomorrow.',
      keyFacts: ['Budget, save, and track spending every month', 'Consistency matters more than the amount', 'Small habits build life-changing results over time'],
      animation: 'savings-grow', duration: 15000,
    },
  ],

  // -------------------------------------------------------------------------
  // 7. COMMUNITY & PERSONAL SAFETY — 12 scenes
  // -------------------------------------------------------------------------
  community_safety: [
    {
      id: 'cs_s1', title: 'Knowing When You Are Unwell',
      narration: 'Your body gives you signals when something is wrong. Learn to recognise common symptoms so you can seek help early.',
      example: 'You have a headache, feel hot, and are very tired. These could be signs of fever — you need to see a doctor.',
      tip: 'Do not wait until you are very sick. Seek help early — early treatment is usually faster and cheaper.',
      keyFacts: ['Common symptoms: fever, pain, fatigue, swelling', 'Seek help at first signs, not last resort', 'Early treatment prevents serious illness'],
      animation: 'health-check', duration: 15000,
    },
    {
      id: 'cs_s2', title: 'Common Symptoms and What They Mean',
      narration: 'Different symptoms point to different health issues. Knowing the difference helps you describe your condition to a doctor accurately.',
      example: 'Fever + body aches = possible malaria or flu. Stomach pain + vomiting = possible food poisoning.',
      tip: 'Note when symptoms started and what makes them better or worse. Tell the doctor exactly this.',
      keyFacts: ['Fever: temperature above 37.5°C', 'Stomach symptoms often mean food or water issues', 'Tell the doctor when it started and how severe it is'],
      animation: 'health-check', duration: 15000,
    },
    {
      id: 'cs_s3', title: 'Describing Symptoms to a Doctor',
      narration: 'When you see a doctor, describe your symptoms clearly: where the pain is, how long it has lasted, and how severe it is on a scale of 1 to 10.',
      example: '"I have had a sharp pain in my lower right side for 2 days. It is about 7 out of 10 in pain."',
      tip: 'Write your symptoms down before the appointment so you do not forget anything important.',
      keyFacts: ['Describe: where, how long, how severe', 'Use a pain scale of 1 to 10', 'Mention any medicines you are already taking'],
      animation: 'health-check', duration: 15000,
    },
    {
      id: 'cs_s4', title: 'Understanding a Prescription',
      narration: 'A prescription tells you what medicine to take, how much, and when. Always read it carefully or ask the pharmacist to explain.',
      example: '"Take 1 tablet twice daily after meals for 7 days." This means morning and evening, always after eating.',
      tip: 'Finish the full course even if you feel better. Stopping early can make the illness come back stronger.',
      keyFacts: ['Read the dosage instructions carefully', 'Take medicine after meals unless told otherwise', 'Complete the full course — never stop early'],
      animation: 'prescription-read', duration: 15000,
    },
    {
      id: 'cs_s5', title: 'Taking Medicine Correctly',
      narration: 'Taking medicine correctly means the right dose, at the right time, for the right number of days. Wrong doses can be harmful.',
      example: 'Your prescription says 2 tablets in the morning. Taking 4 thinking it will work faster is dangerous.',
      tip: 'Set alarms on your phone to remind you to take medicine at the correct time.',
      keyFacts: ['Never exceed the prescribed dose', 'Take at the correct times — set alarms if needed', 'Store medicine in a cool, dry place away from children'],
      animation: 'prescription-read', duration: 15000,
    },
    {
      id: 'cs_s6', title: 'Your Emergency Contacts',
      narration: 'Emergency contacts are people who can help you in a crisis. You should have at least 3 saved in your phone and memorised.',
      example: 'Save: Mum — 0712 345 678. Neighbour John — 0723 456 789. Doctor — 0711 222 333.',
      tip: 'Write your emergency contacts on a card and keep it in your wallet — in case your phone is dead or lost.',
      keyFacts: ['Have at least 3 emergency contacts saved', 'Memorise at least one number', 'Keep a written backup in your wallet'],
      animation: 'emergency-call', duration: 15000,
    },
    {
      id: 'cs_s7', title: 'Calling for Help in an Emergency',
      narration: 'In an emergency, stay calm, call for help, and describe the situation clearly. Give your location first.',
      example: '"I am at Odeon Cinema on Tom Mboya Street. Someone has collapsed and is not breathing. Please send an ambulance."',
      tip: 'Always give your location first. Responders need to know where to come before anything else.',
      keyFacts: ['Stay calm and speak clearly', 'Give your location first', 'Describe what has happened and how many people are affected'],
      animation: 'emergency-call', duration: 15000,
    },
    {
      id: 'cs_s8', title: 'Kenya Emergency Numbers',
      narration: 'Kenya has emergency numbers you can call free of charge from any phone. Save them now.',
      example: 'Police: 999 or 112. Ambulance: 999 or 112. Fire Brigade: 999. Gender Violence: 1195.',
      tip: '112 works even when your phone has no airtime or is locked. It is the universal emergency number.',
      keyFacts: ['999 and 112 are free emergency numbers', '112 works without airtime', 'Gender Violence Hotline: 1195 (free)'],
      animation: 'emergency-call', duration: 15000,
    },
    {
      id: 'cs_s9', title: 'Community Services Near You',
      narration: 'Your community has services to help you — clinics, government offices, police stations, and social workers. Know where they are.',
      example: 'Your nearest government clinic provides free or subsidised healthcare. You do not always need to go to a private hospital.',
      tip: 'Walk around your neighbourhood and locate the nearest clinic, police post, and chief\'s office.',
      keyFacts: ['Government clinics offer subsidised healthcare', 'Chief\'s offices handle community disputes', 'Know your nearest services before you need them'],
      animation: 'community-map', duration: 15000,
    },
    {
      id: 'cs_s10', title: 'Recognising When Someone Needs Help',
      narration: 'Sometimes others around you need help. Knowing when and how to assist can make a real difference.',
      example: 'You see an elderly person struggling to cross the road. You offer your arm and help them across safely.',
      tip: 'Always ask before helping — "Can I help you?" Some people prefer to manage independently.',
      keyFacts: ['Ask before helping — do not assume', 'Call for professional help when needed', 'Your safety matters too — do not put yourself at risk'],
      animation: 'two-people', duration: 15000,
    },
    {
      id: 'cs_s11', title: 'Staying Safe in Public',
      narration: 'Public safety means being aware of your surroundings and making smart choices to keep yourself safe.',
      example: 'Walking home at night: use well-lit streets, walk with others if possible, keep your phone out of sight.',
      tip: 'Trust your instincts. If a situation feels unsafe, leave immediately — your safety comes first.',
      keyFacts: ['Stay on well-lit, busy streets at night', 'Keep valuables out of sight in public', 'Trust your instincts — if it feels wrong, leave'],
      animation: 'shield-rise', duration: 15000,
    },
    {
      id: 'cs_s12', title: 'When a Situation Feels Unsafe',
      narration: 'If you feel unsafe, you have options. Leave the area, call someone, go to a public place, or call 999.',
      example: 'A stranger is following you. Walk into the nearest shop, tell the shopkeeper, and call your emergency contact.',
      tip: 'You never have to stay in a situation that feels wrong. Removing yourself is always the right choice.',
      keyFacts: ['You can always leave a situation that feels unsafe', 'Go to a crowded public place', 'Call 999 or your emergency contact immediately'],
      animation: 'emergency-call', duration: 15000,
    },
  ],

  // -------------------------------------------------------------------------
  // 8. WORKPLACE READINESS — 12 scenes
  // -------------------------------------------------------------------------
  workplace_readiness: [
    {
      id: 'wr_s1', title: 'What Work Is and Why It Matters',
      narration: 'Work is an activity you do in exchange for payment. It gives you income, purpose, structure, and independence.',
      example: 'Working as a shop assistant: you serve customers and organise stock in exchange for a monthly salary.',
      tip: 'Every job, big or small, has value. Be proud of what you do.',
      keyFacts: ['Work provides income and independence', 'It gives your day structure and purpose', 'All work deserves respect'],
      animation: 'work-scene', duration: 15000,
    },
    {
      id: 'wr_s2', title: 'Types of Work and Workplaces',
      narration: 'Work happens in many settings — shops, offices, schools, hospitals, farms, and home businesses. Different jobs suit different people.',
      example: 'Shop assistant, office cleaner, data entry clerk, kitchen helper, market vendor — all are real jobs with real income.',
      tip: 'Think about what you are good at and enjoy. Work is easier when it suits your strengths.',
      keyFacts: ['Jobs exist in many different settings', 'Match your strengths to suitable job types', 'Supported employment is available for neurodiverse individuals'],
      animation: 'work-scene', duration: 15000,
    },
    {
      id: 'wr_s3', title: 'Reading Your Work Schedule',
      narration: 'A work schedule tells you when to be at work, when to break, and when to leave. You must follow it consistently.',
      example: 'Monday–Friday: 8:00 AM–5:00 PM. Lunch break: 1:00–2:00 PM. Saturday: 8:00 AM–1:00 PM.',
      tip: 'Check your schedule the night before. Prepare everything you need so mornings are not rushed.',
      keyFacts: ['Know your hours before your first day', 'Confirm break times with your supervisor', 'Keep your schedule saved on your phone'],
      animation: 'schedule-reveal', duration: 15000,
    },
    {
      id: 'wr_s4', title: 'Punctuality — Arriving on Time',
      narration: 'Being on time shows your employer you are reliable and professional. Arriving late repeatedly puts your job at risk.',
      example: 'Your shift starts at 8:00 AM. Aim to arrive by 7:50 AM — 10 minutes early is on time. 8:00 AM is late.',
      tip: 'Plan your journey the day before. Know exactly how long it takes to get to work.',
      keyFacts: ['Arrive 10 minutes before your shift starts', 'Repeated lateness leads to warnings or dismissal', 'Always inform your supervisor if you will be late'],
      animation: 'clock-tick', duration: 15000,
    },
    {
      id: 'wr_s5', title: 'Dress Code and Presentation',
      narration: 'How you dress at work matters. Always dress clean, neat, and appropriate for your workplace. First impressions last.',
      example: 'Office job: clean, pressed clothes and closed shoes. Market job: comfortable clothes and an apron if required.',
      tip: 'Prepare your work clothes the night before so you are not rushing in the morning.',
      keyFacts: ['Dress clean and appropriate for your workplace', 'Good grooming shows professionalism', 'When in doubt, dress more formally than less'],
      animation: 'work-scene', duration: 15000,
    },
    {
      id: 'wr_s6', title: 'Following Instructions',
      narration: 'Your supervisor will give you instructions. Listen carefully, ask if unsure, then do the task as directed.',
      example: '"Stack the new stock on the shelf and label each item with the price." Listen, confirm you understand, then do it.',
      tip: 'Repeat the instruction back to your supervisor to confirm you understood: "So you would like me to..."',
      keyFacts: ['Listen fully before starting', 'Repeat back to confirm understanding', 'Do not start until you are sure what is expected'],
      animation: 'work-scene', duration: 15000,
    },
    {
      id: 'wr_s7', title: 'Asking for Clarification',
      narration: 'If you do not understand an instruction, ask immediately. It is better to ask than to do the wrong thing.',
      example: '"I want to make sure I do this correctly — could you show me once?" is professional and shows initiative.',
      tip: 'Never guess and hope for the best. A wrong task done completely wastes more time than asking.',
      keyFacts: ['Ask before you start if unsure', '"Could you clarify..." is professional language', 'Asking once is better than redoing the whole task'],
      animation: 'hand-raised', duration: 15000,
    },
    {
      id: 'wr_s8', title: 'Handling a Mistake at Work',
      narration: 'Everyone makes mistakes. What matters is how you respond — acknowledge it, apologise, and correct it.',
      example: 'You enter the wrong price on a product. Tell your supervisor: "I made an error on the pricing. I will correct it now."',
      tip: 'Never hide mistakes. They are usually discovered, and hiding them makes things worse.',
      keyFacts: ['Admit mistakes immediately', 'Apologise and offer to correct it', 'Learn from it so it does not happen again'],
      animation: 'warning-flash', duration: 15000,
    },
    {
      id: 'wr_s9', title: 'Working with Colleagues',
      narration: 'Good workplace relationships make work easier and more enjoyable. Be respectful, cooperative, and professional with colleagues.',
      example: 'A colleague is struggling with heavy boxes. You offer to help: "Would you like a hand with those?"',
      tip: 'You do not need to be friends with everyone — but you must be professional with everyone.',
      keyFacts: ['Be respectful to all colleagues regardless of their role', 'Offer help when you see a colleague struggling', 'Avoid gossip and workplace drama'],
      animation: 'two-people', duration: 15000,
    },
    {
      id: 'wr_s10', title: 'Understanding a Payslip',
      narration: 'A payslip shows your gross pay, deductions, and net pay. Gross is what you earned. Net is what you take home after deductions.',
      example: 'Gross pay: KES 15,000. NHIF: KES 500. NSSF: KES 200. Tax (PAYE): KES 1,200. Net pay: KES 13,100.',
      tip: 'Check your payslip every month. If something looks wrong, raise it with HR or your supervisor.',
      keyFacts: ['Gross pay = total earnings before deductions', 'Net pay = what you actually receive', 'Common deductions: NHIF, NSSF, PAYE tax'],
      animation: 'payslip-reveal', duration: 15000,
    },
    {
      id: 'wr_s11', title: 'NHIF and NSSF',
      narration: 'NHIF is the National Health Insurance Fund — it pays for your hospital bills. NSSF is the National Social Security Fund — it saves money for your retirement.',
      example: 'When you visit a government hospital, your NHIF card covers part or all of the bill. Without it, you pay in full.',
      tip: 'Never opt out of NHIF and NSSF deductions. They protect your future health and retirement.',
      keyFacts: ['NHIF covers hospital bills', 'NSSF saves for your retirement', 'Both are deducted from salary automatically by law'],
      animation: 'payslip-reveal', duration: 15000,
    },
    {
      id: 'wr_s12', title: 'Your Rights as a Worker in Kenya',
      narration: 'Kenyan employment law protects you. You have the right to fair pay, safe conditions, and to not be discriminated against at work.',
      example: 'Your employer cannot pay you less because of your disability. The law requires equal pay for equal work.',
      tip: 'If your rights are violated at work, contact the Labour Office in your county. It is free.',
      keyFacts: ['Right to fair and equal pay', 'Right to safe working conditions', 'Report violations to the County Labour Office'],
      animation: 'shield-rise', duration: 15000,
    },
  ],
}


