// taskData_communication.ts
// Communication & Advocacy — 63 tasks
// 3 Tiers × 3 Difficulties × 7 Tasks = 63

export type TaskCommunication = {
  id: string
  skill: string
  tier: 1 | 2 | 3
  difficulty: 'easy' | 'intermediate' | 'advanced'
  type: 'tap_select' | 'scenario_choice' | 'true_false' | 'fill_blank' | 'sequential_steps' | 'drag_drop'
  topic: string
  question: string
  context?: string
  options?: { id: string; label: string; correct: boolean; image?: string }[]
  steps?: { id: string; label: string; order: number }[]
  dragItems?: { id: string; label: string; targetZone: string }[]
  dropZones?: { id: string; label: string }[]
  hint: string
  explanation: string
  questionImage?: string
  imageLayout?: 'context' | 'options'
}

export const COMMUNICATION_ADVOCACY_TASKS: TaskCommunication[] = [

  // =========================================================================
  // TIER 1 — FOUNDATION
  // =========================================================================

  // Tier 1 / Easy
  {
    id: 'ca_t1_easy_1', skill: 'communication_advocacy', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'expressing_needs',
    question: 'You are hungry and need food. What is the best way to communicate this?',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Say clearly "I am hungry, can I have something to eat please"', correct: true },
      { id: 'b', label: 'Wait and hope someone notices', correct: false },
      { id: 'c', label: 'Get upset and cry without saying why', correct: false },
      { id: 'd', label: 'Take food without asking', correct: false },
    ],
    hint: 'Clear, polite requests get the best results.',
    explanation: 'Saying clearly what you need gives others the chance to help. Polite, direct communication is always most effective.',
  },
  {
    id: 'ca_t1_easy_2', skill: 'communication_advocacy', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'listening',
    question: 'Good listening means looking at the person speaking and not interrupting.',
    questionImage: 'listening.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Think about what shows you are paying attention.',
    explanation: 'Good listening involves eye contact, not interrupting, and showing you understand. These signal respect and help communication flow well.',
  },
  {
    id: 'ca_t1_easy_3', skill: 'communication_advocacy', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'asking_for_help',
    question: 'You do not understand something at school. What should you do?',
    questionImage: 'asking_help.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Raise your hand and ask the teacher to explain again', correct: true },
      { id: 'b', label: 'Pretend you understand to avoid embarrassment', correct: false },
      { id: 'c', label: 'Give up on the subject entirely', correct: false },
      { id: 'd', label: 'Copy from a friend without understanding', correct: false },
    ],
    hint: 'Asking for help is a sign of intelligence, not weakness.',
    explanation: 'Asking for clarification helps you learn. Teachers expect questions — it shows you are engaged and want to understand.',
  },
  {
    id: 'ca_t1_easy_4', skill: 'communication_advocacy', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'expressing_needs',
    question: 'It is rude to tell someone when they have done something that upset you.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Expressing feelings respectfully is healthy and necessary.',
    explanation: 'It is not rude to express feelings respectfully. Keeping feelings inside causes more problems. Politely sharing how you feel allows issues to be resolved.',
  },
  {
    id: 'ca_t1_easy_5', skill: 'communication_advocacy', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'saying_no',
    question: 'A friend asks you to do something you are not comfortable with. What is the best response?',
    questionImage: 'saying_no.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Say "No thank you, I am not comfortable with that"', correct: true },
      { id: 'b', label: 'Do it anyway to keep the friendship', correct: false },
      { id: 'c', label: 'Ignore them and walk away without saying anything', correct: false },
      { id: 'd', label: 'Get angry and shout at them', correct: false },
    ],
    hint: 'You have the right to say no politely.',
    explanation: 'A respectful "no" is always acceptable. True friends respect boundaries. You do not need to do things that make you uncomfortable to maintain a friendship.',
  },
  {
    id: 'ca_t1_easy_6', skill: 'communication_advocacy', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'listening',
    question: 'Nodding your head while someone speaks shows you are listening.',
    questionImage: 'listening.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Body language is part of communication.',
    explanation: 'Nodding, eye contact, and facing the speaker are all ways of showing you are listening. Body language communicates even without words.',
  },
  {
    id: 'ca_t1_easy_7', skill: 'communication_advocacy', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'asking_for_help',
    question: 'You are lost in town and need directions. What do you do?',
    questionImage: 'asking_help.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Politely approach someone and say "Excuse me, can you help me? I am looking for..."', correct: true },
      { id: 'b', label: 'Wander around hoping to find the place', correct: false },
      { id: 'c', label: 'Panic and sit down', correct: false },
      { id: 'd', label: 'Ask anyone and everyone at the same time', correct: false },
    ],
    hint: 'A polite, clear request gets the best help.',
    explanation: 'Approaching someone calmly with a polite greeting and a clear request is the most effective way to get directions or help when lost.',
  },

  // Tier 1 / Intermediate
  {
    id: 'ca_t1_int_1', skill: 'communication_advocacy', tier: 1, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'expressing_needs',
    question: 'Your caregiver forgot to give you your medicine today. How do you communicate this?',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Calmly say "Excuse me, I think I missed my medicine today — can we check?"', correct: true },
      { id: 'b', label: 'Say nothing and hope you remember tomorrow', correct: false },
      { id: 'c', label: 'Get angry because they forgot', correct: false },
      { id: 'd', label: 'Take extra medicine tomorrow to make up for it', correct: false },
    ],
    hint: 'A calm, clear reminder is the most effective approach.',
    explanation: 'Calmly reminding a caregiver is appropriate and important for your health. Using respectful language makes it easier for them to respond positively.',
  },
  {
    id: 'ca_t1_int_2', skill: 'communication_advocacy', tier: 1, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'listening',
    question: 'Sort these behaviours into Good Listening or Poor Listening.',
    questionImage: 'listening.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'l1', label: 'Making eye contact with the speaker', targetZone: 'good' },
      { id: 'l2', label: 'Looking at your phone while they talk', targetZone: 'poor' },
      { id: 'l3', label: 'Asking questions to understand better', targetZone: 'good' },
      { id: 'l4', label: 'Finishing their sentences for them', targetZone: 'poor' },
      { id: 'l5', label: 'Waiting until they finish before responding', targetZone: 'good' },
      { id: 'l6', label: 'Thinking about what to say while they are still talking', targetZone: 'poor' },
    ],
    dropZones: [
      { id: 'good', label: 'Good listening' },
      { id: 'poor', label: 'Poor listening' },
    ],
    hint: 'Good listening focuses fully on the speaker.',
    explanation: 'Good: eye contact, questions, waiting to respond. Poor: phone use, interrupting, thinking ahead while they speak.',
  },
  {
    id: 'ca_t1_int_3', skill: 'communication_advocacy', tier: 1, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'asking_for_help',
    question: 'You are at a hospital and do not understand what the doctor told you. What should you do?',
    questionImage: 'asking_help.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Say "I am sorry, I did not understand. Can you explain that again more simply?"', correct: true },
      { id: 'b', label: 'Nod as if you understood and figure it out later', correct: false },
      { id: 'c', label: 'Leave and ask someone else', correct: false },
      { id: 'd', label: 'Feel embarrassed and say nothing', correct: false },
    ],
    hint: 'Medical information is too important to misunderstand — always ask.',
    explanation: 'Asking a doctor to explain again is your right. Medical information must be understood clearly. Doctors expect and welcome clarifying questions.',
  },
  {
    id: 'ca_t1_int_4', skill: 'communication_advocacy', tier: 1, difficulty: 'intermediate',
    type: 'true_false', topic: 'saying_no',
    question: 'You must always say yes to a family member\'s request even if it makes you uncomfortable.',
    questionImage: 'saying_no.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Boundaries apply in all relationships — including family.',
    explanation: 'You have the right to say no respectfully to anyone — including family members. Healthy boundaries exist in all relationships.',
  },
  {
    id: 'ca_t1_int_5', skill: 'communication_advocacy', tier: 1, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'expressing_needs',
    question: 'When expressing a complaint, it helps to use "I feel..." statements rather than "You always..." because they are less likely to make the other person feel ___.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Defensive or attacked', correct: true },
      { id: 'b', label: 'Happy and understood', correct: false },
      { id: 'c', label: 'Confused about the situation', correct: false },
    ],
    hint: '"I feel" focuses on your experience. "You always" sounds like blame.',
    explanation: '"I feel hurt when..." is less confrontational than "You always hurt me." I-statements invite conversation. You-statements trigger defensiveness.',
  },
  {
    id: 'ca_t1_int_6', skill: 'communication_advocacy', tier: 1, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'asking_for_help',
    question: 'You need help carrying heavy bags but feel shy asking strangers. What should you say?',
    questionImage: 'asking_help.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: '"Excuse me, would you mind helping me carry this? I would really appreciate it."', correct: true },
      { id: 'b', label: 'Struggle alone rather than ask', correct: false },
      { id: 'c', label: 'Take very long hoping someone offers', correct: false },
      { id: 'd', label: 'Drop the bags and walk away', correct: false },
    ],
    hint: 'A polite, specific request is much easier for people to respond to.',
    explanation: 'Most people are happy to help when asked politely and specifically. The discomfort of asking is temporary — the help makes a real difference.',
  },
  {
    id: 'ca_t1_int_7', skill: 'communication_advocacy', tier: 1, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'expressing_needs',
    question: 'Put these steps in order for expressing a need or concern effectively.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Choose a calm moment when both people are not stressed', order: 1 },
      { id: 's2', label: 'Use a polite greeting to start the conversation', order: 2 },
      { id: 's3', label: 'State your need or concern clearly and specifically', order: 3 },
      { id: 's4', label: 'Listen to the other person\'s response without interrupting', order: 4 },
      { id: 's5', label: 'Work together to find a solution', order: 5 },
    ],
    hint: 'Timing, greeting, clarity, listening, and collaboration.',
    explanation: 'Effective communication: calm timing → polite opening → clear statement → active listening → collaborative solution.',
  },

  // Tier 1 / Advanced
  {
    id: 'ca_t1_adv_1', skill: 'communication_advocacy', tier: 1, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'self_advocacy',
    question: 'A shopkeeper gives you wrong change and denies it when you point it out. What do you do?',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Calmly recount the money together and state the correct amount clearly', correct: true },
      { id: 'b', label: 'Accept the loss — arguing is not worth it', correct: false },
      { id: 'c', label: 'Shout and cause a scene', correct: false },
      { id: 'd', label: 'Leave and never return to the shop', correct: false },
    ],
    hint: 'Stay calm, be specific, and count together.',
    explanation: 'Calmly recounting money together removes the argument from opinion to fact. State the amount you gave, the cost, and the expected change. Stay calm throughout.',
  },
  {
    id: 'ca_t1_adv_2', skill: 'communication_advocacy', tier: 1, difficulty: 'advanced',
    type: 'true_false', topic: 'self_advocacy',
    question: 'You have the right to ask for information about your own health, education, or welfare.',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Asking about matters that affect you directly is always your right.',
    explanation: 'You have the right to be informed about your own health, education, and welfare. Self-advocacy means asking questions and seeking information that affects your life.',
  },
  {
    id: 'ca_t1_adv_3', skill: 'communication_advocacy', tier: 1, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'expressing_needs',
    question: 'You feel a service provider is not treating you with respect. How do you address this?',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Calmly say "I would appreciate being treated with respect. Can we start again?"', correct: true },
      { id: 'b', label: 'Accept poor treatment — they are in charge', correct: false },
      { id: 'c', label: 'Respond rudely to match their behaviour', correct: false },
      { id: 'd', label: 'Leave without addressing the issue', correct: false },
    ],
    hint: 'You can request respectful treatment without being aggressive.',
    explanation: 'Requesting respectful treatment is your right. A calm, direct request is more effective than aggression or silent acceptance. Most people respond well to being asked.',
  },
  {
    id: 'ca_t1_adv_4', skill: 'communication_advocacy', tier: 1, difficulty: 'advanced',
    type: 'fill_blank', topic: 'saying_no',
    question: 'When someone pressures you repeatedly after you have said no, you should ___ your response.',
    questionImage: 'saying_no.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Repeat calmly without explaining further', correct: true },
      { id: 'b', label: 'Make up excuses each time', correct: false },
      { id: 'c', label: 'Give in to end the pressure', correct: false },
    ],
    hint: 'Repeating "no" calmly is called the broken record technique.',
    explanation: 'When pressured, simply repeat "No, I am not comfortable with that" calmly. You do not need to justify your no. Providing reasons invites counter-arguments.',
  },
  {
    id: 'ca_t1_adv_5', skill: 'communication_advocacy', tier: 1, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'self_advocacy',
    question: 'You have a disability and need a specific accommodation at school. How do you request it?',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Speak to the relevant teacher or administrator, explain your need, and ask what support is available', correct: true },
      { id: 'b', label: 'Assume the school knows and will provide it automatically', correct: false },
      { id: 'c', label: 'Avoid school until the accommodation is in place', correct: false },
      { id: 'd', label: 'Ask a friend to request on your behalf without explaining your situation', correct: false },
    ],
    hint: 'Clearly stating your need directly to the right person is most effective.',
    explanation: 'Self-advocacy means communicating your needs directly and clearly. Schools have a responsibility to provide reasonable accommodations when properly informed.',
  },
  {
    id: 'ca_t1_adv_6', skill: 'communication_advocacy', tier: 1, difficulty: 'advanced',
    type: 'drag_drop', topic: 'expressing_needs',
    question: 'Sort these communication approaches into Assertive, Passive, or Aggressive.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'c1', label: '"I feel upset when plans change without notice. Can we discuss this?"', targetZone: 'assertive' },
      { id: 'c2', label: 'Saying nothing and feeling resentful inside', targetZone: 'passive' },
      { id: 'c3', label: '"You always do this! You never consider anyone else!"', targetZone: 'aggressive' },
      { id: 'c4', label: '"I would like to share a concern if that is okay"', targetZone: 'assertive' },
      { id: 'c5', label: 'Agreeing to everything to avoid conflict', targetZone: 'passive' },
      { id: 'c6', label: 'Raising your voice and pointing fingers', targetZone: 'aggressive' },
    ],
    dropZones: [
      { id: 'assertive', label: 'Assertive — direct and respectful' },
      { id: 'passive', label: 'Passive — avoids conflict but unheard' },
      { id: 'aggressive', label: 'Aggressive — confrontational' },
    ],
    hint: 'Assertive is direct AND respectful. Passive avoids. Aggressive attacks.',
    explanation: 'Assertive: clear, respectful, direct. Passive: avoids, suppresses feelings. Aggressive: attacks, blames, escalates. Assertive communication is most effective.',
  },
  {
    id: 'ca_t1_adv_7', skill: 'communication_advocacy', tier: 1, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'self_advocacy',
    question: 'Put these steps in order for making a formal complaint.',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Note down the details of what happened — dates, times, names', order: 1 },
      { id: 's2', label: 'Try to resolve it directly with the person or organisation first', order: 2 },
      { id: 's3', label: 'If unresolved, ask to speak with a supervisor or manager', order: 3 },
      { id: 's4', label: 'Submit a written complaint if verbal attempts fail', order: 4 },
      { id: 's5', label: 'Escalate to relevant authorities if the organisation does not respond', order: 5 },
    ],
    hint: 'Document → direct → supervisor → written → escalate.',
    explanation: 'Formal complaint process: document details → direct resolution → supervisor → written complaint → escalate to authorities. Each step up requires the previous one first.',
  },

  // =========================================================================
  // TIER 2 — APPLICATION
  // =========================================================================

  // Tier 2 / Easy
  {
    id: 'ca_t2_easy_1', skill: 'communication_advocacy', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'expressing_needs',
    question: 'You are in pain but your doctor appointment is not for two weeks. What should you do?',
    questionImage: 'asking_help.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Call the clinic and explain your pain level — ask if you can be seen sooner', correct: true },
      { id: 'b', label: 'Wait the two weeks as scheduled', correct: false },
      { id: 'c', label: 'Go to a different doctor without explaining', correct: false },
      { id: 'd', label: 'Ignore the pain and hope it resolves', correct: false },
    ],
    hint: 'You have the right to communicate changes in your condition.',
    explanation: 'Calling to explain your pain level is appropriate self-advocacy. Clinics often have urgent slots for patients whose condition has worsened.',
  },
  {
    id: 'ca_t2_easy_2', skill: 'communication_advocacy', tier: 2, difficulty: 'easy',
    type: 'true_false', topic: 'listening',
    question: 'Repeating back what someone said in your own words confirms you understood them correctly.',
    questionImage: 'listening.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'This technique is called "reflective listening" or "paraphrasing."',
    explanation: 'Paraphrasing — saying "So what you mean is..." — confirms understanding and shows the speaker they were heard. It prevents misunderstandings.',
  },
  {
    id: 'ca_t2_easy_3', skill: 'communication_advocacy', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'saying_no',
    question: 'A colleague asks you to cover their shift but you have a prior commitment. What do you say?',
    questionImage: 'saying_no.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: '"I am sorry, I already have a commitment that day. I hope you find someone."', correct: true },
      { id: 'b', label: 'Say yes and then cancel your existing commitment', correct: false },
      { id: 'c', label: 'Avoid them so you do not have to answer', correct: false },
      { id: 'd', label: 'Make up a dramatic excuse to seem more justified', correct: false },
    ],
    hint: 'A simple, honest, and kind decline is enough.',
    explanation: 'You do not need an elaborate excuse to say no. A simple, honest response respects both your boundaries and the other person\'s time.',
  },
  {
    id: 'ca_t2_easy_4', skill: 'communication_advocacy', tier: 2, difficulty: 'easy',
    type: 'fill_blank', topic: 'expressing_needs',
    question: 'When you are angry, it is best to ___ before discussing the issue.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Calm down and collect your thoughts', correct: true },
      { id: 'b', label: 'Speak immediately while the feelings are fresh', correct: false },
      { id: 'c', label: 'Write an angry message and send it right away', correct: false },
    ],
    hint: 'Hot emotions lead to poor communication.',
    explanation: 'Anger clouds communication. Taking time to calm down — even 10 minutes — means you can express your concern clearly and constructively.',
  },
  {
    id: 'ca_t2_easy_5', skill: 'communication_advocacy', tier: 2, difficulty: 'easy',
    type: 'tap_select', topic: 'self_advocacy',
    question: 'You receive a bill that seems too high. What is the first step?',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Ask for an itemised bill and check each charge carefully', correct: true },
      { id: 'b', label: 'Pay it without question — they must be right', correct: false },
      { id: 'c', label: 'Refuse to pay anything until it is sorted', correct: false },
      { id: 'd', label: 'Complain loudly in public', correct: false },
    ],
    hint: 'Ask for details before disputing or paying.',
    explanation: 'Requesting an itemised bill lets you verify each charge. Errors are common and most organisations correct genuine mistakes when calmly shown the evidence.',
  },
  {
    id: 'ca_t2_easy_6', skill: 'communication_advocacy', tier: 2, difficulty: 'easy',
    type: 'true_false', topic: 'asking_for_help',
    question: 'Asking for help is a sign of weakness.',
    questionImage: 'asking_help.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Everyone needs help at some point.',
    explanation: 'Asking for help shows self-awareness and good judgment. People who ask for help when needed achieve more than those who struggle alone out of pride.',
  },
  {
    id: 'ca_t2_easy_7', skill: 'communication_advocacy', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'expressing_needs',
    question: 'Your neighbour plays loud music late at night and it affects your sleep. What do you do first?',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Knock politely and explain "The music is affecting my sleep, could you turn it down please?"', correct: true },
      { id: 'b', label: 'Call the police immediately', correct: false },
      { id: 'c', label: 'Retaliate by playing your own loud music', correct: false },
      { id: 'd', label: 'Suffer in silence to avoid conflict', correct: false },
    ],
    hint: 'A polite direct conversation is always the first step.',
    explanation: 'A calm, direct conversation is the most effective first step. Most people are unaware of the impact and respond well when approached respectfully.',
  },

  // Tier 2 / Intermediate
  {
    id: 'ca_t2_int_1', skill: 'communication_advocacy', tier: 2, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'self_advocacy',
    question: 'You are being bullied at work. What is the correct sequence of steps?',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Document incidents → tell the bully their behaviour is unacceptable → report to HR if it continues', correct: true },
      { id: 'b', label: 'Ignore it and hope it stops', correct: false },
      { id: 'c', label: 'Quit the job immediately', correct: false },
      { id: 'd', label: 'Retaliate to show you will not be a victim', correct: false },
    ],
    hint: 'Document, address directly, then escalate if needed.',
    explanation: 'Documenting creates evidence. Addressing directly gives the person a chance to stop. HR escalation is warranted when direct communication fails.',
  },
  {
    id: 'ca_t2_int_2', skill: 'communication_advocacy', tier: 2, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'expressing_needs',
    question: 'Sort these situations into Handle Directly or Seek Support.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    dragItems: [
      { id: 's1', label: 'Neighbour\'s noisy music at night', targetZone: 'direct' },
      { id: 's2', label: 'Experiencing physical violence from a partner', targetZone: 'support' },
      { id: 's3', label: 'A friend said something that hurt your feelings', targetZone: 'direct' },
      { id: 's4', label: 'Being denied a legal right at a government office', targetZone: 'support' },
      { id: 's5', label: 'Disagreement about a shared chore at home', targetZone: 'direct' },
      { id: 's6', label: 'Mental health crisis affecting daily functioning', targetZone: 'support' },
    ],
    dropZones: [
      { id: 'direct', label: 'Handle directly with conversation' },
      { id: 'support', label: 'Seek professional or authority support' },
    ],
    hint: 'Everyday conflicts can be handled directly. Safety and rights issues need support.',
    explanation: 'Direct: music, hurt feelings, chores. Support needed: violence, legal rights violations, mental health crises. Knowing when to escalate protects you.',
  },
  {
    id: 'ca_t2_int_3', skill: 'communication_advocacy', tier: 2, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'asking_for_help',
    question: 'You are struggling with a mental health challenge but fear judgement. What is the best first step?',
    questionImage: 'asking_help.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Talk to a trusted person or a health professional confidentially', correct: true },
      { id: 'b', label: 'Handle it alone — mental health is private', correct: false },
      { id: 'c', label: 'Post about it on social media to raise awareness', correct: false },
      { id: 'd', label: 'Wait until it becomes very serious before seeking help', correct: false },
    ],
    hint: 'Confidential help from a trusted person is safe and effective.',
    explanation: 'Talking to a trusted person or professional is the safest first step. Health professionals keep information confidential. Early help leads to better outcomes.',
  },
  {
    id: 'ca_t2_int_4', skill: 'communication_advocacy', tier: 2, difficulty: 'intermediate',
    type: 'true_false', topic: 'self_advocacy',
    question: 'In Kenya, it is illegal for an employer to dismiss you without following proper procedures.',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Kenya\'s Employment Act protects workers from unfair dismissal.',
    explanation: 'Kenya\'s Employment Act requires proper procedures including notice, warning letters, and hearings before dismissal. Unfair dismissal can be reported to the Employment and Labour Relations Court.',
  },
  {
    id: 'ca_t2_int_5', skill: 'communication_advocacy', tier: 2, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'expressing_needs',
    question: 'The three parts of an assertive message are: describe the behaviour, state how it makes you feel, and say what you ___.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Need or want to happen instead', correct: true },
      { id: 'b', label: 'Think the other person should do without asking them', correct: false },
      { id: 'c', label: 'Plan to do if they do not change', correct: false },
    ],
    hint: 'Assertive messages describe, feel, and request.',
    explanation: 'Assertive message: "When you [behaviour], I feel [emotion]. I need [request]." Example: "When meetings run late, I feel stressed. I need us to finish on time."',
  },
  {
    id: 'ca_t2_int_6', skill: 'communication_advocacy', tier: 2, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'saying_no',
    question: 'A family member asks to borrow money you cannot afford to give. How do you respond?',
    questionImage: 'saying_no.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: '"I care about you but I am not able to lend money right now — my budget does not allow it."', correct: true },
      { id: 'b', label: 'Give the money even though you cannot afford it to keep peace', correct: false },
      { id: 'c', label: 'Lie and say you have no money at all', correct: false },
      { id: 'd', label: 'Avoid the person until they stop asking', correct: false },
    ],
    hint: 'Honesty with compassion is the most sustainable approach.',
    explanation: 'A compassionate, honest response protects both you and the relationship. You do not need to explain your full financial situation — a simple decline is enough.',
  },
  {
    id: 'ca_t2_int_7', skill: 'communication_advocacy', tier: 2, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'self_advocacy',
    question: 'Put these steps in order for resolving a disagreement with a service provider.',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Gather evidence — receipts, messages, contracts', order: 1 },
      { id: 's2', label: 'Contact the organisation calmly and explain the issue', order: 2 },
      { id: 's3', label: 'Request a specific resolution — refund, replacement, or correction', order: 3 },
      { id: 's4', label: 'If unresolved, ask for the complaints department or manager', order: 4 },
      { id: 's5', label: 'File with the relevant regulatory body if still unresolved', order: 5 },
    ],
    hint: 'Evidence → contact → request → escalate → regulatory body.',
    explanation: 'Dispute resolution: gather evidence → contact calmly → request specific fix → escalate internally → regulatory body. Each step requires the previous one.',
  },

  // Tier 2 / Advanced
  {
    id: 'ca_t2_adv_1', skill: 'communication_advocacy', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'self_advocacy',
    question: 'You witness a colleague being treated unfairly. You are not directly involved. What should you do?',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Support the colleague privately, encourage them to report it, and offer to be a witness if needed', correct: true },
      { id: 'b', label: 'Stay out of it — it is not your problem', correct: false },
      { id: 'c', label: 'Confront the offender aggressively on behalf of the colleague', correct: false },
      { id: 'd', label: 'Report it yourself without telling the colleague', correct: false },
    ],
    hint: 'Supporting someone as a witness or ally is powerful advocacy.',
    explanation: 'Supporting the affected person privately, encouraging reporting, and offering to witness are the most helpful actions. Confronting alone may worsen the situation.',
  },
  {
    id: 'ca_t2_adv_2', skill: 'communication_advocacy', tier: 2, difficulty: 'advanced',
    type: 'drag_drop', topic: 'expressing_needs',
    question: 'Sort these communication styles into the correct category.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'st1', label: '"I understand your concern. Here is what I can do..."', targetZone: 'assertive' },
      { id: 'st2', label: 'Agreeing to everything and feeling resentful', targetZone: 'passive' },
      { id: 'st3', label: '"That is completely unreasonable and you know it!"', targetZone: 'aggressive' },
      { id: 'st4', label: '"I need more time to complete this — is that possible?"', targetZone: 'assertive' },
      { id: 'st5', label: 'Giving the silent treatment when upset', targetZone: 'passive' },
      { id: 'st6', label: 'Interrupting repeatedly to make your point', targetZone: 'aggressive' },
    ],
    dropZones: [
      { id: 'assertive', label: 'Assertive' },
      { id: 'passive', label: 'Passive' },
      { id: 'aggressive', label: 'Aggressive' },
    ],
    hint: 'Assertive: clear and respectful. Passive: avoids. Aggressive: attacks.',
    explanation: 'Assertive: acknowledges and responds constructively. Passive: suppresses and avoids. Aggressive: attacks, interrupts, and escalates conflict.',
  },
  {
    id: 'ca_t2_adv_3', skill: 'communication_advocacy', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'asking_for_help',
    question: 'You are caring for an elderly parent who refuses help even though they clearly need it. How do you approach this?',
    questionImage: 'asking_help.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Listen to their concerns, acknowledge their dignity, and introduce help gradually', correct: true },
      { id: 'b', label: 'Force the help — you know what is best for them', correct: false },
      { id: 'c', label: 'Give up and let them manage alone', correct: false },
      { id: 'd', label: 'Tell all relatives to pressure them into accepting help', correct: false },
    ],
    hint: 'Dignity and autonomy matter at every age.',
    explanation: 'Listening first shows respect. Acknowledging dignity reduces resistance. Gradual introduction of help — starting with small tasks — is more successful than forcing it.',
  },
  {
    id: 'ca_t2_adv_4', skill: 'communication_advocacy', tier: 2, difficulty: 'advanced',
    type: 'true_false', topic: 'self_advocacy',
    question: 'Persons with disabilities in Kenya are protected by the Persons with Disabilities Act 2003.',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Kenya has specific legislation protecting people with disabilities.',
    explanation: 'The Persons with Disabilities Act 2003 and the Constitution protect rights of persons with disabilities including access, employment, and non-discrimination.',
  },
  {
    id: 'ca_t2_adv_5', skill: 'communication_advocacy', tier: 2, difficulty: 'advanced',
    type: 'fill_blank', topic: 'expressing_needs',
    question: 'In a difficult conversation, asking "What would help you feel better about this situation?" shifts the focus from blame to ___.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Solutions and collaboration', correct: true },
      { id: 'b', label: 'More arguments and complaints', correct: false },
      { id: 'c', label: 'The other person\'s feelings only', correct: false },
    ],
    hint: 'Solution-focused questions move conversations forward.',
    explanation: 'Asking about what would help redirects from the problem to the solution. It shows you care about resolution, not just being right.',
  },
  {
    id: 'ca_t2_adv_6', skill: 'communication_advocacy', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'self_advocacy',
    question: 'A government office keeps redirecting you without resolving your issue. What should you do?',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Ask for the name and title of who you are speaking with, document everything, and request to speak to a supervisor', correct: true },
      { id: 'b', label: 'Give up — government offices are impossible to deal with', correct: false },
      { id: 'c', label: 'Shout and demand service', correct: false },
      { id: 'd', label: 'Come back every day until someone helps', correct: false },
    ],
    hint: 'Documentation and escalation are your most powerful tools in bureaucratic systems.',
    explanation: 'Getting names and titles creates accountability. Documentation shows a pattern. Requesting a supervisor escalates appropriately. Persistence through proper channels works.',
  },
  {
    id: 'ca_t2_adv_7', skill: 'communication_advocacy', tier: 2, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'self_advocacy',
    question: 'Put these steps in order for advocating for your rights in a formal setting.',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Know your rights — research the relevant laws or policies', order: 1 },
      { id: 's2', label: 'State your case clearly and specifically with evidence', order: 2 },
      { id: 's3', label: 'Remain calm and professional throughout', order: 3 },
      { id: 's4', label: 'Request a specific outcome or action', order: 4 },
      { id: 's5', label: 'Follow up in writing after verbal discussions', order: 5 },
    ],
    hint: 'Know rights → state case → stay calm → request outcome → follow up in writing.',
    explanation: 'Formal advocacy: know your rights → state clearly → stay professional → request specific outcome → follow up in writing. Written records are crucial.',
  },

  // =========================================================================
  // TIER 3 — INDEPENDENCE
  // =========================================================================

  // Tier 3 / Easy
  {
    id: 'ca_t3_easy_1', skill: 'communication_advocacy', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'self_advocacy',
    question: 'You are not satisfied with a medical diagnosis and want a second opinion. What is your right?',
    questionImage: 'asking_help.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'You have the right to seek a second opinion from another qualified doctor', correct: true },
      { id: 'b', label: 'You must accept the first doctor\'s opinion — they are the expert', correct: false },
      { id: 'c', label: 'You can only get a second opinion if the first doctor approves', correct: false },
      { id: 'd', label: 'Seeking another opinion is disrespectful to the first doctor', correct: false },
    ],
    hint: 'Second opinions are a recognised patient right.',
    explanation: 'You have the right to seek a second medical opinion. This is not disrespectful — it is responsible healthcare. Doctors expect and accept this practice.',
  },
  {
    id: 'ca_t3_easy_2', skill: 'communication_advocacy', tier: 3, difficulty: 'easy',
    type: 'true_false', topic: 'expressing_needs',
    question: 'Using "I" statements instead of "you" statements reduces defensiveness in difficult conversations.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: '"I feel..." focuses on your experience. "You did..." sounds like blame.',
    explanation: '"I feel worried when you come home late" is less confrontational than "You always come home late and never consider others." I-statements invite dialogue.',
  },
  {
    id: 'ca_t3_easy_3', skill: 'communication_advocacy', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'asking_for_help',
    question: 'A community member is clearly struggling but has not asked for help. How do you approach them?',
    questionImage: 'asking_help.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Approach privately, express genuine concern, and ask if there is anything they need', correct: true },
      { id: 'b', label: 'Tell others in the community so everyone can help at once', correct: false },
      { id: 'c', label: 'Wait for them to ask — it is not your place', correct: false },
      { id: 'd', label: 'Assume they are fine if they have not said anything', correct: false },
    ],
    hint: 'A private, genuine check-in opens the door without pressure.',
    explanation: 'A private, non-judgmental approach respects dignity. Asking "Is there anything I can do?" gives them choice without creating public embarrassment.',
  },
  {
    id: 'ca_t3_easy_4', skill: 'communication_advocacy', tier: 3, difficulty: 'easy',
    type: 'fill_blank', topic: 'self_advocacy',
    question: 'When speaking to an authority figure about a concern, bringing ___ makes your case stronger.',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Written evidence or documentation', correct: true },
      { id: 'b', label: 'As many people as possible to create pressure', correct: false },
      { id: 'c', label: 'Emotional displays to show how serious it is', correct: false },
    ],
    hint: 'Facts and documentation are more persuasive than emotions alone.',
    explanation: 'Written evidence — receipts, records, dates, names — strengthens your case significantly. It shows you are serious and prepared, not just complaining.',
  },
  {
    id: 'ca_t3_easy_5', skill: 'communication_advocacy', tier: 3, difficulty: 'easy',
    type: 'true_false', topic: 'saying_no',
    question: 'Once you have said yes to something, you cannot change your mind later.',
    questionImage: 'saying_no.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Circumstances change — so can your decision.',
    explanation: 'You can change your mind respectfully: "I agreed earlier but I have since realised I cannot commit to this — I apologise for any inconvenience." Circumstances change.',
  },
  {
    id: 'ca_t3_easy_6', skill: 'communication_advocacy', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'expressing_needs',
    question: 'You are in a group meeting and your idea is repeatedly ignored. What do you do?',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Say "I would like to go back to the point I raised — I think it is worth discussing"', correct: true },
      { id: 'b', label: 'Stay quiet — your idea was probably not good enough', correct: false },
      { id: 'c', label: 'Get frustrated and leave the meeting', correct: false },
      { id: 'd', label: 'Wait until after the meeting to mention it privately', correct: false },
    ],
    hint: 'Assertively redirecting the conversation is your right in any meeting.',
    explanation: 'Politely redirecting to your point is assertive and appropriate. Groups benefit from hearing all ideas. Silence when ignored means your contribution is lost.',
  },
  {
    id: 'ca_t3_easy_7', skill: 'communication_advocacy', tier: 3, difficulty: 'easy',
    type: 'sequential_steps', topic: 'self_advocacy',
    question: 'Put these steps in order for reporting a human rights violation in Kenya.',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Document the violation — dates, witnesses, evidence', order: 1 },
      { id: 's2', label: 'Report to the relevant authority — police, employer, or institution', order: 2 },
      { id: 's3', label: 'Contact the Kenya National Human Rights Commission (KNHRC) if unresolved', order: 3 },
      { id: 's4', label: 'Seek legal aid if needed through organisations like FIDA Kenya', order: 4 },
      { id: 's5', label: 'Follow through persistently — rights cases often take time', order: 5 },
    ],
    hint: 'Document → report → KNHRC → legal aid → persist.',
    explanation: 'Rights reporting: document → report to authority → KNHRC → legal aid → persist. The Kenya National Human Rights Commission handles unresolved cases.',
  },

  // Tier 3 / Intermediate
  {
    id: 'ca_t3_int_1', skill: 'communication_advocacy', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'self_advocacy',
    question: 'You are supporting someone with a communication difficulty in a medical appointment. How do you help without taking over?',
    questionImage: 'asking_help.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Let them speak first, only clarify or add when they signal they need help, and check in with them throughout', correct: true },
      { id: 'b', label: 'Speak for them entirely — it is faster and clearer', correct: false },
      { id: 'c', label: 'Wait outside — your presence may be distracting', correct: false },
      { id: 'd', label: 'Write down everything they say before the appointment and read it out', correct: false },
    ],
    hint: 'Supporting means enabling, not replacing.',
    explanation: 'True support enables the person\'s own voice. Lead with listening, offer clarification only when invited, and check in regularly. Their autonomy is paramount.',
  },
  {
    id: 'ca_t3_int_2', skill: 'communication_advocacy', tier: 3, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'self_advocacy',
    question: 'Sort these advocacy actions into Individual Advocacy or Community Advocacy.',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'av1', label: 'Requesting a reasonable accommodation at work for yourself', targetZone: 'individual' },
      { id: 'av2', label: 'Organising a petition for better road conditions in your area', targetZone: 'community' },
      { id: 'av3', label: 'Disputing an incorrect bill at a hospital', targetZone: 'individual' },
      { id: 'av4', label: 'Starting a support group for caregivers in your community', targetZone: 'community' },
      { id: 'av5', label: 'Appealing an unfair school grade', targetZone: 'individual' },
      { id: 'av6', label: 'Campaigning for accessible public transport in your town', targetZone: 'community' },
    ],
    dropZones: [
      { id: 'individual', label: 'Individual advocacy — for yourself' },
      { id: 'community', label: 'Community advocacy — for a group' },
    ],
    hint: 'Individual advocacy addresses your own situation. Community advocacy addresses shared issues.',
    explanation: 'Individual: accommodations, bills, grades. Community: petitions, support groups, campaigns. Both are valid and important forms of advocacy.',
  },
  {
    id: 'ca_t3_int_3', skill: 'communication_advocacy', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'expressing_needs',
    question: 'You are in a leadership role and a team member comes to you with a complaint about another member. What is your first step?',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Listen fully without taking sides, thank them for coming to you, and tell them you will investigate fairly', correct: true },
      { id: 'b', label: 'Immediately confront the other team member', correct: false },
      { id: 'c', label: 'Dismiss the complaint — team conflicts are normal', correct: false },
      { id: 'd', label: 'Tell the complaining member to sort it out themselves', correct: false },
    ],
    hint: 'Fairness and listening come before action.',
    explanation: 'Listening without prejudgment is the foundation of fair leadership. Thank them for raising it, commit to fair investigation, and avoid immediate conclusions.',
  },
  {
    id: 'ca_t3_int_4', skill: 'communication_advocacy', tier: 3, difficulty: 'intermediate',
    type: 'true_false', topic: 'self_advocacy',
    question: 'In Kenya, citizens can report corruption to the Ethics and Anti-Corruption Commission (EACC).',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Kenya has specific anti-corruption reporting mechanisms.',
    explanation: 'The EACC investigates corruption and unethical conduct by public officers. Citizens can report corruption confidentially through their hotline or website.',
  },
  {
    id: 'ca_t3_int_5', skill: 'communication_advocacy', tier: 3, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'expressing_needs',
    question: 'Mediation is a process where a neutral ___ helps two parties reach a mutually acceptable agreement.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Third party or mediator', correct: true },
      { id: 'b', label: 'Judge or magistrate', correct: false },
      { id: 'c', label: 'Friend of one of the parties', correct: false },
    ],
    hint: 'Mediation is voluntary and requires someone outside the dispute.',
    explanation: 'A mediator is a neutral third party who facilitates communication. Unlike a judge, they do not make decisions — they help parties find their own agreement.',
  },
  {
    id: 'ca_t3_int_6', skill: 'communication_advocacy', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'self_advocacy',
    question: 'You discover your employer has been underpaying you for months against your contract. What steps do you take?',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Gather pay slips as evidence, raise with HR formally in writing, and contact the Labour Office if unresolved', correct: true },
      { id: 'b', label: 'Quit immediately without addressing it', correct: false },
      { id: 'c', label: 'Accept it — confronting employers is risky', correct: false },
      { id: 'd', label: 'Tell colleagues to all complain at once', correct: false },
    ],
    hint: 'Evidence, formal complaint, and labour law protection are your tools.',
    explanation: 'Document with pay slips and contract. Raise formally in writing — creates a record. Kenya Labour Office handles wage disputes. You are legally protected from retaliation for raising legitimate wage concerns.',
  },
  {
    id: 'ca_t3_int_7', skill: 'communication_advocacy', tier: 3, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'self_advocacy',
    question: 'Put these steps for facilitating a community meeting about a shared problem in the correct order.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Define the problem clearly and agree it affects the whole group', order: 1 },
      { id: 's2', label: 'Give everyone a chance to share their perspective without interruption', order: 2 },
      { id: 's3', label: 'Identify common ground and shared goals', order: 3 },
      { id: 's4', label: 'Brainstorm possible solutions together', order: 4 },
      { id: 's5', label: 'Agree on actions and who is responsible for each', order: 5 },
    ],
    hint: 'Define → hear all → find common ground → solutions → assign actions.',
    explanation: 'Effective community meetings: clear problem → hear everyone → find common ground → brainstorm → assign clear actions. Every step matters for buy-in.',
  },

  // Tier 3 / Advanced
  {
    id: 'ca_t3_adv_1', skill: 'communication_advocacy', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'self_advocacy',
    question: 'You are advocating for a change in policy at a community organisation. What approach is most likely to succeed?',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Present evidence of the problem, propose a specific alternative, and build a coalition of supporters', correct: true },
      { id: 'b', label: 'Demand the change loudly at every meeting', correct: false },
      { id: 'c', label: 'Wait for leadership to notice the problem on their own', correct: false },
      { id: 'd', label: 'Threaten to leave if the change is not made', correct: false },
    ],
    hint: 'Evidence, specifics, and coalition are the three pillars of successful advocacy.',
    explanation: 'Advocacy success requires evidence (proves the problem), a specific proposal (provides the solution), and a coalition (demonstrates shared concern). This is persuasion, not pressure.',
  },
  {
    id: 'ca_t3_adv_2', skill: 'communication_advocacy', tier: 3, difficulty: 'advanced',
    type: 'drag_drop', topic: 'expressing_needs',
    question: 'Sort these conflict resolution approaches into Collaborative or Competitive.',
    questionImage: 'communication_basic.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'cr1', label: '"What would work for both of us?"', targetZone: 'collaborative' },
      { id: 'cr2', label: '"I will win this argument no matter what"', targetZone: 'competitive' },
      { id: 'cr3', label: '"Let us find a solution that addresses your concern and mine"', targetZone: 'collaborative' },
      { id: 'cr4', label: '"You will agree with me or face consequences"', targetZone: 'competitive' },
      { id: 'cr5', label: '"I hear your concern — here is mine. Where can we find middle ground?"', targetZone: 'collaborative' },
      { id: 'cr6', label: '"My way is the only sensible way"', targetZone: 'competitive' },
    ],
    dropZones: [
      { id: 'collaborative', label: 'Collaborative — seeks mutual solution' },
      { id: 'competitive', label: 'Competitive — seeks to win' },
    ],
    hint: 'Collaborative seeks win-win. Competitive seeks win-lose.',
    explanation: 'Collaborative: asks what works for both, seeks middle ground. Competitive: focuses on winning, uses pressure. Collaborative approaches build longer-lasting solutions.',
  },
  {
    id: 'ca_t3_adv_3', skill: 'communication_advocacy', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'self_advocacy',
    question: 'A person with a disability is denied entry to a public building due to lack of accessible facilities. What advocacy steps apply?',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Document the denial, report to the National Council for Persons with Disabilities (NCPWD), and consider legal action', correct: true },
      { id: 'b', label: 'Accept it — some buildings are just not accessible', correct: false },
      { id: 'c', label: 'Post about it on social media as the first action', correct: false },
      { id: 'd', label: 'Only complain if it happens repeatedly', correct: false },
    ],
    hint: 'Kenya law requires public buildings to be accessible. NCPWD handles violations.',
    explanation: 'Kenya\'s Persons with Disabilities Act requires public buildings to be accessible. The NCPWD enforces this. Document and report — one case creates precedent for others.',
  },
  {
    id: 'ca_t3_adv_4', skill: 'communication_advocacy', tier: 3, difficulty: 'advanced',
    type: 'true_false', topic: 'expressing_needs',
    question: 'Effective advocacy sometimes requires patience — change in systems or policies can take months or years.',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Systemic change is slow — but sustained advocacy works.',
    explanation: 'Policy and systemic change is rarely immediate. Sustained, documented, respectful advocacy over time builds the case for change. Giving up too early means others do not benefit.',
  },
  {
    id: 'ca_t3_adv_5', skill: 'communication_advocacy', tier: 3, difficulty: 'advanced',
    type: 'fill_blank', topic: 'self_advocacy',
    question: 'When advocating for others, the most important principle is to ___ their voice rather than speak for them.',
    questionImage: 'asking_help.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Amplify or support', correct: true },
      { id: 'b', label: 'Replace or override', correct: false },
      { id: 'c', label: 'Summarise and simplify', correct: false },
    ],
    hint: 'Good advocacy empowers — it does not take over.',
    explanation: 'Advocacy for others should amplify their voice, not replace it. Ask what they want, support them in saying it, and step back when they can speak for themselves.',
  },
  {
    id: 'ca_t3_adv_6', skill: 'communication_advocacy', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'self_advocacy',
    question: 'You want to raise awareness about a community issue. What is the most effective and sustainable approach?',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Build a coalition, gather data, engage local leaders, and present solutions — not just problems', correct: true },
      { id: 'b', label: 'Share emotional posts on social media and hope they go viral', correct: false },
      { id: 'c', label: 'Organise a one-time protest and hope for coverage', correct: false },
      { id: 'd', label: 'Write a letter to a newspaper', correct: false },
    ],
    hint: 'Sustained, evidence-based, solution-focused advocacy creates lasting change.',
    explanation: 'Coalition building creates collective voice. Data makes the case credible. Local leader engagement builds political will. Proposing solutions — not just problems — shows readiness for change.',
  },
  {
    id: 'ca_t3_adv_7', skill: 'communication_advocacy', tier: 3, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'self_advocacy',
    question: 'Put these steps for building a successful community advocacy campaign in the correct order.',
    questionImage: 'self_advocacy.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Clearly define the problem and who it affects', order: 1 },
      { id: 's2', label: 'Research the relevant laws, rights, and policies', order: 2 },
      { id: 's3', label: 'Build a coalition of people who share the concern', order: 3 },
      { id: 's4', label: 'Develop a specific, realistic solution to propose', order: 4 },
      { id: 's5', label: 'Engage decision-makers with evidence and your proposal', order: 5 },
      { id: 's6', label: 'Sustain the campaign with regular updates and follow-through', order: 6 },
    ],
    hint: 'Define → research → coalition → solution → engage → sustain.',
    explanation: 'Advocacy campaign: define problem → research rights → build coalition → develop solution → engage decision-makers → sustain effort. Every step builds on the previous.',
  },
]
