// taskData_digital.ts
// Digital Safety — 63 tasks
// 3 Tiers × 3 Difficulties × 7 Tasks = 63

export type TaskDigital = {
  id: string
  skill: string
  tier: 1 | 2 | 3
  difficulty: 'easy' | 'intermediate' | 'advanced'
  type: 'tap_select' | 'scenario_choice' | 'true_false' | 'fill_blank' | 'sequential_steps' | 'drag_drop'
  topic: string
  question: string
  context?: string
  options?: { id: string; label: string; correct: boolean; image?: string }[]
  steps?: { id: string; label: string; order: number }[]
  dragItems?: { id: string; label: string; targetZone: string }[]
  dropZones?: { id: string; label: string }[]
  hint: string
  explanation: string
  questionImage?: string
  imageLayout?: 'context' | 'options'
}

export const DIGITAL_SAFETY_TASKS: TaskDigital[] = [

  // =========================================================================
  // TIER 1 — FOUNDATION
  // =========================================================================

  // Tier 1 / Easy
  {
    id: 'ds_t1_easy_1', skill: 'digital_safety', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'passwords',
    question: 'You should share your password with your best friend so they can help you if you forget it.',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Passwords are private — even from people you trust.',
    explanation: 'Never share your password with anyone — not even close friends. If they know it, your account is no longer secure.',
  },
  {
    id: 'ds_t1_easy_2', skill: 'digital_safety', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'scams',
    question: 'You receive a message saying you won KES 100,000 but must pay KES 500 to claim it. What is this?',
    questionImage: 'scam_message.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'A scam — you cannot win money you did not enter for', correct: true },
      { id: 'b', label: 'A real prize — pay and collect your money', correct: false },
      { id: 'c', label: 'A bank promotion — it must be real', correct: false },
      { id: 'd', label: 'A government offer — safe to trust', correct: false },
    ],
    hint: 'If you must pay to receive a prize, it is a scam.',
    explanation: 'Legitimate prizes never require payment to claim. Any message asking you to pay to receive money is a scam.',
  },
  {
    id: 'ds_t1_easy_3', skill: 'digital_safety', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'personal_information',
    question: 'It is safe to share your ID number and home address with anyone who asks online.',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Personal information can be used to steal your identity.',
    explanation: 'Your ID number and home address are personal information. Sharing them online can lead to identity theft and fraud.',
  },
  {
    id: 'ds_t1_easy_4', skill: 'digital_safety', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'passwords',
    question: 'Which of these is the strongest password?',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Nairobi2024!@#', correct: true },
      { id: 'b', label: '12345678', correct: false },
      { id: 'c', label: 'password', correct: false },
      { id: 'd', label: 'your name and birth year', correct: false },
    ],
    hint: 'Strong passwords mix letters, numbers, and symbols.',
    explanation: 'Strong passwords use uppercase, lowercase, numbers, and symbols. Avoid simple sequences, the word "password", or personal information.',
  },
  {
    id: 'ds_t1_easy_5', skill: 'digital_safety', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'safe_browsing',
    question: 'You should click every link sent to you by unknown numbers on WhatsApp.',
    questionImage: 'phone_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Unknown senders sending links is a common scam method.',
    explanation: 'Never click links from unknown senders. They can install malware, steal your data, or take you to fake websites.',
  },
  {
    id: 'ds_t1_easy_6', skill: 'digital_safety', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'scams',
    question: 'Someone calls claiming to be from your bank and asks for your PIN. What should you do?',
    questionImage: 'phone_call.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Hang up — banks never ask for your PIN', correct: true },
      { id: 'b', label: 'Give them your PIN — they are from the bank', correct: false },
      { id: 'c', label: 'Give them half your PIN to verify', correct: false },
      { id: 'd', label: 'Ask them to call back tomorrow', correct: false },
    ],
    hint: 'No legitimate bank or organisation ever asks for your PIN.',
    explanation: 'Hang up immediately. Banks never ask for your PIN, password, or OTP over the phone. Call the official bank number to verify.',
  },
  {
    id: 'ds_t1_easy_7', skill: 'digital_safety', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'personal_information',
    question: 'Using public WiFi at a cafe to check your M-Pesa balance is completely safe.',
    questionImage: 'public_wifi.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Public WiFi networks can be monitored by others.',
    explanation: 'Public WiFi is not secure. Others on the same network can potentially intercept your data. Avoid accessing financial accounts on public WiFi.',
  },

  // Tier 1 / Intermediate
  {
    id: 'ds_t1_int_1', skill: 'digital_safety', tier: 1, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'scams',
    question: 'You receive an SMS: "Your M-Pesa account has been suspended. Click this link to reactivate: www.mpesa-verify.co". What do you do?',
    questionImage: 'scam_message.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Delete the message — this is a phishing scam', correct: true },
      { id: 'b', label: 'Click the link and enter your details', correct: false },
      { id: 'c', label: 'Forward it to friends to warn them', correct: false },
      { id: 'd', label: 'Reply to ask if it is real', correct: false },
    ],
    hint: 'M-Pesa never sends links via SMS asking for your details.',
    explanation: 'This is phishing — a fake message designed to steal your login details. Official M-Pesa communications never include suspicious links. Call 0722000000 to verify.',
  },
  {
    id: 'ds_t1_int_2', skill: 'digital_safety', tier: 1, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'passwords',
    question: 'Sort these password practices into Safe or Unsafe.',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'p1', label: 'Using a different password for each account', targetZone: 'safe' },
      { id: 'p2', label: 'Using your birthday as your PIN', targetZone: 'unsafe' },
      { id: 'p3', label: 'Changing passwords every few months', targetZone: 'safe' },
      { id: 'p4', label: 'Writing your password on a note near your phone', targetZone: 'unsafe' },
      { id: 'p5', label: 'Using a mix of letters, numbers and symbols', targetZone: 'safe' },
      { id: 'p6', label: 'Using the same password for everything', targetZone: 'unsafe' },
    ],
    dropZones: [
      { id: 'safe', label: 'Safe practice' },
      { id: 'unsafe', label: 'Unsafe practice' },
    ],
    hint: 'Strong passwords are unique, complex, and kept private.',
    explanation: 'Safe: unique passwords, regular changes, complex combinations. Unsafe: birthdays, written notes, same password everywhere.',
  },
  {
    id: 'ds_t1_int_3', skill: 'digital_safety', tier: 1, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'personal_information',
    question: 'A new app asks for permission to access your contacts, camera, microphone, and location. The app is just a simple calculator. What should you do?',
    questionImage: 'phone_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Deny all unnecessary permissions — a calculator needs none of these', correct: true },
      { id: 'b', label: 'Accept all permissions — the app may need them', correct: false },
      { id: 'c', label: 'Delete your contacts first then accept', correct: false },
      { id: 'd', label: 'Only accept location permission', correct: false },
    ],
    hint: 'Apps should only access what they genuinely need to function.',
    explanation: 'A calculator needs no permissions. Granting unnecessary access allows apps to collect your personal data. Only approve permissions that make sense for the app.',
  },
  {
    id: 'ds_t1_int_4', skill: 'digital_safety', tier: 1, difficulty: 'intermediate',
    type: 'true_false', topic: 'safe_browsing',
    question: 'A website starting with "https://" is more secure than one starting with "http://".',
    questionImage: 'public_wifi.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'The "s" in https stands for secure.',
    explanation: 'HTTPS encrypts data between you and the website. HTTP does not. Always look for https:// especially when entering passwords or payment details.',
  },
  {
    id: 'ds_t1_int_5', skill: 'digital_safety', tier: 1, difficulty: 'intermediate',
    type: 'tap_select', topic: 'scams',
    question: 'What is "phishing"?',
    questionImage: 'scam_message.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Fake messages or websites designed to steal your personal information', correct: true },
      { id: 'b', label: 'A type of online fishing game', correct: false },
      { id: 'c', label: 'A way to earn money online', correct: false },
      { id: 'd', label: 'A security feature that protects your phone', correct: false },
    ],
    hint: 'Phishing "fishes" for your personal information using fake bait.',
    explanation: 'Phishing uses fake messages, emails, or websites that look real to trick you into giving personal information like passwords or card numbers.',
  },
  {
    id: 'ds_t1_int_6', skill: 'digital_safety', tier: 1, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'safe_browsing',
    question: 'You want to download a free version of an expensive app. A website offers it for free outside the official app store. What should you do?',
    questionImage: 'phone_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Do not download — unofficial apps often contain malware', correct: true },
      { id: 'b', label: 'Download it — free is always better', correct: false },
      { id: 'c', label: 'Download and scan it afterwards', correct: false },
      { id: 'd', label: 'Download on a friend\'s phone first to test', correct: false },
    ],
    hint: 'If an app is free outside the official store, there is usually a harmful reason.',
    explanation: 'Unofficial app sources often bundle malware that steals data or money. Only download apps from official stores — Google Play Store or Apple App Store.',
  },
  {
    id: 'ds_t1_int_7', skill: 'digital_safety', tier: 1, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'passwords',
    question: 'A two-factor authentication (2FA) code sent to your phone adds an extra ___ to your account.',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Layer of security', correct: true },
      { id: 'b', label: 'Password to remember', correct: false },
      { id: 'c', label: 'Risk to your account', correct: false },
    ],
    hint: 'Two-factor means two steps to verify it is really you.',
    explanation: '2FA adds a second verification step — even if someone steals your password, they cannot access your account without your phone.',
  },

  // Tier 1 / Advanced
  {
    id: 'ds_t1_adv_1', skill: 'digital_safety', tier: 1, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'scams',
    question: 'A friend\'s WhatsApp account sends you a message: "I am in trouble, please send KES 2,000 via M-Pesa urgently, I will explain later." What do you do?',
    questionImage: 'phone_call.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Call your friend directly on their number to verify before sending anything', correct: true },
      { id: 'b', label: 'Send the money — your friend needs help', correct: false },
      { id: 'c', label: 'Reply on WhatsApp asking for more details', correct: false },
      { id: 'd', label: 'Send half the amount to be safe', correct: false },
    ],
    hint: 'Hacked accounts are used to scam contacts. Always verify by calling.',
    explanation: 'WhatsApp accounts are often hacked and used to scam the victim\'s contacts. Always call your friend directly to verify before sending any money.',
  },
  {
    id: 'ds_t1_adv_2', skill: 'digital_safety', tier: 1, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'passwords',
    question: 'Your phone was stolen. Put these security steps in the correct order.',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Report the theft to police and your network provider', order: 1 },
      { id: 's2', label: 'Call your bank to block your mobile banking', order: 2 },
      { id: 's3', label: 'Change passwords for all accounts from another device', order: 3 },
      { id: 's4', label: 'Contact M-Pesa to secure your account', order: 4 },
      { id: 's5', label: 'Enable remote wipe if available to clear phone data', order: 5 },
    ],
    hint: 'Secure your finances first, then your accounts, then the device.',
    explanation: 'Stolen phone: report → block bank → change passwords → secure M-Pesa → remote wipe. Speed matters — act within minutes.',
  },
  {
    id: 'ds_t1_adv_3', skill: 'digital_safety', tier: 1, difficulty: 'advanced',
    type: 'drag_drop', topic: 'personal_information',
    question: 'Sort these pieces of information into Safe to Share Online or Keep Private.',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'i1', label: 'Your first name', targetZone: 'safe' },
      { id: 'i2', label: 'Your ID number', targetZone: 'private' },
      { id: 'i3', label: 'Your favourite food', targetZone: 'safe' },
      { id: 'i4', label: 'Your M-Pesa PIN', targetZone: 'private' },
      { id: 'i5', label: 'Your home address', targetZone: 'private' },
      { id: 'i6', label: 'Your bank account number', targetZone: 'private' },
    ],
    dropZones: [
      { id: 'safe', label: 'Safe to share online' },
      { id: 'private', label: 'Keep private' },
    ],
    hint: 'Anything that identifies you financially or physically should stay private.',
    explanation: 'Safe: first name, favourite food. Private: ID number, M-Pesa PIN, home address, bank account. Financial and location data enables fraud.',
  },
  {
    id: 'ds_t1_adv_4', skill: 'digital_safety', tier: 1, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'safe_browsing',
    question: 'You notice your phone is running very slowly, getting hot, and using mobile data even when you are not using it. What might be happening?',
    questionImage: 'phone_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Your phone may have malware — run a security scan and remove suspicious apps', correct: true },
      { id: 'b', label: 'Your phone is just old — nothing to worry about', correct: false },
      { id: 'c', label: 'You need to charge it more frequently', correct: false },
      { id: 'd', label: 'The weather is causing it', correct: false },
    ],
    hint: 'Malware often runs secretly in the background using data and battery.',
    explanation: 'Slow performance, overheating, and unexplained data use are signs of malware. Run a trusted security app, remove suspicious apps, and consider a factory reset.',
  },
  {
    id: 'ds_t1_adv_5', skill: 'digital_safety', tier: 1, difficulty: 'advanced',
    type: 'true_false', topic: 'scams',
    question: 'If a scammer already has your name and phone number, they have enough to steal your M-Pesa.',
    questionImage: 'scam_message.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'They also need your PIN or OTP to access your account.',
    explanation: 'A name and number alone cannot access M-Pesa. They also need your PIN or a one-time code. Never share your PIN or OTP with anyone.',
  },
  {
    id: 'ds_t1_adv_6', skill: 'digital_safety', tier: 1, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'personal_information',
    question: 'You want to sell your old phone. Before handing it over, what must you do?',
    questionImage: 'phone_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Factory reset the phone to erase all personal data', correct: true },
      { id: 'b', label: 'Delete only your photos and give it as is', correct: false },
      { id: 'c', label: 'Log out of WhatsApp and sell it', correct: false },
      { id: 'd', label: 'Nothing — the buyer cannot access your data', correct: false },
    ],
    hint: 'Deleting files is not enough — a factory reset wipes everything.',
    explanation: 'Factory reset erases all data properly. Just deleting files or logging out leaves data recoverable. Always factory reset before selling or giving away a device.',
  },
  {
    id: 'ds_t1_adv_7', skill: 'digital_safety', tier: 1, difficulty: 'advanced',
    type: 'fill_blank', topic: 'safe_browsing',
    question: 'Keeping your phone\'s operating system updated is important because updates often include ___.',
    questionImage: 'phone_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Security patches that fix vulnerabilities', correct: true },
      { id: 'b', label: 'New games and entertainment', correct: false },
      { id: 'c', label: 'Bigger storage capacity', correct: false },
    ],
    hint: 'Updates fix weaknesses that hackers could exploit.',
    explanation: 'Security updates patch vulnerabilities that hackers use to access devices. Always install updates promptly — especially security updates.',
  },

  // =========================================================================
  // TIER 2 — APPLICATION
  // =========================================================================

  // Tier 2 / Easy
  {
    id: 'ds_t2_easy_1', skill: 'digital_safety', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'scams',
    question: 'You receive a call: "Congratulations! You have won a Safaricom prize. Send KES 200 activation fee to this number." What do you do?',
    questionImage: 'phone_call.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Hang up — this is a common scam', correct: true },
      { id: 'b', label: 'Send KES 200 — it is a small amount', correct: false },
      { id: 'c', label: 'Ask them to send proof first', correct: false },
      { id: 'd', label: 'Call a friend for advice before sending', correct: false },
    ],
    hint: 'Real prizes never require payment to claim.',
    explanation: 'Hanging up is correct. Any "prize" requiring payment is a scam. Safaricom never calls to ask for money to release prizes.',
  },
  {
    id: 'ds_t2_easy_2', skill: 'digital_safety', tier: 2, difficulty: 'easy',
    type: 'true_false', topic: 'passwords',
    question: 'You should use the same password for your email, M-Pesa, and social media to make it easier to remember.',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'If one account is hacked, all accounts with the same password are at risk.',
    explanation: 'Using the same password everywhere means one breach compromises all accounts. Use different passwords for each important account.',
  },
  {
    id: 'ds_t2_easy_3', skill: 'digital_safety', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'personal_information',
    question: 'A job advertisement online asks for your ID number, bank account details, and MPESA PIN to "process your application." What should you do?',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Do not apply — legitimate employers never ask for bank PINs', correct: true },
      { id: 'b', label: 'Apply — it must be required for payroll setup', correct: false },
      { id: 'c', label: 'Give the information but change your PIN afterwards', correct: false },
      { id: 'd', label: 'Ask a family member to apply using their details instead', correct: false },
    ],
    hint: 'No real employer needs your M-Pesa PIN.',
    explanation: 'This is a job scam. Legitimate employers never ask for PINs. Report such adverts and do not engage further.',
  },
  {
    id: 'ds_t2_easy_4', skill: 'digital_safety', tier: 2, difficulty: 'easy',
    type: 'tap_select', topic: 'safe_browsing',
    question: 'Which of these is the safest way to access your bank account online?',
    questionImage: 'public_wifi.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Using your own mobile data on your personal phone', correct: true },
      { id: 'b', label: 'Using public WiFi at a shopping mall', correct: false },
      { id: 'c', label: 'Using a friend\'s phone on their home WiFi', correct: false },
      { id: 'd', label: 'Using a shared computer at a cyber cafe', correct: false },
    ],
    hint: 'Your own device and data connection is the only fully private option.',
    explanation: 'Your own data on your own phone is safest. Public WiFi, shared computers, and other people\'s devices all risk your data being seen or saved.',
  },
  {
    id: 'ds_t2_easy_5', skill: 'digital_safety', tier: 2, difficulty: 'easy',
    type: 'true_false', topic: 'scams',
    question: 'If you accidentally click a scam link but do not enter any information, you are completely safe.',
    questionImage: 'scam_message.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Some malware downloads automatically when you visit a page.',
    explanation: 'Some malicious sites install malware just from visiting — even without entering information. Close the browser immediately and run a security scan.',
  },
  {
    id: 'ds_t2_easy_6', skill: 'digital_safety', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'passwords',
    question: 'You forgot your email password. The safest way to recover it is:',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Use the official "Forgot Password" feature on the login page', correct: true },
      { id: 'b', label: 'Ask a friend who knows passwords to help you guess it', correct: false },
      { id: 'c', label: 'Search online for a tool that can recover it', correct: false },
      { id: 'd', label: 'Create a new account and abandon the old one', correct: false },
    ],
    hint: 'Official recovery features are built precisely for this situation.',
    explanation: 'Always use the official password recovery feature. Third-party tools may steal your account. Friends guessing means sharing account access.',
  },
  {
    id: 'ds_t2_easy_7', skill: 'digital_safety', tier: 2, difficulty: 'easy',
    type: 'true_false', topic: 'personal_information',
    question: 'Posting photos of your house, car, and location on social media can help burglars know when you are away.',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Criminals monitor social media to identify targets and opportunities.',
    explanation: 'Sharing your location, home, and travel plans on social media tells criminals when you are away and where your valuables are. Limit what you post publicly.',
  },

  // Tier 2 / Intermediate
  {
    id: 'ds_t2_int_1', skill: 'digital_safety', tier: 2, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'scams',
    question: 'You realise you have been scammed and sent KES 3,000 via M-Pesa. Put these response steps in the correct order.',
    questionImage: 'phone_call.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Call Safaricom immediately on 0722000000', order: 1 },
      { id: 's2', label: 'Report the scam number to Safaricom to block it', order: 2 },
      { id: 's3', label: 'File a report with the police', order: 3 },
      { id: 's4', label: 'Warn friends and family about the scam method', order: 4 },
      { id: 's5', label: 'Change all your account PINs and passwords', order: 5 },
    ],
    hint: 'Act fast — contact Safaricom first as they may be able to reverse the transaction.',
    explanation: 'Call Safaricom immediately — quick action may recover money. Then report, file police report, warn others, and secure all accounts.',
  },
  {
    id: 'ds_t2_int_2', skill: 'digital_safety', tier: 2, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'personal_information',
    question: 'You want to join an online marketplace to sell items. Which information is safe to include in your seller profile?',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Your first name, phone number, and general area (not exact address)', correct: true },
      { id: 'b', label: 'Full name, ID number, and exact home address', correct: false },
      { id: 'c', label: 'Your M-Pesa number and bank account', correct: false },
      { id: 'd', label: 'Your full personal details for trust and credibility', correct: false },
    ],
    hint: 'Share only what is necessary to conduct business safely.',
    explanation: 'A first name, phone number, and general area are enough for selling. Your ID, exact address, and financial details are private and unnecessary.',
  },
  {
    id: 'ds_t2_int_3', skill: 'digital_safety', tier: 2, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'scams',
    question: 'Sort these messages into Likely Scam or Likely Legitimate.',
    questionImage: 'scam_message.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'm1', label: '"You have won KES 50,000! Send KES 500 to claim"', targetZone: 'scam' },
      { id: 'm2', label: '"Your Safaricom bill is ready. Log in at safaricom.co.ke"', targetZone: 'legit' },
      { id: 'm3', label: '"Urgent: Your account is suspended. Click here now"', targetZone: 'scam' },
      { id: 'm4', label: '"Your M-Pesa transaction of KES 500 was successful"', targetZone: 'legit' },
      { id: 'm5', label: '"Send your PIN to verify your identity"', targetZone: 'scam' },
      { id: 'm6', label: '"Your KCB statement is attached"', targetZone: 'legit' },
    ],
    dropZones: [
      { id: 'scam', label: 'Likely Scam' },
      { id: 'legit', label: 'Likely Legitimate' },
    ],
    hint: 'Scams ask for money or personal info. Legitimate messages inform without demanding.',
    explanation: 'Scams: prizes requiring payment, urgent account threats, PIN requests. Legitimate: billing notices, transaction confirmations, statements.',
  },
  {
    id: 'ds_t2_int_4', skill: 'digital_safety', tier: 2, difficulty: 'intermediate',
    type: 'true_false', topic: 'safe_browsing',
    question: 'Installing every app that looks useful from the Play Store is always safe.',
    questionImage: 'phone_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Even official app stores have had malicious apps published.',
    explanation: 'Even Play Store apps can be malicious. Check ratings, reviews, developer reputation, and requested permissions before installing any app.',
  },
  {
    id: 'ds_t2_int_5', skill: 'digital_safety', tier: 2, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'passwords',
    question: 'You use M-Pesa on a shared family phone. What should you do after each session?',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Log out completely and ensure no PIN or transaction details are saved', correct: true },
      { id: 'b', label: 'Nothing — family members can be trusted', correct: false },
      { id: 'c', label: 'Lock the phone screen so others cannot see', correct: false },
      { id: 'd', label: 'Change the phone PIN after each use', correct: false },
    ],
    hint: 'Logging out removes your session from the shared device.',
    explanation: 'Always log out from shared devices. Even trusted family members should not have unintended access to your financial accounts.',
  },
  {
    id: 'ds_t2_int_6', skill: 'digital_safety', tier: 2, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'scams',
    question: 'Online romance scams often target victims by building ___ over weeks or months before asking for money.',
    questionImage: 'phone_call.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Trust and emotional connection', correct: true },
      { id: 'b', label: 'A business partnership', correct: false },
      { id: 'c', label: 'A shared phone number', correct: false },
    ],
    hint: 'They invest time to make you feel comfortable before asking.',
    explanation: 'Romance scammers build genuine-seeming relationships over time to gain trust. They then create emergencies requiring money transfers. Never send money to someone you have not met.',
  },
  {
    id: 'ds_t2_int_7', skill: 'digital_safety', tier: 2, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'personal_information',
    question: 'Your child uses your phone for school videos. What parental controls should you set?',
    questionImage: 'phone_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Restrict app downloads, set screen time limits, and block inappropriate content', correct: true },
      { id: 'b', label: 'Nothing — they are only watching school content', correct: false },
      { id: 'c', label: 'Give them their own social media account', correct: false },
      { id: 'd', label: 'Let them use the phone freely — children learn from exploration', correct: false },
    ],
    hint: 'Children need guided access to protect them from inappropriate content and spending.',
    explanation: 'Set restrictions on app downloads, screen time, and content. Children can accidentally access inappropriate content or spend money through in-app purchases.',
  },

  // Tier 2 / Advanced
  {
    id: 'ds_t2_adv_1', skill: 'digital_safety', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'scams',
    question: 'You receive an email that looks exactly like it is from your bank — same logo, colours, and format — asking you to verify your account by clicking a link. How do you verify if it is real?',
    questionImage: 'scam_message.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Do not click — call the official bank number or log in directly through the official website', correct: true },
      { id: 'b', label: 'Click the link — it looks exactly like the bank', correct: false },
      { id: 'c', label: 'Reply to the email to verify', correct: false },
      { id: 'd', label: 'Forward to a friend who knows about computers', correct: false },
    ],
    hint: 'Appearance alone cannot verify an email — check the sender address and go directly to the site.',
    explanation: 'Professional-looking emails can be faked perfectly. Never click links in emails — go directly to the bank website by typing the address yourself or call the official number.',
  },
  {
    id: 'ds_t2_adv_2', skill: 'digital_safety', tier: 2, difficulty: 'advanced',
    type: 'drag_drop', topic: 'safe_browsing',
    question: 'Sort these phone security practices into Good Habit or Bad Habit.',
    questionImage: 'phone_screen.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'h1', label: 'Lock phone with fingerprint or strong PIN', targetZone: 'good' },
      { id: 'h2', label: 'Keep Bluetooth on always for convenience', targetZone: 'bad' },
      { id: 'h3', label: 'Regularly back up your phone data', targetZone: 'good' },
      { id: 'h4', label: 'Use the same PIN for your phone and M-Pesa', targetZone: 'bad' },
      { id: 'h5', label: 'Enable remote tracking in case of theft', targetZone: 'good' },
      { id: 'h6', label: 'Install apps from any website offering free versions', targetZone: 'bad' },
    ],
    dropZones: [
      { id: 'good', label: 'Good security habit' },
      { id: 'bad', label: 'Bad security habit' },
    ],
    hint: 'Good habits protect data. Bad habits create vulnerabilities.',
    explanation: 'Good: fingerprint lock, backups, remote tracking. Bad: always-on Bluetooth (enables attacks), same PIN everywhere, unofficial app sources.',
  },
  {
    id: 'ds_t2_adv_3', skill: 'digital_safety', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'personal_information',
    question: 'You discover a photo of you was posted online without your permission and is being used negatively. What steps should you take?',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Screenshot evidence, report to the platform, contact police if threatening', correct: true },
      { id: 'b', label: 'Ignore it — it will be forgotten eventually', correct: false },
      { id: 'c', label: 'Post your own response publicly', correct: false },
      { id: 'd', label: 'Message the person who posted it directly', correct: false },
    ],
    hint: 'Document first, then report through official channels.',
    explanation: 'Screenshot evidence before it is removed. Report to the platform — all major platforms have abuse reporting. Contact police if threatening or criminal. Do not engage the attacker directly.',
  },
  {
    id: 'ds_t2_adv_4', skill: 'digital_safety', tier: 2, difficulty: 'advanced',
    type: 'true_false', topic: 'scams',
    question: 'In Kenya, you can report cybercrime to the Directorate of Criminal Investigations (DCI).',
    questionImage: 'phone_call.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Kenya has specific cybercrime reporting mechanisms.',
    explanation: 'The DCI handles cybercrime in Kenya. You can also report to the Communications Authority of Kenya (CA) and Safaricom for M-Pesa related fraud.',
  },
  {
    id: 'ds_t2_adv_5', skill: 'digital_safety', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'passwords',
    question: 'You want to use a password manager app. What should you look for?',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'A reputable app with strong encryption and regular security updates', correct: true },
      { id: 'b', label: 'The cheapest or free option regardless of reputation', correct: false },
      { id: 'c', label: 'An app made by an unknown developer with great reviews', correct: false },
      { id: 'd', label: 'Any app recommended by a friend', correct: false },
    ],
    hint: 'A password manager holds all your passwords — it must be trustworthy.',
    explanation: 'Use established password managers like Bitwarden or 1Password. Check reviews, encryption standards, and the developer\'s reputation before trusting any app with all your passwords.',
  },
  {
    id: 'ds_t2_adv_6', skill: 'digital_safety', tier: 2, difficulty: 'advanced',
    type: 'fill_blank', topic: 'safe_browsing',
    question: 'A VPN (Virtual Private Network) protects your privacy by ___ your internet traffic.',
    questionImage: 'public_wifi.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Encrypting and hiding', correct: true },
      { id: 'b', label: 'Blocking and stopping', correct: false },
      { id: 'c', label: 'Speeding up', correct: false },
    ],
    hint: 'VPN wraps your data so it cannot be read by others.',
    explanation: 'A VPN encrypts your internet traffic and hides your IP address. It is especially useful on public WiFi to prevent others from seeing your data.',
  },
  {
    id: 'ds_t2_adv_7', skill: 'digital_safety', tier: 2, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'personal_information',
    question: 'Put these steps for setting up a new phone securely in the correct order.',
    questionImage: 'phone_screen.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Set a strong lock screen PIN or fingerprint', order: 1 },
      { id: 's2', label: 'Enable encryption if not already on by default', order: 2 },
      { id: 's3', label: 'Only install apps from official stores', order: 3 },
      { id: 's4', label: 'Enable automatic security updates', order: 4 },
      { id: 's5', label: 'Set up remote tracking and wipe capability', order: 5 },
    ],
    hint: 'Secure the device first, then the apps, then enable automatic protection.',
    explanation: 'New phone security: lock screen → encryption → official apps only → auto updates → remote wipe. These five steps cover the main attack surfaces.',
  },

  // =========================================================================
  // TIER 3 — INDEPENDENCE
  // =========================================================================

  // Tier 3 / Easy
  {
    id: 'ds_t3_easy_1', skill: 'digital_safety', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'scams',
    question: 'An elderly parent calls you saying someone phoned them claiming to be you in an accident needing KES 10,000 urgently. What do you tell them?',
    questionImage: 'phone_call.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Tell them it is a scam — hang up and call you directly to verify', correct: true },
      { id: 'b', label: 'Tell them to send the money — you might actually need it', correct: false },
      { id: 'c', label: 'Tell them to ask the caller for more details', correct: false },
      { id: 'd', label: 'Tell them to call the police first', correct: false },
    ],
    hint: 'The fastest verification is calling the person directly on their known number.',
    explanation: 'This is a common "grandchild scam." Tell your parent to hang up and call your actual number. If you are fine, it was a scam. Simple and fast.',
  },
  {
    id: 'ds_t3_easy_2', skill: 'digital_safety', tier: 3, difficulty: 'easy',
    type: 'true_false', topic: 'personal_information',
    question: 'You should regularly check what information about you appears when you search your own name online.',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'What others can find about you online affects your privacy and safety.',
    explanation: 'Searching your own name shows what others can find. If sensitive information appears, you can request its removal or adjust privacy settings on platforms.',
  },
  {
    id: 'ds_t3_easy_3', skill: 'digital_safety', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'safe_browsing',
    question: 'You run a small business and want a website. A developer asks for full access to your hosting account. What should you do?',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Create a separate account with limited permissions for the developer', correct: true },
      { id: 'b', label: 'Give full access — they need it to build the site', correct: false },
      { id: 'c', label: 'Give them your main account but change the password after', correct: false },
      { id: 'd', label: 'Do not hire any developer to keep your site secure', correct: false },
    ],
    hint: 'Give access only to what is needed — not everything.',
    explanation: 'Create a separate developer account with only the permissions needed. Full access means they can modify, delete, or steal everything. Limit access to limit risk.',
  },
  {
    id: 'ds_t3_easy_4', skill: 'digital_safety', tier: 3, difficulty: 'easy',
    type: 'tap_select', topic: 'scams',
    question: 'Which of these is the official Safaricom M-Pesa customer care number?',
    questionImage: 'phone_call.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: '0722 000 000', correct: true },
      { id: 'b', label: '0700 000 000', correct: false },
      { id: 'c', label: '100', correct: false },
      { id: 'd', label: '0800 000 000', correct: false },
    ],
    hint: 'Know official numbers so you can verify communications.',
    explanation: 'Safaricom M-Pesa customer care is 0722 000 000. Knowing official numbers helps you verify suspicious communications and report fraud quickly.',
  },
  {
    id: 'ds_t3_easy_5', skill: 'digital_safety', tier: 3, difficulty: 'easy',
    type: 'true_false', topic: 'passwords',
    question: 'Enabling two-factor authentication on your email is one of the most effective ways to protect it.',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Two factors means even a stolen password is not enough to access the account.',
    explanation: '2FA means a hacker needs both your password AND your phone. Even if they have your password, they cannot get in without the second factor.',
  },
  {
    id: 'ds_t3_easy_6', skill: 'digital_safety', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'personal_information',
    question: 'A friend tags you in a photo on social media at a location you would prefer to keep private. What should you do?',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Ask your friend to remove the tag or delete the post', correct: true },
      { id: 'b', label: 'Accept it — it is already public', correct: false },
      { id: 'c', label: 'Delete your social media account', correct: false },
      { id: 'd', label: 'Post a comment saying the tag is wrong', correct: false },
    ],
    hint: 'You can request removal of content that compromises your privacy.',
    explanation: 'Politely ask your friend to remove the tag or post. Most people respond well to private requests. You can also remove the tag yourself on most platforms.',
  },
  {
    id: 'ds_t3_easy_7', skill: 'digital_safety', tier: 3, difficulty: 'easy',
    type: 'sequential_steps', topic: 'scams',
    question: 'Put these steps for teaching a family member about scam calls in the correct order.',
    questionImage: 'phone_call.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Explain that scammers often pretend to be banks, Safaricom, or family', order: 1 },
      { id: 's2', label: 'Show them examples of scam messages so they recognise them', order: 2 },
      { id: 's3', label: 'Teach them to hang up and call back on the official number', order: 3 },
      { id: 's4', label: 'Agree on a family code word to verify real emergencies', order: 4 },
      { id: 's5', label: 'Remind them regularly as new scam methods emerge', order: 5 },
    ],
    hint: 'Awareness → recognition → response → verification → ongoing reminders.',
    explanation: 'Teaching family: explain who scammers pretend to be → show examples → teach the hang-up-and-call-back rule → create a family code word → refresh knowledge regularly.',
  },

  // Tier 3 / Intermediate
  {
    id: 'ds_t3_int_1', skill: 'digital_safety', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'scams',
    question: 'You run a small business selling on WhatsApp. A "customer" sends you a fake M-Pesa confirmation SMS and claims they paid. How do you protect yourself?',
    questionImage: 'scam_message.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Always verify payment in your actual M-Pesa messages — not from SMS screenshots', correct: true },
      { id: 'b', label: 'The SMS looks real — release the goods', correct: false },
      { id: 'c', label: 'Call Safaricom to verify each transaction', correct: false },
      { id: 'd', label: 'Accept only half payment to reduce risk', correct: false },
    ],
    hint: 'Fake M-Pesa confirmation SMS are common business scams.',
    explanation: 'Always check your actual M-Pesa inbox or dial *334# to see received payments. Never release goods based on a screenshot — they are easily faked.',
  },
  {
    id: 'ds_t3_int_2', skill: 'digital_safety', tier: 3, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'personal_information',
    question: 'You are setting up a business social media page. Sort these into Include on Public Page or Keep Private.',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'b1', label: 'Business name', targetZone: 'public' },
      { id: 'b2', label: 'Business phone number', targetZone: 'public' },
      { id: 'b3', label: 'Your personal home address', targetZone: 'private' },
      { id: 'b4', label: 'Business M-Pesa till or Paybill number', targetZone: 'public' },
      { id: 'b5', label: 'Your personal ID number', targetZone: 'private' },
      { id: 'b6', label: 'Business operating hours', targetZone: 'public' },
    ],
    dropZones: [
      { id: 'public', label: 'Include on public page' },
      { id: 'private', label: 'Keep private' },
    ],
    hint: 'Business contact details are public. Personal identity details stay private.',
    explanation: 'Public: business name, phone, M-Pesa number, hours. Private: home address, personal ID. Separating personal and business information protects both.',
  },
  {
    id: 'ds_t3_int_3', skill: 'digital_safety', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'safe_browsing',
    question: 'Your computer at work stores customer data. A colleague wants to use it briefly. What should you do?',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Lock your screen before stepping away and have them use their own login', correct: true },
      { id: 'b', label: 'Let them use it — they are a trusted colleague', correct: false },
      { id: 'c', label: 'Stand beside them the whole time they use it', correct: false },
      { id: 'd', label: 'Log out and let them log in as a guest', correct: false },
    ],
    hint: 'Customer data is protected by law — only authorised users should access it.',
    explanation: 'Lock your screen and have colleagues use their own credentials. Sharing access to customer data violates data protection and creates accountability issues.',
  },
  {
    id: 'ds_t3_int_4', skill: 'digital_safety', tier: 3, difficulty: 'intermediate',
    type: 'true_false', topic: 'scams',
    question: 'In Kenya, the Computer Misuse and Cybercrimes Act 2018 makes cybercrime a criminal offence.',
    questionImage: 'phone_call.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Kenya has specific laws protecting citizens from cybercrime.',
    explanation: 'The Computer Misuse and Cybercrimes Act 2018 criminalises hacking, fraud, identity theft, and other cyber offences. Victims have legal recourse.',
  },
  {
    id: 'ds_t3_int_5', skill: 'digital_safety', tier: 3, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'passwords',
    question: 'To prevent unauthorised access when you are not present, you should always ___ your computer or phone screen.',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Lock', correct: true },
      { id: 'b', label: 'Switch off', correct: false },
      { id: 'c', label: 'Cover', correct: false },
    ],
    hint: 'A locked screen requires authentication to access.',
    explanation: 'Locking your screen prevents anyone from accessing your device while you are away. Set it to lock automatically after 30 seconds or 1 minute of inactivity.',
  },
  {
    id: 'ds_t3_int_6', skill: 'digital_safety', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'scams',
    question: 'You receive an investment offer via WhatsApp: "Invest KES 1,000 today, receive KES 3,000 in 3 days — guaranteed." A friend already joined. What do you do?',
    questionImage: 'scam_message.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Do not invest — guaranteed high returns in days is a pyramid scheme or scam', correct: true },
      { id: 'b', label: 'Invest a small amount to test it first', correct: false },
      { id: 'c', label: 'Join because your friend is already in', correct: false },
      { id: 'd', label: 'Ask for proof that others have been paid', correct: false },
    ],
    hint: 'No legitimate investment guarantees 200% returns in 3 days.',
    explanation: 'This is a pyramid or Ponzi scheme. Early members may be paid from new recruits\' money to create the illusion of legitimacy. Most participants lose everything.',
  },
  {
    id: 'ds_t3_int_7', skill: 'digital_safety', tier: 3, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'personal_information',
    question: 'Your social media account was hacked. Put these recovery steps in the correct order.',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Use the platform\'s account recovery feature immediately', order: 1 },
      { id: 's2', label: 'Change your password and enable 2FA once recovered', order: 2 },
      { id: 's3', label: 'Check and revoke any third-party app access', order: 3 },
      { id: 's4', label: 'Warn your contacts that the account was compromised', order: 4 },
      { id: 's5', label: 'Review what was posted or messaged and address any damage', order: 5 },
    ],
    hint: 'Recover → secure → audit access → warn contacts → address damage.',
    explanation: 'Hacked account recovery: use official recovery → change password + 2FA → revoke suspicious app access → warn contacts → review damage done.',
  },

  // Tier 3 / Advanced
  {
    id: 'ds_t3_adv_1', skill: 'digital_safety', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'scams',
    question: 'You are helping a community group manage their finances online. How do you protect against internal fraud?',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Require two people to authorise any transaction over a set amount', correct: true },
      { id: 'b', label: 'Give the most trusted member full access to everything', correct: false },
      { id: 'c', label: 'Only use cash to avoid digital fraud', correct: false },
      { id: 'd', label: 'Check the accounts once a year', correct: false },
    ],
    hint: 'Two-person authorisation prevents any single person from misusing funds.',
    explanation: 'Requiring two signatures or authorisations for significant transactions prevents any one person from acting alone. This is standard financial governance.',
  },
  {
    id: 'ds_t3_adv_2', skill: 'digital_safety', tier: 3, difficulty: 'advanced',
    type: 'drag_drop', topic: 'safe_browsing',
    question: 'Sort these digital threats into the correct category.',
    questionImage: 'scam_message.jpg', imageLayout: 'context',
    dragItems: [
      { id: 't1', label: 'Fake M-Pesa SMS asking for PIN', targetZone: 'phishing' },
      { id: 't2', label: 'App that secretly records your keystrokes', targetZone: 'malware' },
      { id: 't3', label: 'Email pretending to be from your bank', targetZone: 'phishing' },
      { id: 't4', label: 'Virus that deletes your phone data', targetZone: 'malware' },
      { id: 't5', label: 'Investment scheme promising 100% returns', targetZone: 'scam' },
      { id: 't6', label: 'WhatsApp message claiming you won a prize', targetZone: 'scam' },
    ],
    dropZones: [
      { id: 'phishing', label: 'Phishing' },
      { id: 'malware', label: 'Malware' },
      { id: 'scam', label: 'Financial Scam' },
    ],
    hint: 'Phishing steals info. Malware damages or spies. Scams steal money directly.',
    explanation: 'Phishing: fake SMS/emails stealing credentials. Malware: software that damages or spies. Financial scams: schemes that steal money through deception.',
  },
  {
    id: 'ds_t3_adv_3', skill: 'digital_safety', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'personal_information',
    question: 'A data breach at a company exposed your email and password. You use that email and password on other sites too. What must you do immediately?',
    questionImage: 'password_screen.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Change the password on every site where you used that combination immediately', correct: true },
      { id: 'b', label: 'Only change it on the breached site', correct: false },
      { id: 'c', label: 'Wait to see if anything happens', correct: false },
      { id: 'd', label: 'Create a new email and abandon the old one', correct: false },
    ],
    hint: 'Hackers try stolen credentials on many sites — this is called "credential stuffing."',
    explanation: 'Change passwords everywhere that email-password combination was used. Hackers automatically try stolen credentials across all major sites — act within hours.',
  },
  {
    id: 'ds_t3_adv_4', skill: 'digital_safety', tier: 3, difficulty: 'advanced',
    type: 'true_false', topic: 'scams',
    question: 'If you have already sent money to a scammer, reporting it to Safaricom and police is pointless because money cannot be recovered.',
    questionImage: 'phone_call.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Immediate reporting gives a chance of recovery and helps others.',
    explanation: 'Reporting immediately to Safaricom can sometimes reverse or hold transactions. Police reports create a record that helps prosecute scammers and may lead to recovery.',
  },
  {
    id: 'ds_t3_adv_5', skill: 'digital_safety', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'safe_browsing',
    question: 'You are setting up internet for a small office. What basic security steps should you take for the WiFi router?',
    questionImage: 'public_wifi.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Change default router password, use WPA2 encryption, and hide the network name', correct: true },
      { id: 'b', label: 'Leave default settings — the internet provider set them up correctly', correct: false },
      { id: 'c', label: 'Share the WiFi password publicly so clients can connect easily', correct: false },
      { id: 'd', label: 'Only use the router for one device at a time', correct: false },
    ],
    hint: 'Default router settings are publicly known and easily exploited.',
    explanation: 'Change default passwords (known to hackers), use WPA2 encryption (strongest standard), and hide the network name (SSID) to prevent casual discovery.',
  },
  {
    id: 'ds_t3_adv_6', skill: 'digital_safety', tier: 3, difficulty: 'advanced',
    type: 'fill_blank', topic: 'personal_information',
    question: 'Under Kenya\'s Data Protection Act 2019, organisations must have your ___ before collecting or sharing your personal data.',
    questionImage: 'personal_info.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Consent', correct: true },
      { id: 'b', label: 'Money', correct: false },
      { id: 'c', label: 'Employment record', correct: false },
    ],
    hint: 'The law requires permission before using your data.',
    explanation: 'Kenya\'s Data Protection Act 2019 requires organisations to obtain your informed consent before collecting, processing, or sharing your personal data. You have the right to know and agree.',
  },
  {
    id: 'ds_t3_adv_7', skill: 'digital_safety', tier: 3, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'scams',
    question: 'Put these steps for creating a digital safety policy for a small community group in the correct order.',
    questionImage: 'phone_call.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Identify what digital tools and data the group uses', order: 1 },
      { id: 's2', label: 'Decide who can access which information and accounts', order: 2 },
      { id: 's3', label: 'Set password requirements and change schedules', order: 3 },
      { id: 's4', label: 'Create a procedure for reporting suspected scams or breaches', order: 4 },
      { id: 's5', label: 'Train all members and review the policy annually', order: 5 },
    ],
    hint: 'Identify → access control → passwords → incident response → training.',
    explanation: 'Digital safety policy: know your tools → set access controls → manage passwords → create incident response → train everyone. Annual review keeps it current.',
  },
]
