// taskData_financial.ts
// Financial Planning — 63 tasks
// 3 Tiers × 3 Difficulties × 7 Tasks = 63

export type TaskFinancial = {
  id: string
  skill: string
  tier: 1 | 2 | 3
  difficulty: 'easy' | 'intermediate' | 'advanced'
  type: 'tap_select' | 'scenario_choice' | 'true_false' | 'fill_blank' | 'sequential_steps' | 'drag_drop'
  topic: string
  question: string
  context?: string
  options?: { id: string; label: string; correct: boolean; image?: string }[]
  steps?: { id: string; label: string; order: number }[]
  dragItems?: { id: string; label: string; targetZone: string }[]
  dropZones?: { id: string; label: string }[]
  hint: string
  explanation: string
  questionImage?: string
  imageLayout?: 'context' | 'options'
}

export const FINANCIAL_PLANNING_TASKS: TaskFinancial[] = [

  // =========================================================================
  // TIER 1 — FOUNDATION
  // =========================================================================

  // Tier 1 / Easy
  {
    id: 'fp_t1_easy_1', skill: 'financial_planning', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'income_expenses',
    question: 'What is income?',
    questionImage: 'income_money.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Money you receive from work or other sources', correct: true },
      { id: 'b', label: 'Money you spend on things', correct: false },
      { id: 'c', label: 'Money you borrow from someone', correct: false },
      { id: 'd', label: 'Money you lose', correct: false },
    ],
    hint: 'Income is money coming IN to you.',
    explanation: 'Income is money you receive — from a job, selling items, or any other source. It is money coming in.',
  },
  {
    id: 'fp_t1_easy_2', skill: 'financial_planning', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'income_expenses',
    question: 'An expense is money you spend.',
    questionImage: 'expenses.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Think about what happens to money when you buy something.',
    explanation: 'An expense is money going OUT — rent, food, transport, airtime. Any purchase is an expense.',
  },
  {
    id: 'fp_t1_easy_3', skill: 'financial_planning', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'saving',
    question: 'What does it mean to save money?',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Keeping some money aside instead of spending it all', correct: true },
      { id: 'b', label: 'Spending money quickly before you lose it', correct: false },
      { id: 'c', label: 'Giving money away to others', correct: false },
      { id: 'd', label: 'Borrowing money from the bank', correct: false },
    ],
    hint: 'Saving means putting money away for later.',
    explanation: 'Saving means setting aside part of your money instead of spending it all. Saved money is available for future needs.',
  },
  {
    id: 'fp_t1_easy_4', skill: 'financial_planning', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'budgeting',
    question: 'A budget helps you plan how to spend your money.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Think about what a plan does — it guides your decisions.',
    explanation: 'A budget is a plan for your money. It shows how much you have, what you need to spend on, and how much to save.',
  },
  {
    id: 'fp_t1_easy_5', skill: 'financial_planning', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'needs_wants',
    question: 'Which of these is a NEED?',
    questionImage: 'needs_wants.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Food to eat', correct: true },
      { id: 'b', label: 'A new phone', correct: false },
      { id: 'c', label: 'Designer shoes', correct: false },
      { id: 'd', label: 'A TV set', correct: false },
    ],
    hint: 'A need is something you must have to survive.',
    explanation: 'Food is a need — you cannot survive without it. A new phone, designer shoes, and a TV are wants — nice to have but not essential.',
  },
  {
    id: 'fp_t1_easy_6', skill: 'financial_planning', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'needs_wants',
    question: 'Transport to work is a need if you cannot walk there.',
    questionImage: 'transport.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'If you need it to earn income, it is a need.',
    explanation: 'Transport to work is a need if it enables you to earn income. Without it, you cannot work and cannot pay for anything else.',
  },
  {
    id: 'fp_t1_easy_7', skill: 'financial_planning', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'income_expenses',
    question: 'You earn KES 5,000 and spend KES 4,000. How much do you have left?',
    questionImage: 'income_money.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 1,000', correct: true },
      { id: 'b', label: 'KES 500', correct: false },
      { id: 'c', label: 'KES 9,000', correct: false },
      { id: 'd', label: 'KES 2,000', correct: false },
    ],
    hint: 'Income minus expenses = what is left.',
    explanation: 'KES 5,000 - KES 4,000 = KES 1,000 remaining. This leftover money can be saved or used for other needs.',
  },

  // Tier 1 / Intermediate
  {
    id: 'fp_t1_int_1', skill: 'financial_planning', tier: 1, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'needs_wants',
    question: 'Sort these expenses into Needs or Wants.',
    questionImage: 'needs_wants.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'e1', label: 'Rent — KES 3,000', targetZone: 'needs' },
      { id: 'e2', label: 'Food — KES 2,000', targetZone: 'needs' },
      { id: 'e3', label: 'New clothes for a party — KES 1,500', targetZone: 'wants' },
      { id: 'e4', label: 'School fees — KES 2,500', targetZone: 'needs' },
      { id: 'e5', label: 'Movie tickets — KES 500', targetZone: 'wants' },
      { id: 'e6', label: 'Medicine — KES 300', targetZone: 'needs' },
    ],
    dropZones: [
      { id: 'needs', label: 'Needs — must pay' },
      { id: 'wants', label: 'Wants — optional' },
    ],
    hint: 'Needs are essential for survival and function. Wants improve life but are optional.',
    explanation: 'Needs: rent, food, school fees, medicine. Wants: party clothes and movie tickets. Always cover needs before wants.',
  },
  {
    id: 'fp_t1_int_2', skill: 'financial_planning', tier: 1, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'budgeting',
    question: 'You earn KES 8,000 per month. Your needs total KES 6,000. You have KES ___ left for saving and wants.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 2,000', correct: true },
      { id: 'b', label: 'KES 1,000', correct: false },
      { id: 'c', label: 'KES 3,000', correct: false },
    ],
    hint: 'Income minus needs = remaining money.',
    explanation: 'KES 8,000 - KES 6,000 = KES 2,000 remaining for saving and wants.',
  },
  {
    id: 'fp_t1_int_3', skill: 'financial_planning', tier: 1, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'saving',
    question: 'You have KES 2,000 left after paying needs. What is the best way to use it?',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Save KES 500 first, then use the rest for wants', correct: true },
      { id: 'b', label: 'Spend it all on wants — you deserve it', correct: false },
      { id: 'c', label: 'Give it all away', correct: false },
      { id: 'd', label: 'Save it all and spend nothing on wants', correct: false },
    ],
    hint: 'Save first, then enjoy what is left.',
    explanation: 'Pay yourself first by saving before spending on wants. Even a small amount saved consistently grows over time.',
  },
  {
    id: 'fp_t1_int_4', skill: 'financial_planning', tier: 1, difficulty: 'intermediate',
    type: 'true_false', topic: 'budgeting',
    question: 'If your expenses are more than your income, you are living beyond your means.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Think about what happens when you spend more than you earn.',
    explanation: 'Spending more than you earn means you go into debt. You must either reduce expenses or increase income to balance your budget.',
  },
  {
    id: 'fp_t1_int_5', skill: 'financial_planning', tier: 1, difficulty: 'intermediate',
    type: 'tap_select', topic: 'saving',
    question: 'You want to save KES 5,000 in 5 months. How much must you save each month?',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 1,000', correct: true },
      { id: 'b', label: 'KES 500', correct: false },
      { id: 'c', label: 'KES 2,000', correct: false },
      { id: 'd', label: 'KES 1,500', correct: false },
    ],
    hint: 'Divide the total by the number of months.',
    explanation: 'KES 5,000 ÷ 5 months = KES 1,000 per month. Breaking a big goal into monthly amounts makes it achievable.',
  },
  {
    id: 'fp_t1_int_6', skill: 'financial_planning', tier: 1, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'income_expenses',
    question: 'Your income this month is KES 6,000. Your expenses are KES 6,500. What should you do?',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Find a way to reduce expenses by at least KES 500', correct: true },
      { id: 'b', label: 'Borrow KES 500 to cover the shortfall', correct: false },
      { id: 'c', label: 'Skip paying one of the bills', correct: false },
      { id: 'd', label: 'Do nothing — it will sort itself out', correct: false },
    ],
    hint: 'When expenses exceed income, reduce expenses.',
    explanation: 'You are spending KES 500 more than you earn. Review your expenses and cut a want or find a cheaper option for a need.',
  },
  {
    id: 'fp_t1_int_7', skill: 'financial_planning', tier: 1, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'budgeting',
    question: 'Put these budgeting steps in the correct order.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Write down your total monthly income', order: 1 },
      { id: 's2', label: 'List all your monthly needs and their costs', order: 2 },
      { id: 's3', label: 'Subtract needs from income', order: 3 },
      { id: 's4', label: 'Set aside savings from the remainder', order: 4 },
      { id: 's5', label: 'Use what is left for wants', order: 5 },
    ],
    hint: 'Income first, then needs, then savings, then wants.',
    explanation: 'Budget order: know income → list needs → subtract needs → save first → spend remainder on wants. This ensures essentials and savings are covered.',
  },

  // Tier 1 / Advanced
  {
    id: 'fp_t1_adv_1', skill: 'financial_planning', tier: 1, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'budgeting',
    question: 'You earn KES 10,000. Rent is KES 3,500, food KES 2,000, transport KES 1,000, airtime KES 500. How much can you save if you target 10% of income?',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 1,000 — and KES 2,000 left for wants', correct: true },
      { id: 'b', label: 'KES 500 — that is 10% of expenses', correct: false },
      { id: 'c', label: 'KES 2,000 — save everything remaining', correct: false },
      { id: 'd', label: 'Nothing — expenses use everything', correct: false },
    ],
    hint: '10% of KES 10,000 = KES 1,000. Total needs = KES 7,000. Remaining = KES 3,000.',
    explanation: 'Needs total KES 7,000. Remaining = KES 3,000. 10% of income = KES 1,000 savings. KES 2,000 left for wants.',
  },
  {
    id: 'fp_t1_adv_2', skill: 'financial_planning', tier: 1, difficulty: 'advanced',
    type: 'true_false', topic: 'saving',
    question: 'Saving even a small amount regularly is better than waiting until you have a large amount to save.',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Think about what happens when you save KES 100 every week for a year.',
    explanation: 'KES 100 per week = KES 5,200 per year. Small consistent savings grow significantly over time. Waiting for a large amount often means never saving.',
  },
  {
    id: 'fp_t1_adv_3', skill: 'financial_planning', tier: 1, difficulty: 'advanced',
    type: 'tap_select', topic: 'needs_wants',
    question: 'You want to buy new shoes (KES 2,000) but your savings goal for the month is KES 1,500 and you only have KES 2,500 left after needs. What should you do?',
    questionImage: 'needs_wants.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Save KES 1,500 first, then buy shoes with the remaining KES 1,000 — but wait until next month', correct: true },
      { id: 'b', label: 'Buy the shoes now — you can save next month', correct: false },
      { id: 'c', label: 'Skip saving this month to buy the shoes', correct: false },
      { id: 'd', label: 'Borrow KES 500 to buy the shoes and save', correct: false },
    ],
    hint: 'Save your target first. If you cannot afford the want, wait.',
    explanation: 'Save KES 1,500 first (savings goal). Remaining = KES 1,000 — not enough for KES 2,000 shoes. Save next month too and buy when you can afford it.',
  },
  {
    id: 'fp_t1_adv_4', skill: 'financial_planning', tier: 1, difficulty: 'advanced',
    type: 'fill_blank', topic: 'income_expenses',
    question: 'Income KES 12,000. Needs KES 8,000. Savings KES 1,200. Wants spending = KES ___.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 2,800', correct: true },
      { id: 'b', label: 'KES 3,000', correct: false },
      { id: 'c', label: 'KES 2,000', correct: false },
    ],
    hint: '12,000 - 8,000 - 1,200 = ?',
    explanation: 'KES 12,000 - KES 8,000 needs - KES 1,200 savings = KES 2,800 available for wants.',
  },
  {
    id: 'fp_t1_adv_5', skill: 'financial_planning', tier: 1, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'saving',
    question: 'Your friend says "I will start saving when I earn more money." What is wrong with this thinking?',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'If you cannot save a little now, you will not save a lot later — the habit matters more than the amount', correct: true },
      { id: 'b', label: 'Nothing — it makes perfect sense to wait', correct: false },
      { id: 'c', label: 'They should borrow money to save instead', correct: false },
      { id: 'd', label: 'They are right — small savings are pointless', correct: false },
    ],
    hint: 'Saving is a habit, not an amount.',
    explanation: 'People who do not save when they earn little usually do not save when they earn more either. The habit of saving matters more than the amount.',
  },
  {
    id: 'fp_t1_adv_6', skill: 'financial_planning', tier: 1, difficulty: 'advanced',
    type: 'drag_drop', topic: 'budgeting',
    question: 'You earn KES 15,000. Sort these into your budget categories.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'b1', label: 'Rent KES 4,000', targetZone: 'needs' },
      { id: 'b2', label: 'Food KES 3,000', targetZone: 'needs' },
      { id: 'b3', label: 'Savings KES 1,500', targetZone: 'savings' },
      { id: 'b4', label: 'New jacket KES 2,000', targetZone: 'wants' },
      { id: 'b5', label: 'Transport KES 1,500', targetZone: 'needs' },
      { id: 'b6', label: 'Entertainment KES 1,000', targetZone: 'wants' },
    ],
    dropZones: [
      { id: 'needs', label: 'Needs' },
      { id: 'savings', label: 'Savings' },
      { id: 'wants', label: 'Wants' },
    ],
    hint: 'Rent, food, transport are needs. Savings go before wants.',
    explanation: 'Needs: rent + food + transport = KES 8,500. Savings: KES 1,500. Wants: jacket + entertainment = KES 3,000. Remaining KES 2,000 unallocated.',
  },
  {
    id: 'fp_t1_adv_7', skill: 'financial_planning', tier: 1, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'saving',
    question: 'Put these steps for reaching a savings goal in the correct order.',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Decide what you are saving for and how much you need', order: 1 },
      { id: 's2', label: 'Set a deadline for when you want to reach the goal', order: 2 },
      { id: 's3', label: 'Divide the total by the number of months', order: 3 },
      { id: 's4', label: 'Set aside that amount every month before spending on wants', order: 4 },
      { id: 's5', label: 'Track progress and adjust if needed', order: 5 },
    ],
    hint: 'Goal → deadline → monthly amount → save consistently → track.',
    explanation: 'Savings goals: know the target → set deadline → calculate monthly amount → save first → track. This turns a dream into a plan.',
  },

  // =========================================================================
  // TIER 2 — APPLICATION
  // =========================================================================

  // Tier 2 / Easy
  {
    id: 'fp_t2_easy_1', skill: 'financial_planning', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'budgeting',
    question: 'You receive your salary of KES 18,000. The first thing you should do is:',
    questionImage: 'income_money.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Pay all bills and set aside savings before spending on anything else', correct: true },
      { id: 'b', label: 'Go shopping for things you have wanted', correct: false },
      { id: 'c', label: 'Lend money to friends who ask', correct: false },
      { id: 'd', label: 'Wait and see how much is left at the end of the month', correct: false },
    ],
    hint: 'Bills and savings come before any wants.',
    explanation: 'Pay essential bills and save first — this is called paying yourself first. Spending on wants before bills leads to financial problems.',
  },
  {
    id: 'fp_t2_easy_2', skill: 'financial_planning', tier: 2, difficulty: 'easy',
    type: 'true_false', topic: 'saving',
    question: 'A savings account at a bank is safer than keeping cash at home.',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Think about what can happen to cash kept at home.',
    explanation: 'Bank savings are protected from theft, fire, and loss. Banks also pay interest — your money grows slightly over time.',
  },
  {
    id: 'fp_t2_easy_3', skill: 'financial_planning', tier: 2, difficulty: 'easy',
    type: 'fill_blank', topic: 'income_expenses',
    question: 'If your income is KES 20,000 and your total expenses are KES 17,500, your monthly surplus is KES ___.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 2,500', correct: true },
      { id: 'b', label: 'KES 3,000', correct: false },
      { id: 'c', label: 'KES 1,500', correct: false },
    ],
    hint: '20,000 - 17,500 = ?',
    explanation: 'KES 20,000 - KES 17,500 = KES 2,500 surplus. This surplus can go to savings or wants.',
  },
  {
    id: 'fp_t2_easy_4', skill: 'financial_planning', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'needs_wants',
    question: 'You have KES 3,000 left after needs. You want to buy shoes for KES 2,500 and save KES 1,000. What should you do?',
    questionImage: 'needs_wants.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Save KES 1,000 and buy cheaper shoes next month when you have more', correct: true },
      { id: 'b', label: 'Buy the shoes — saving can wait', correct: false },
      { id: 'c', label: 'Borrow KES 500 to do both', correct: false },
      { id: 'd', label: 'Skip saving and spend all KES 3,000 on shoes and extras', correct: false },
    ],
    hint: 'You cannot do both with KES 3,000 — choose savings first.',
    explanation: 'KES 1,000 savings + KES 2,500 shoes = KES 3,500 — over your budget. Save KES 1,000 now and save for shoes next month.',
  },
  {
    id: 'fp_t2_easy_5', skill: 'financial_planning', tier: 2, difficulty: 'easy',
    type: 'tap_select', topic: 'budgeting',
    question: 'Which of these is a fixed expense — one that stays the same every month?',
    questionImage: 'expenses.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Rent', correct: true },
      { id: 'b', label: 'Food', correct: false },
      { id: 'c', label: 'Entertainment', correct: false },
      { id: 'd', label: 'Clothing', correct: false },
    ],
    hint: 'Fixed expenses are the same amount every month.',
    explanation: 'Rent is fixed — you pay the same amount every month. Food, entertainment, and clothing vary month to month.',
  },
  {
    id: 'fp_t2_easy_6', skill: 'financial_planning', tier: 2, difficulty: 'easy',
    type: 'true_false', topic: 'budgeting',
    question: 'Tracking your spending helps you understand where your money goes.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'You cannot manage what you do not measure.',
    explanation: 'Tracking spending shows you patterns — where you overspend and where you can cut. Without tracking, money disappears without knowing why.',
  },
  {
    id: 'fp_t2_easy_7', skill: 'financial_planning', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'saving',
    question: 'Your phone breaks and you have no savings. You need KES 5,000 for a replacement. What is the consequence of not having savings?',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'You must borrow money or go without — having savings would have prevented this', correct: true },
      { id: 'b', label: 'Nothing — you can always get a new phone on credit', correct: false },
      { id: 'c', label: 'You ask friends for help — that is what friends are for', correct: false },
      { id: 'd', label: 'It does not matter — phones are not important', correct: false },
    ],
    hint: 'Emergency savings exist precisely for unexpected expenses.',
    explanation: 'Without savings, unexpected expenses force you to borrow. Debt adds stress and costs more in the long run. An emergency fund prevents this.',
  },

  // Tier 2 / Intermediate
  {
    id: 'fp_t2_int_1', skill: 'financial_planning', tier: 2, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'budgeting',
    question: 'You track your spending and find you spend KES 3,000 per month on eating out. Your budget for food is KES 1,500. What should you do?',
    questionImage: 'expenses.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Cook at home more — reduce eating out to stay within KES 1,500', correct: true },
      { id: 'b', label: 'Increase your food budget to KES 3,000', correct: false },
      { id: 'c', label: 'Stop eating out completely forever', correct: false },
      { id: 'd', label: 'Ignore it — food is important', correct: false },
    ],
    hint: 'When spending exceeds budget, find ways to reduce — not just increase the budget.',
    explanation: 'Cooking at home is much cheaper than eating out. Reduce eating out frequency rather than letting the budget grow unchecked.',
  },
  {
    id: 'fp_t2_int_2', skill: 'financial_planning', tier: 2, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'saving',
    question: 'You want to build an emergency fund of KES 15,000. You can save KES 1,500 per month. It will take ___ months.',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: '10', correct: true },
      { id: 'b', label: '8', correct: false },
      { id: 'c', label: '12', correct: false },
    ],
    hint: '15,000 ÷ 1,500 = ?',
    explanation: 'KES 15,000 ÷ KES 1,500 per month = 10 months. Setting a goal and timeline makes saving concrete and achievable.',
  },
  {
    id: 'fp_t2_int_3', skill: 'financial_planning', tier: 2, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'income_expenses',
    question: 'Sort these into Fixed Expenses or Variable Expenses.',
    questionImage: 'expenses.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'x1', label: 'Rent — KES 4,000 every month', targetZone: 'fixed' },
      { id: 'x2', label: 'Electricity bill — varies each month', targetZone: 'variable' },
      { id: 'x3', label: 'NHIF contribution — same each month', targetZone: 'fixed' },
      { id: 'x4', label: 'Food — depends on what you buy', targetZone: 'variable' },
      { id: 'x5', label: 'Loan repayment — same each month', targetZone: 'fixed' },
      { id: 'x6', label: 'Transport — varies with journeys', targetZone: 'variable' },
    ],
    dropZones: [
      { id: 'fixed', label: 'Fixed — same every month' },
      { id: 'variable', label: 'Variable — changes each month' },
    ],
    hint: 'Fixed expenses are predictable. Variable expenses change.',
    explanation: 'Fixed: rent, NHIF, loan repayment. Variable: electricity, food, transport. Knowing which is which helps you predict your monthly spending.',
  },
  {
    id: 'fp_t2_int_4', skill: 'financial_planning', tier: 2, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'needs_wants',
    question: 'You have KES 5,000 saved. An emergency costs KES 3,000. A friend asks to borrow KES 2,000. What should you do?',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Pay the emergency and politely decline the loan — your savings are for emergencies', correct: true },
      { id: 'b', label: 'Lend the money — your friend is more important than savings', correct: false },
      { id: 'c', label: 'Pay the emergency and lend the money — leaving nothing saved', correct: false },
      { id: 'd', label: 'Skip the emergency payment to help your friend', correct: false },
    ],
    hint: 'Emergency funds are for your own emergencies — protect them.',
    explanation: 'Pay your emergency (KES 3,000). Politely decline lending — your savings protect you. Lending your emergency fund leaves you vulnerable.',
  },
  {
    id: 'fp_t2_int_5', skill: 'financial_planning', tier: 2, difficulty: 'intermediate',
    type: 'true_false', topic: 'budgeting',
    question: 'The 50/30/20 rule means spending 50% on needs, 30% on wants, and 20% on savings.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'This is a well-known budgeting guideline.',
    explanation: 'The 50/30/20 rule: 50% needs, 30% wants, 20% savings. On KES 10,000: KES 5,000 needs, KES 3,000 wants, KES 2,000 savings.',
  },
  {
    id: 'fp_t2_int_6', skill: 'financial_planning', tier: 2, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'budgeting',
    question: 'Using the 50/30/20 rule on income of KES 25,000, your savings target is KES ___.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 5,000', correct: true },
      { id: 'b', label: 'KES 7,500', correct: false },
      { id: 'c', label: 'KES 2,500', correct: false },
    ],
    hint: '20% of KES 25,000 = ?',
    explanation: '20% of KES 25,000 = KES 5,000 savings. Also: KES 12,500 needs and KES 7,500 wants.',
  },
  {
    id: 'fp_t2_int_7', skill: 'financial_planning', tier: 2, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'saving',
    question: 'Put these steps for opening and using a savings account in the correct order.',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Choose a bank or SACCO with low fees', order: 1 },
      { id: 's2', label: 'Open the account with required documents', order: 2 },
      { id: 's3', label: 'Deposit your first savings amount', order: 3 },
      { id: 's4', label: 'Set a regular savings date each month', order: 4 },
      { id: 's5', label: 'Review balance and progress every 3 months', order: 5 },
    ],
    hint: 'Choose → open → deposit → schedule → review.',
    explanation: 'Savings account: choose institution → open → deposit → set schedule → review regularly. Reviewing keeps you motivated and on track.',
  },

  // Tier 2 / Advanced
  {
    id: 'fp_t2_adv_1', skill: 'financial_planning', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'budgeting',
    question: 'You have a KES 50,000 annual income. Using 50/30/20: needs KES 25,000, wants KES 15,000, savings KES 10,000. Your rent alone is KES 24,000/year. What adjustment do you need?',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Rent takes nearly all of needs budget — reduce wants or find cheaper housing', correct: true },
      { id: 'b', label: 'Everything is fine — rent fits within needs', correct: false },
      { id: 'c', label: 'Stop saving to afford rent', correct: false },
      { id: 'd', label: 'Borrow money to supplement income', correct: false },
    ],
    hint: 'Rent = KES 24,000 of KES 25,000 needs budget. Only KES 1,000 left for all other needs.',
    explanation: 'KES 24,000 rent leaves only KES 1,000 for food and transport — impossible. Either find cheaper housing or significantly reduce wants.',
  },
  {
    id: 'fp_t2_adv_2', skill: 'financial_planning', tier: 2, difficulty: 'advanced',
    type: 'fill_blank', topic: 'saving',
    question: 'You save KES 2,000 per month for 12 months. At the end of the year you have KES ___.',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 24,000', correct: true },
      { id: 'b', label: 'KES 20,000', correct: false },
      { id: 'c', label: 'KES 12,000', correct: false },
    ],
    hint: '2,000 × 12 = ?',
    explanation: 'KES 2,000 × 12 months = KES 24,000. Small consistent savings add up to a significant amount over a year.',
  },
  {
    id: 'fp_t2_adv_3', skill: 'financial_planning', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'income_expenses',
    question: 'Your expenses have increased by KES 2,000 per month but your income has not changed. What are your two options?',
    questionImage: 'expenses.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Reduce other expenses by KES 2,000 OR find a way to earn KES 2,000 more', correct: true },
      { id: 'b', label: 'Borrow KES 2,000 every month to cover it', correct: false },
      { id: 'c', label: 'Ignore it and hope the situation improves', correct: false },
      { id: 'd', label: 'Stop saving to cover the extra expenses', correct: false },
    ],
    hint: 'When costs rise, either cut elsewhere or earn more.',
    explanation: 'Two options: cut KES 2,000 from other expenses, or increase income by KES 2,000. Borrowing to cover regular expenses is unsustainable.',
  },
  {
    id: 'fp_t2_adv_4', skill: 'financial_planning', tier: 2, difficulty: 'advanced',
    type: 'drag_drop', topic: 'needs_wants',
    question: 'You have KES 8,000 after needs. Sort these into Save Now or Can Wait.',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'p1', label: 'Emergency fund contribution KES 2,000', targetZone: 'now' },
      { id: 'p2', label: 'New phone KES 5,000', targetZone: 'wait' },
      { id: 'p3', label: 'School fees due next month KES 3,000', targetZone: 'now' },
      { id: 'p4', label: 'Holiday trip KES 4,000', targetZone: 'wait' },
      { id: 'p5', label: 'NHIF annual contribution KES 1,000', targetZone: 'now' },
    ],
    dropZones: [
      { id: 'now', label: 'Save or pay now' },
      { id: 'wait', label: 'Can wait' },
    ],
    hint: 'Emergency fund, upcoming bills, and insurance come before luxuries.',
    explanation: 'Save now: emergency fund + school fees + NHIF = KES 6,000. Wait: phone and holiday. This protects you from urgent shortfalls.',
  },
  {
    id: 'fp_t2_adv_5', skill: 'financial_planning', tier: 2, difficulty: 'advanced',
    type: 'true_false', topic: 'budgeting',
    question: 'Debt is always bad and should never be used.',
    questionImage: 'expenses.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Think about when borrowing can be a useful tool.',
    explanation: 'Not all debt is bad. A business loan or school fees loan can improve your earning potential. Bad debt is borrowing for wants you cannot afford.',
  },
  {
    id: 'fp_t2_adv_6', skill: 'financial_planning', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'saving',
    question: 'A chama (savings group) meets monthly. Members contribute KES 1,000 each and one member takes the total each month. With 10 members, what does each member receive when it is their turn?',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 10,000 — all members contributions for that month', correct: true },
      { id: 'b', label: 'KES 1,000 — only their own contribution', correct: false },
      { id: 'c', label: 'KES 5,000 — half the total', correct: false },
      { id: 'd', label: 'KES 12,000 — with interest added', correct: false },
    ],
    hint: '10 members × KES 1,000 each = ?',
    explanation: '10 members × KES 1,000 = KES 10,000 per month. Each member receives KES 10,000 once during the cycle. It is a structured way to save and receive a lump sum.',
  },
  {
    id: 'fp_t2_adv_7', skill: 'financial_planning', tier: 2, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'budgeting',
    question: 'Put these steps for reviewing and adjusting a monthly budget in the correct order.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'At month end, compare actual spending to planned budget', order: 1 },
      { id: 's2', label: 'Identify categories where you overspent', order: 2 },
      { id: 's3', label: 'Understand why you overspent in those categories', order: 3 },
      { id: 's4', label: 'Adjust next month\'s budget or behaviour accordingly', order: 4 },
      { id: 's5', label: 'Celebrate progress and savings achieved', order: 5 },
    ],
    hint: 'Review → identify → understand → adjust → celebrate.',
    explanation: 'Monthly budget review: compare → find overages → understand why → adjust next month → acknowledge wins. Regular review keeps your budget realistic.',
  },

  // =========================================================================
  // TIER 3 — INDEPENDENCE
  // =========================================================================

  // Tier 3 / Easy
  {
    id: 'fp_t3_easy_1', skill: 'financial_planning', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'budgeting',
    question: 'You just got your first job earning KES 25,000 per month. What should you do first?',
    questionImage: 'income_money.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Write down all your monthly expenses and create a budget before spending anything', correct: true },
      { id: 'b', label: 'Buy everything you have been wanting', correct: false },
      { id: 'c', label: 'Lend money to family who ask', correct: false },
      { id: 'd', label: 'Wait until the end of the month to see what is left', correct: false },
    ],
    hint: 'Plan before you spend — a budget prevents regret.',
    explanation: 'Create a budget before spending your first salary. Know your expenses, set savings goals, and allocate money intentionally.',
  },
  {
    id: 'fp_t3_easy_2', skill: 'financial_planning', tier: 3, difficulty: 'easy',
    type: 'true_false', topic: 'saving',
    question: 'An emergency fund should cover 3 to 6 months of your basic expenses.',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Think about how long it might take to find a new job if you lose yours.',
    explanation: '3 to 6 months of expenses gives you time to recover from job loss, illness, or major unexpected costs without going into debt.',
  },
  {
    id: 'fp_t3_easy_3', skill: 'financial_planning', tier: 3, difficulty: 'easy',
    type: 'fill_blank', topic: 'budgeting',
    question: 'Your monthly expenses are KES 12,000. Your emergency fund target (3 months) is KES ___.',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 36,000', correct: true },
      { id: 'b', label: 'KES 24,000', correct: false },
      { id: 'c', label: 'KES 12,000', correct: false },
    ],
    hint: '12,000 × 3 = ?',
    explanation: 'KES 12,000 × 3 months = KES 36,000 emergency fund target. This protects you for 3 months if income stops.',
  },
  {
    id: 'fp_t3_easy_4', skill: 'financial_planning', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'income_expenses',
    question: 'You have a side hustle earning KES 3,000 extra per month. What is the best use of this money?',
    questionImage: 'income_money.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Direct it entirely to savings or debt repayment', correct: true },
      { id: 'b', label: 'Spend it on treats since it is extra', correct: false },
      { id: 'c', label: 'Use it to expand your lifestyle expenses', correct: false },
      { id: 'd', label: 'Lend it to friends', correct: false },
    ],
    hint: 'Extra income is an opportunity to accelerate savings or pay off debt.',
    explanation: 'Extra income should go to savings or debt first — not lifestyle inflation. This accelerates your financial goals significantly.',
  },
  {
    id: 'fp_t3_easy_5', skill: 'financial_planning', tier: 3, difficulty: 'easy',
    type: 'true_false', topic: 'needs_wants',
    question: 'Lifestyle inflation means as your income grows, your spending grows at the same rate — leaving no extra to save.',
    questionImage: 'expenses.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Think about people who earn more but never seem to save more.',
    explanation: 'Lifestyle inflation happens when every raise leads to more spending. To build wealth, keep expenses steady when income rises and save the difference.',
  },
  {
    id: 'fp_t3_easy_6', skill: 'financial_planning', tier: 3, difficulty: 'easy',
    type: 'tap_select', topic: 'saving',
    question: 'Which of these is the safest and most accessible way to save money in Kenya?',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'A bank savings account or SACCO', correct: true },
      { id: 'b', label: 'Under the mattress at home', correct: false },
      { id: 'c', label: 'Giving it to a friend to keep', correct: false },
      { id: 'd', label: 'Buying goods you plan to resell', correct: false },
    ],
    hint: 'Regulated financial institutions offer safety and accessibility.',
    explanation: 'Bank or SACCO accounts are regulated, insured, and accessible. Cash at home can be stolen, damaged, or spent impulsively.',
  },
  {
    id: 'fp_t3_easy_7', skill: 'financial_planning', tier: 3, difficulty: 'easy',
    type: 'sequential_steps', topic: 'budgeting',
    question: 'Put these steps for creating your first monthly budget in the correct order.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Calculate your total monthly income from all sources', order: 1 },
      { id: 's2', label: 'List every monthly expense — fixed and variable', order: 2 },
      { id: 's3', label: 'Categorise each expense as need, want, or saving', order: 3 },
      { id: 's4', label: 'Ensure needs and savings are covered first', order: 4 },
      { id: 's5', label: 'Allocate remaining money to wants', order: 5 },
      { id: 's6', label: 'Track actual spending against the budget each week', order: 6 },
    ],
    hint: 'Income → expenses → categorise → prioritise → allocate → track.',
    explanation: 'First budget: know income → list expenses → categorise → cover needs and savings → spend remainder on wants → track weekly.',
  },

  // Tier 3 / Intermediate
  {
    id: 'fp_t3_int_1', skill: 'financial_planning', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'saving',
    question: 'You have saved KES 50,000. A friend offers you an investment promising 50% returns in one month. What should you do?',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Decline — promises of very high returns in short time are usually scams', correct: true },
      { id: 'b', label: 'Invest all KES 50,000 — the returns sound amazing', correct: false },
      { id: 'c', label: 'Invest half and keep half safe', correct: false },
      { id: 'd', label: 'Borrow more money to invest — more investment means more returns', correct: false },
    ],
    hint: 'If it sounds too good to be true, it usually is.',
    explanation: '50% returns in one month is a red flag for fraud. Legitimate investments offer 5–15% annually. Always verify before investing your savings.',
  },
  {
    id: 'fp_t3_int_2', skill: 'financial_planning', tier: 3, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'budgeting',
    question: 'You earn KES 30,000. Sort these into a complete monthly budget using 50/30/20.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'b1', label: 'Rent KES 6,000', targetZone: 'needs' },
      { id: 'b2', label: 'Food KES 4,000', targetZone: 'needs' },
      { id: 'b3', label: 'Transport KES 2,000', targetZone: 'needs' },
      { id: 'b4', label: 'Savings KES 6,000', targetZone: 'savings' },
      { id: 'b5', label: 'Entertainment KES 3,000', targetZone: 'wants' },
      { id: 'b6', label: 'New clothes KES 2,000', targetZone: 'wants' },
    ],
    dropZones: [
      { id: 'needs', label: 'Needs (50% = KES 15,000)' },
      { id: 'savings', label: 'Savings (20% = KES 6,000)' },
      { id: 'wants', label: 'Wants (30% = KES 9,000)' },
    ],
    hint: 'Needs 50% = KES 15,000. Savings 20% = KES 6,000. Wants 30% = KES 9,000.',
    explanation: 'Needs: rent + food + transport = KES 12,000 (under KES 15,000 limit). Savings: KES 6,000. Wants: entertainment + clothes = KES 5,000 (under KES 9,000 limit).',
  },
  {
    id: 'fp_t3_int_3', skill: 'financial_planning', tier: 3, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'income_expenses',
    question: 'You have a loan of KES 30,000 at 10% annual interest. The interest you pay in one year is KES ___.',
    questionImage: 'expenses.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 3,000', correct: true },
      { id: 'b', label: 'KES 300', correct: false },
      { id: 'c', label: 'KES 30,000', correct: false },
    ],
    hint: '10% of KES 30,000 = ?',
    explanation: '10% of KES 30,000 = KES 3,000 interest per year. Understanding interest helps you evaluate whether a loan is worth taking.',
  },
  {
    id: 'fp_t3_int_4', skill: 'financial_planning', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'needs_wants',
    question: 'You want to buy a motorcycle for KES 80,000 to use as a boda boda. You have KES 30,000 saved. What is the most financially sound approach?',
    questionImage: 'income_money.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Save for 3 more months to reach KES 50,000, then take a smaller loan for the rest', correct: true },
      { id: 'b', label: 'Take a loan for the full KES 80,000 now', correct: false },
      { id: 'c', label: 'Buy a cheaper motorcycle that does not work well', correct: false },
      { id: 'd', label: 'Abandon the idea — KES 80,000 is too much', correct: false },
    ],
    hint: 'A larger down payment means a smaller loan and less interest.',
    explanation: 'Saving more before borrowing reduces the loan amount and interest paid. A KES 50,000 deposit means only a KES 30,000 loan — saving significant interest.',
  },
  {
    id: 'fp_t3_int_5', skill: 'financial_planning', tier: 3, difficulty: 'intermediate',
    type: 'true_false', topic: 'budgeting',
    question: 'NHIF and NSSF contributions are investments in your future health and retirement.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'NHIF covers medical costs. NSSF is a retirement fund.',
    explanation: 'NHIF (health insurance) and NSSF (pension) are long-term financial protection. They reduce future costs for healthcare and provide income after retirement.',
  },
  {
    id: 'fp_t3_int_6', skill: 'financial_planning', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'saving',
    question: 'You have KES 20,000 saved. Should you use it to pay off a KES 15,000 loan charging 20% interest, or keep it saved earning 5% interest?',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Pay off the loan — 20% debt cost is higher than 5% savings gain', correct: true },
      { id: 'b', label: 'Keep saving — savings are always better', correct: false },
      { id: 'c', label: 'Do both equally', correct: false },
      { id: 'd', label: 'Take another loan to invest', correct: false },
    ],
    hint: 'Compare the interest rate you pay on debt vs what you earn on savings.',
    explanation: 'Paying 20% interest costs more than earning 5% savings gain. Pay off high-interest debt first — it is like getting a guaranteed 20% return.',
  },
  {
    id: 'fp_t3_int_7', skill: 'financial_planning', tier: 3, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'budgeting',
    question: 'Put these steps for handling a financial emergency in the correct order.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Assess the exact amount needed for the emergency', order: 1 },
      { id: 's2', label: 'Use emergency fund savings first', order: 2 },
      { id: 's3', label: 'If savings are insufficient, cut wants spending immediately', order: 3 },
      { id: 's4', label: 'If still short, consider a small low-interest loan', order: 4 },
      { id: 's5', label: 'After the emergency, rebuild the emergency fund as first priority', order: 5 },
    ],
    hint: 'Savings first → cut wants → borrow if needed → rebuild savings.',
    explanation: 'Emergency protocol: assess → use savings → cut wants → small loan if needed → rebuild savings. This minimises debt and recovers your financial buffer.',
  },

  // Tier 3 / Advanced
  {
    id: 'fp_t3_adv_1', skill: 'financial_planning', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'budgeting',
    question: 'You earn KES 40,000 but feel like you never have enough. You track spending and find KES 8,000 goes to unplanned purchases each month. What is the solution?',
    questionImage: 'expenses.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Create a specific allocation for fun money — say KES 3,000 — and stop when it is gone', correct: true },
      { id: 'b', label: 'Stop all unplanned spending permanently', correct: false },
      { id: 'c', label: 'Earn more money to cover the unplanned spending', correct: false },
      { id: 'd', label: 'Ignore it — spontaneous spending is normal', correct: false },
    ],
    hint: 'Give unplanned spending a budget — that controls it without eliminating it.',
    explanation: 'Budget a "fun money" category of KES 3,000. When it is gone, stop. This controls spending without requiring complete restriction, which is unsustainable.',
  },
  {
    id: 'fp_t3_adv_2', skill: 'financial_planning', tier: 3, difficulty: 'advanced',
    type: 'fill_blank', topic: 'saving',
    question: 'You invest KES 10,000 at 10% annual return. After one year you have KES ___.',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 11,000', correct: true },
      { id: 'b', label: 'KES 10,100', correct: false },
      { id: 'c', label: 'KES 12,000', correct: false },
    ],
    hint: '10% of KES 10,000 = KES 1,000 return.',
    explanation: 'KES 10,000 + 10% (KES 1,000) = KES 11,000 after one year. The next year, 10% is calculated on KES 11,000 — this is compound growth.',
  },
  {
    id: 'fp_t3_adv_3', skill: 'financial_planning', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'income_expenses',
    question: 'You want to increase your income. Which of these is the most sustainable long-term approach?',
    questionImage: 'income_money.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Develop a skill that increases your earning potential at work or through a side business', correct: true },
      { id: 'b', label: 'Take a second full-time job and work 16 hours a day', correct: false },
      { id: 'c', label: 'Borrow money and invest in high-risk schemes', correct: false },
      { id: 'd', label: 'Ask for a raise every month', correct: false },
    ],
    hint: 'Sustainable income growth comes from growing your value and skills.',
    explanation: 'Skills development is the most sustainable income growth strategy. A second full-time job leads to burnout. High-risk investments can lose everything.',
  },
  {
    id: 'fp_t3_adv_4', skill: 'financial_planning', tier: 3, difficulty: 'advanced',
    type: 'drag_drop', topic: 'budgeting',
    question: 'Sort these financial goals into Short Term (under 1 year), Medium Term (1–5 years), Long Term (5+ years).',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'g1', label: 'Buy new phone — KES 15,000', targetZone: 'short' },
      { id: 'g2', label: 'Build emergency fund — KES 36,000', targetZone: 'short' },
      { id: 'g3', label: 'Buy a plot of land — KES 500,000', targetZone: 'medium' },
      { id: 'g4', label: 'Start a business — KES 100,000', targetZone: 'medium' },
      { id: 'g5', label: 'Build a house — KES 2,000,000', targetZone: 'long' },
      { id: 'g6', label: 'Retirement fund', targetZone: 'long' },
    ],
    dropZones: [
      { id: 'short', label: 'Short Term (under 1 year)' },
      { id: 'medium', label: 'Medium Term (1–5 years)' },
      { id: 'long', label: 'Long Term (5+ years)' },
    ],
    hint: 'Match the goal size and timeline realistically.',
    explanation: 'Phone and emergency fund: short term. Plot and business: medium term. House and retirement: long term. Planning by timeline makes goals achievable.',
  },
  {
    id: 'fp_t3_adv_5', skill: 'financial_planning', tier: 3, difficulty: 'advanced',
    type: 'true_false', topic: 'saving',
    question: 'Diversifying savings means keeping all your money in one place for simplicity.',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Diversifying means spreading — not concentrating.',
    explanation: 'Diversifying means spreading money across different accounts or investments. If one fails, the others protect you. All in one place is concentration, not diversification.',
  },
  {
    id: 'fp_t3_adv_6', skill: 'financial_planning', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'needs_wants',
    question: 'Your parents need KES 20,000 for a medical emergency. You have KES 25,000 in savings. What is the most balanced decision?',
    questionImage: 'savings_jar.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Give KES 20,000 and immediately plan to rebuild savings — family health is a priority', correct: true },
      { id: 'b', label: 'Refuse — your savings are for you only', correct: false },
      { id: 'c', label: 'Give everything including the last KES 5,000', correct: false },
      { id: 'd', label: 'Lend it at interest to protect your savings', correct: false },
    ],
    hint: 'Family medical emergencies qualify as genuine needs — but keep a small buffer.',
    explanation: 'Give KES 20,000 — family health is urgent. Keep KES 5,000 as a buffer. Then immediately plan to rebuild savings. Charging family interest is harmful to relationships.',
  },
  {
    id: 'fp_t3_adv_7', skill: 'financial_planning', tier: 3, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'budgeting',
    question: 'Put these steps for building long-term financial security in the correct order.',
    questionImage: 'budget_plan.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Build an emergency fund of 3 to 6 months expenses', order: 1 },
      { id: 's2', label: 'Pay off all high-interest debt', order: 2 },
      { id: 's3', label: 'Start contributing to NSSF or a pension plan', order: 3 },
      { id: 's4', label: 'Build savings toward medium-term goals like land or business', order: 4 },
      { id: 's5', label: 'Invest for long-term growth and financial independence', order: 5 },
    ],
    hint: 'Emergency fund first, then debt, then retirement, then goals, then investment.',
    explanation: 'Financial security order: emergency fund → clear debt → pension → medium goals → long-term investment. Each step builds on the previous one.',
  },
]
