// taskData_mobile.ts
// Mobile Money & M-Pesa — 63 tasks
// 3 Tiers × 3 Difficulties × 7 Tasks = 63

export type TaskMobile = {
  id: string
  skill: string
  tier: 1 | 2 | 3
  difficulty: 'easy' | 'intermediate' | 'advanced'
  type: 'tap_select' | 'scenario_choice' | 'true_false' | 'fill_blank' | 'sequential_steps' | 'drag_drop'
  topic: string
  question: string
  context?: string
  options?: { id: string; label: string; correct: boolean; image?: string }[]
  steps?: { id: string; label: string; order: number }[]
  dragItems?: { id: string; label: string; targetZone: string }[]
  dropZones?: { id: string; label: string }[]
  hint: string
  explanation: string
  questionImage?: string
  imageLayout?: 'context' | 'options'
}

export const MOBILE_MONEY_TASKS: TaskMobile[] = [

  // =========================================================================
  // TIER 1 — FOUNDATION
  // =========================================================================

  // Tier 1 / Easy
  {
    id: 'mm_t1_easy_1', skill: 'mobile_money', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'mpesa_basics',
    question: 'What is M-Pesa?',
    questionImage: 'mpesa_logo.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'A mobile money service for sending and receiving money', correct: true },
      { id: 'b', label: 'A type of bank account that requires a branch visit', correct: false },
      { id: 'c', label: 'A mobile game application', correct: false },
      { id: 'd', label: 'A savings account at Equity Bank', correct: false },
    ],
    hint: 'M-Pesa lets you send money using your phone.',
    explanation: 'M-Pesa is a mobile money service by Safaricom that lets you send, receive, save, and pay for things using your phone.',
  },
  {
    id: 'mm_t1_easy_2', skill: 'mobile_money', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'mpesa_basics',
    question: 'You need a smartphone to use M-Pesa.',
    questionImage: 'mpesa_phone.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'M-Pesa works on basic phones using a SIM card menu.',
    explanation: 'M-Pesa works on any phone including basic feature phones. You access it through the Safaricom SIM toolkit menu by dialling *334#.',
  },
  {
    id: 'mm_t1_easy_3', skill: 'mobile_money', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'mpesa_basics',
    question: 'What do you dial to access M-Pesa on your phone?',
    questionImage: 'mpesa_phone.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: '*334#', correct: true },
      { id: 'b', label: '*100#', correct: false },
      { id: 'c', label: '#123#', correct: false },
      { id: 'd', label: '*999#', correct: false },
    ],
    hint: 'The M-Pesa USSD code starts with *334.',
    explanation: 'Dial *334# on your Safaricom line to access the M-Pesa menu on any phone.',
  },
  {
    id: 'mm_t1_easy_4', skill: 'mobile_money', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'mpesa_basics',
    question: 'Your M-Pesa PIN should be 4 digits.',
    questionImage: 'mpesa_pin.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'M-Pesa uses a 4-digit PIN for security.',
    explanation: 'Your M-Pesa PIN is 4 digits. Keep it secret and never share it with anyone — not even Safaricom agents.',
  },
  {
    id: 'mm_t1_easy_5', skill: 'mobile_money', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'sending_receiving',
    question: 'To send money to someone via M-Pesa, what do you need?',
    questionImage: 'mpesa_send.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Their phone number and your M-Pesa PIN', correct: true },
      { id: 'b', label: 'Their bank account number and ID', correct: false },
      { id: 'c', label: 'Their full name and home address', correct: false },
      { id: 'd', label: 'Their email address', correct: false },
    ],
    hint: 'M-Pesa sends money to phone numbers.',
    explanation: 'To send money via M-Pesa you need the recipient\'s phone number and your own M-Pesa PIN to authorise the transaction.',
  },
  {
    id: 'mm_t1_easy_6', skill: 'mobile_money', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'sending_receiving',
    question: 'When someone sends you M-Pesa money, you receive an SMS confirmation.',
    questionImage: 'mpesa_sms.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'M-Pesa always sends a message when money moves.',
    explanation: 'Every M-Pesa transaction generates an SMS confirmation. Always check your messages to confirm amounts received or sent.',
  },
  {
    id: 'mm_t1_easy_7', skill: 'mobile_money', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'mpesa_basics',
    question: 'Where can you deposit cash into your M-Pesa account?',
    questionImage: 'mpesa_agent.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'At an authorised M-Pesa agent', correct: true },
      { id: 'b', label: 'Only at Safaricom headquarters', correct: false },
      { id: 'c', label: 'At any supermarket checkout', correct: false },
      { id: 'd', label: 'You cannot deposit cash — only receive transfers', correct: false },
    ],
    hint: 'M-Pesa agents are found in shops and kiosks across Kenya.',
    explanation: 'You can deposit cash at any authorised M-Pesa agent. They are found at shops, kiosks, and Safaricom outlets across Kenya.',
  },

  // Tier 1 / Intermediate
  {
    id: 'mm_t1_int_1', skill: 'mobile_money', tier: 1, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'sending_receiving',
    question: 'Put these steps in the correct order to send money via M-Pesa.',
    questionImage: 'mpesa_send.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Dial *334# on your phone', order: 1 },
      { id: 's2', label: 'Select "Send Money"', order: 2 },
      { id: 's3', label: 'Enter the recipient\'s phone number', order: 3 },
      { id: 's4', label: 'Enter the amount to send', order: 4 },
      { id: 's5', label: 'Enter your M-Pesa PIN to confirm', order: 5 },
      { id: 's6', label: 'Check your SMS confirmation', order: 6 },
    ],
    hint: 'Dial → select → enter number → enter amount → confirm with PIN → check SMS.',
    explanation: 'Sending M-Pesa: dial *334# → Send Money → enter number → enter amount → enter PIN → verify via SMS.',
  },
  {
    id: 'mm_t1_int_2', skill: 'mobile_money', tier: 1, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'sending_receiving',
    question: 'You want to send KES 500 to your mother. After entering her number and amount, the phone asks for your PIN. You enter it and receive an SMS saying "You have sent KES 500 to 0722XXXXXX." What does this mean?',
    questionImage: 'mpesa_sms.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'The transaction was successful — your mother received KES 500', correct: true },
      { id: 'b', label: 'The transaction failed — try again', correct: false },
      { id: 'c', label: 'The money is pending and not yet received', correct: false },
      { id: 'd', label: 'You need to visit an agent to complete it', correct: false },
    ],
    hint: 'An SMS confirmation means the transaction completed.',
    explanation: 'The SMS confirms the transaction was successful. Your mother will also receive an SMS saying she received KES 500.',
  },
  {
    id: 'mm_t1_int_3', skill: 'mobile_money', tier: 1, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'withdrawing',
    question: 'To withdraw cash from M-Pesa at an agent, the agent gives you cash and your M-Pesa balance ___.',
    questionImage: 'mpesa_agent.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Decreases by the amount withdrawn plus any charges', correct: true },
      { id: 'b', label: 'Stays the same — it is your money', correct: false },
      { id: 'c', label: 'Increases — the agent adds money', correct: false },
    ],
    hint: 'Withdrawing removes money from your M-Pesa balance.',
    explanation: 'When you withdraw, your M-Pesa balance decreases by the amount withdrawn plus any applicable transaction charges.',
  },
  {
    id: 'mm_t1_int_4', skill: 'mobile_money', tier: 1, difficulty: 'intermediate',
    type: 'true_false', topic: 'mpesa_basics',
    question: 'M-Pesa charges a fee for sending money to other people.',
    questionImage: 'mpesa_charges.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Most M-Pesa transactions have small charges.',
    explanation: 'M-Pesa charges small fees for sending money and withdrawing. Receiving money is free. Always check the charges before sending.',
  },
  {
    id: 'mm_t1_int_5', skill: 'mobile_money', tier: 1, difficulty: 'intermediate',
    type: 'tap_select', topic: 'mpesa_basics',
    question: 'How do you check your M-Pesa balance?',
    questionImage: 'mpesa_phone.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Dial *334# and select "My Account" then "Balance"', correct: true },
      { id: 'b', label: 'Call Safaricom customer care', correct: false },
      { id: 'c', label: 'Visit the nearest Safaricom shop', correct: false },
      { id: 'd', label: 'Wait for a monthly statement', correct: false },
    ],
    hint: 'Balance check is done through the M-Pesa menu.',
    explanation: 'Dial *334# → My Account → Balance. You will be asked for your PIN. Your balance will be shown on screen.',
  },
  {
    id: 'mm_t1_int_6', skill: 'mobile_money', tier: 1, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'sending_receiving',
    question: 'You entered the wrong phone number and sent KES 1,000 to a stranger. What should you do?',
    questionImage: 'mpesa_send.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Call Safaricom immediately on 0722000000 to report and attempt reversal', correct: true },
      { id: 'b', label: 'Nothing — the money is gone', correct: false },
      { id: 'c', label: 'Send another KES 1,000 to the correct person', correct: false },
      { id: 'd', label: 'Wait for the stranger to send it back', correct: false },
    ],
    hint: 'Safaricom can sometimes reverse wrong transactions if reported quickly.',
    explanation: 'Call Safaricom immediately on 0722000000. Quick reporting gives the best chance of reversal. They can contact the recipient and request the money back.',
  },
  {
    id: 'mm_t1_int_7', skill: 'mobile_money', tier: 1, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'mpesa_basics',
    question: 'Sort these M-Pesa transactions into Free or Has a Charge.',
    questionImage: 'mpesa_charges.jpg', imageLayout: 'context',
    dragItems: [
      { id: 't1', label: 'Receiving money from someone', targetZone: 'free' },
      { id: 't2', label: 'Sending money to another person', targetZone: 'charge' },
      { id: 't3', label: 'Withdrawing cash at an agent', targetZone: 'charge' },
      { id: 't4', label: 'Checking your balance', targetZone: 'free' },
      { id: 't5', label: 'Depositing cash at an agent', targetZone: 'free' },
      { id: 't6', label: 'Paying a Paybill number', targetZone: 'charge' },
    ],
    dropZones: [
      { id: 'free', label: 'Free' },
      { id: 'charge', label: 'Has a charge' },
    ],
    hint: 'Receiving and depositing are free. Sending, withdrawing, and paying have charges.',
    explanation: 'Free: receiving money, checking balance, depositing cash. Charged: sending money, withdrawing cash, paying Paybill.',
  },

  // Tier 1 / Advanced
  {
    id: 'mm_t1_adv_1', skill: 'mobile_money', tier: 1, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'paybill_buygoods',
    question: 'You want to pay your electricity bill via M-Pesa. The KPLC Paybill number is 888880. What details do you need?',
    questionImage: 'mpesa_paybill.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Paybill number 888880, your meter number as account number, and amount', correct: true },
      { id: 'b', label: 'Just the amount — M-Pesa knows your meter', correct: false },
      { id: 'c', label: 'Your ID number and meter number', correct: false },
      { id: 'd', label: 'The KPLC office address and amount', correct: false },
    ],
    hint: 'Paybill requires: business number, account number, and amount.',
    explanation: 'For Paybill: enter the business number (888880), your account number (meter number), and the amount. This directs payment to your specific account.',
  },
  {
    id: 'mm_t1_adv_2', skill: 'mobile_money', tier: 1, difficulty: 'advanced',
    type: 'true_false', topic: 'paybill_buygoods',
    question: 'Buy Goods (Till Number) and Paybill are the same thing.',
    questionImage: 'mpesa_paybill.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Till numbers are for shops. Paybill is for utilities and larger organisations.',
    explanation: 'Buy Goods uses a Till Number for retail purchases. Paybill uses a Business Number plus Account Number for utilities, school fees, and organisations.',
  },
  {
    id: 'mm_t1_adv_3', skill: 'mobile_money', tier: 1, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'paybill_buygoods',
    question: 'Put these steps in the correct order to pay school fees via Paybill.',
    questionImage: 'mpesa_paybill.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Dial *334# and select "Lipa na M-Pesa"', order: 1 },
      { id: 's2', label: 'Select "Pay Bill"', order: 2 },
      { id: 's3', label: 'Enter the school\'s Paybill business number', order: 3 },
      { id: 's4', label: 'Enter your child\'s admission number as account number', order: 4 },
      { id: 's5', label: 'Enter the amount', order: 5 },
      { id: 's6', label: 'Enter your PIN and confirm', order: 6 },
    ],
    hint: 'Lipa na M-Pesa → Pay Bill → business number → account number → amount → PIN.',
    explanation: 'Paybill steps: *334# → Lipa na M-Pesa → Pay Bill → business number → account number → amount → PIN.',
  },
  {
    id: 'mm_t1_adv_4', skill: 'mobile_money', tier: 1, difficulty: 'advanced',
    type: 'fill_blank', topic: 'mpesa_basics',
    question: 'If you enter the wrong PIN three times on M-Pesa, your account is ___.',
    questionImage: 'mpesa_pin.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Temporarily locked for security', correct: true },
      { id: 'b', label: 'Permanently deleted', correct: false },
      { id: 'c', label: 'Charged a penalty fee', correct: false },
    ],
    hint: 'Wrong PIN attempts trigger a security lockout.',
    explanation: 'Three wrong PIN attempts locks your M-Pesa account temporarily. Call Safaricom on 0722000000 to unlock it.',
  },
  {
    id: 'mm_t1_adv_5', skill: 'mobile_money', tier: 1, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'sending_receiving',
    question: 'An agent asks you to give them your PIN so they can help you deposit money. What should you do?',
    questionImage: 'mpesa_agent.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Refuse — agents never need your PIN to process a deposit', correct: true },
      { id: 'b', label: 'Give them the PIN — they are a trusted agent', correct: false },
      { id: 'c', label: 'Give them half your PIN', correct: false },
      { id: 'd', label: 'Only give the PIN if they show their agent badge', correct: false },
    ],
    hint: 'You enter your own PIN — no one else should ever know it.',
    explanation: 'Agents never need your PIN. For deposits, the agent initiates and you enter your own PIN privately. Anyone asking for your PIN is attempting fraud.',
  },
  {
    id: 'mm_t1_adv_6', skill: 'mobile_money', tier: 1, difficulty: 'advanced',
    type: 'tap_select', topic: 'mpesa_basics',
    question: 'What is the M-Pesa statement and how do you access it?',
    questionImage: 'mpesa_statement.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'A record of all your transactions — access via *334# → My Account → Statement', correct: true },
      { id: 'b', label: 'A monthly bill sent to your home address', correct: false },
      { id: 'c', label: 'Only available at Safaricom shops', correct: false },
      { id: 'd', label: 'A document showing your bank balance', correct: false },
    ],
    hint: 'Your M-Pesa statement shows all transactions — accessible from the menu.',
    explanation: 'Your M-Pesa mini statement shows recent transactions. Access via *334# → My Account → Statement. Full statements can be requested from Safaricom.',
  },
  {
    id: 'mm_t1_adv_7', skill: 'mobile_money', tier: 1, difficulty: 'advanced',
    type: 'true_false', topic: 'paybill_buygoods',
    question: 'You can use M-Pesa to pay for items at a shop using the Till Number without needing cash.',
    questionImage: 'mpesa_paybill.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Buy Goods lets you pay directly from M-Pesa to a shop.',
    explanation: 'Buy Goods (Till Number) lets you pay directly from M-Pesa to shops, supermarkets, and businesses without using cash.',
  },

  // =========================================================================
  // TIER 2 — APPLICATION
  // =========================================================================

  // Tier 2 / Easy
  {
    id: 'mm_t2_easy_1', skill: 'mobile_money', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'sending_receiving',
    question: 'You need to send KES 2,000 to your sister. Your M-Pesa balance is KES 1,800. What should you do?',
    questionImage: 'mpesa_send.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Deposit at least KES 200 at an agent first, then send', correct: true },
      { id: 'b', label: 'Try sending anyway — it might work', correct: false },
      { id: 'c', label: 'Ask your sister to wait indefinitely', correct: false },
      { id: 'd', label: 'Send KES 1,800 and explain the shortfall', correct: false },
    ],
    hint: 'You cannot send more than your current balance.',
    explanation: 'You need KES 2,000 but have KES 1,800. Deposit KES 200 or more at an agent to top up, then send the full amount.',
  },
  {
    id: 'mm_t2_easy_2', skill: 'mobile_money', tier: 2, difficulty: 'easy',
    type: 'fill_blank', topic: 'sending_receiving',
    question: 'You send KES 500 and the charge is KES 11. Your M-Pesa balance decreases by KES ___.',
    questionImage: 'mpesa_charges.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 511', correct: true },
      { id: 'b', label: 'KES 500', correct: false },
      { id: 'c', label: 'KES 489', correct: false },
    ],
    hint: 'Total deducted = amount sent + transaction charge.',
    explanation: 'KES 500 sent + KES 11 charge = KES 511 total deducted from your balance. Always factor in charges when planning transactions.',
  },
  {
    id: 'mm_t2_easy_3', skill: 'mobile_money', tier: 2, difficulty: 'easy',
    type: 'true_false', topic: 'mpesa_basics',
    question: 'M-Pesa transactions are instant — the recipient gets money immediately.',
    questionImage: 'mpesa_sms.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'M-Pesa is a real-time payment system.',
    explanation: 'M-Pesa transactions are processed instantly. The recipient receives the money and an SMS confirmation within seconds.',
  },
  {
    id: 'mm_t2_easy_4', skill: 'mobile_money', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'withdrawing',
    question: 'You want to withdraw KES 1,000 at an agent. The agent says their float (cash) is finished. What should you do?',
    questionImage: 'mpesa_agent.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Find another M-Pesa agent nearby', correct: true },
      { id: 'b', label: 'Leave your money with them and come back tomorrow', correct: false },
      { id: 'c', label: 'Give them your phone to keep until they have cash', correct: false },
      { id: 'd', label: 'Cancel your M-Pesa account', correct: false },
    ],
    hint: 'Agents sometimes run out of cash — find another one.',
    explanation: 'When an agent has no float, simply find another M-Pesa agent. Never leave your phone or personal items with an agent.',
  },
  {
    id: 'mm_t2_easy_5', skill: 'mobile_money', tier: 2, difficulty: 'easy',
    type: 'tap_select', topic: 'paybill_buygoods',
    question: 'What is the difference between Paybill and Buy Goods?',
    questionImage: 'mpesa_paybill.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Paybill needs a business number and account number. Buy Goods only needs a Till number.', correct: true },
      { id: 'b', label: 'They are exactly the same thing', correct: false },
      { id: 'c', label: 'Paybill is free. Buy Goods has charges.', correct: false },
      { id: 'd', label: 'Buy Goods is for big companies only', correct: false },
    ],
    hint: 'Paybill has an extra account number field.',
    explanation: 'Paybill: business number + account number (e.g. your meter or admission number). Buy Goods: just a Till number. Both deduct from your M-Pesa balance.',
  },
  {
    id: 'mm_t2_easy_6', skill: 'mobile_money', tier: 2, difficulty: 'easy',
    type: 'true_false', topic: 'mpesa_basics',
    question: 'You can link your M-Pesa to your bank account to move money between them.',
    questionImage: 'mpesa_bank.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Most Kenyan banks support M-Pesa linking.',
    explanation: 'Most Kenyan banks allow you to link M-Pesa to your account. You can then move money between M-Pesa and your bank account through the M-Pesa menu.',
  },
  {
    id: 'mm_t2_easy_7', skill: 'mobile_money', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'sending_receiving',
    question: 'You receive an SMS: "You have received KES 500 from 0700XXXXXX. New balance: KES 1,200." What is your current M-Pesa balance?',
    questionImage: 'mpesa_sms.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 1,200', correct: true },
      { id: 'b', label: 'KES 500', correct: false },
      { id: 'c', label: 'KES 700', correct: false },
      { id: 'd', label: 'KES 1,700', correct: false },
    ],
    hint: 'The SMS tells you the new balance after the transaction.',
    explanation: 'Your new balance is KES 1,200 as stated in the SMS. The previous balance was KES 700 (1,200 - 500 = 700).',
  },

  // Tier 2 / Intermediate
  {
    id: 'mm_t2_int_1', skill: 'mobile_money', tier: 2, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'paybill_buygoods',
    question: 'You pay school fees of KES 12,000 via Paybill but enter the wrong account number. What happens and what should you do?',
    questionImage: 'mpesa_paybill.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'The money may go to the wrong account — call Safaricom and the school immediately', correct: true },
      { id: 'b', label: 'Nothing — Paybill automatically corrects wrong account numbers', correct: false },
      { id: 'c', label: 'The transaction fails automatically if the account is wrong', correct: false },
      { id: 'd', label: 'Wait a week and it will resolve itself', correct: false },
    ],
    hint: 'Wrong account numbers direct money to the wrong place — act fast.',
    explanation: 'Call Safaricom and the school immediately. Quick action may allow reversal or the school can locate the misallocated payment. Always verify account numbers before confirming.',
  },
  {
    id: 'mm_t2_int_2', skill: 'mobile_money', tier: 2, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'mpesa_basics',
    question: 'The M-Pesa Fuliza service allows you to complete a transaction even when your balance is insufficient — this is essentially a ___.',
    questionImage: 'mpesa_fuliza.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Short-term loan or overdraft', correct: true },
      { id: 'b', label: 'Free top-up from Safaricom', correct: false },
      { id: 'c', label: 'Savings bonus', correct: false },
    ],
    hint: 'Fuliza lets you go below zero — you repay it later.',
    explanation: 'Fuliza is an overdraft facility. It lends you money to complete a transaction when your balance is insufficient. You repay with interest when money is deposited.',
  },
  {
    id: 'mm_t2_int_3', skill: 'mobile_money', tier: 2, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'mpesa_basics',
    question: 'Sort these M-Pesa services into the correct category.',
    questionImage: 'mpesa_phone.jpg', imageLayout: 'context',
    dragItems: [
      { id: 's1', label: 'Send Money — transfer to another person', targetZone: 'transfer' },
      { id: 's2', label: 'Lipa na M-Pesa — pay businesses', targetZone: 'payment' },
      { id: 's3', label: 'M-Shwari — save and borrow', targetZone: 'savings' },
      { id: 's4', label: 'Withdraw Cash — get cash at agent', targetZone: 'cash' },
      { id: 's5', label: 'Fuliza — overdraft facility', targetZone: 'savings' },
      { id: 's6', label: 'Pay Bill — pay utilities and schools', targetZone: 'payment' },
    ],
    dropZones: [
      { id: 'transfer', label: 'Person to Person Transfer' },
      { id: 'payment', label: 'Payments to Businesses' },
      { id: 'savings', label: 'Savings and Credit' },
      { id: 'cash', label: 'Cash Transactions' },
    ],
    hint: 'Match each service to what it primarily does.',
    explanation: 'Transfer: Send Money. Payments: Lipa na M-Pesa and Pay Bill. Savings/Credit: M-Shwari and Fuliza. Cash: Withdraw.',
  },
  {
    id: 'mm_t2_int_4', skill: 'mobile_money', tier: 2, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'withdrawing',
    question: 'You are at an agent to withdraw KES 5,000. The agent asks you to hand them your phone so they can process it. What should you do?',
    questionImage: 'mpesa_agent.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Decline — initiate the withdrawal yourself and only enter your PIN when prompted', correct: true },
      { id: 'b', label: 'Give them the phone — it is standard procedure', correct: false },
      { id: 'c', label: 'Give them the phone but cover the PIN entry', correct: false },
      { id: 'd', label: 'Leave and find a different agent', correct: false },
    ],
    hint: 'You should always control your own phone during M-Pesa transactions.',
    explanation: 'Never hand your phone to an agent. You initiate the withdrawal yourself and enter your PIN privately. Agents only verify their end after you confirm.',
  },
  {
    id: 'mm_t2_int_5', skill: 'mobile_money', tier: 2, difficulty: 'intermediate',
    type: 'true_false', topic: 'mpesa_basics',
    question: 'M-Shwari is a savings and loan account accessible through M-Pesa.',
    questionImage: 'mpesa_bank.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'M-Shwari is built into the M-Pesa ecosystem.',
    explanation: 'M-Shwari is a mobile savings and loan account by NCBA Bank, accessible through M-Pesa. You can save money and take small loans directly from your phone.',
  },
  {
    id: 'mm_t2_int_6', skill: 'mobile_money', tier: 2, difficulty: 'intermediate',
    type: 'tap_select', topic: 'sending_receiving',
    question: 'You want to send money to someone who does not have M-Pesa. What happens?',
    questionImage: 'mpesa_send.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'They receive an SMS with a code to withdraw cash at any agent without M-Pesa', correct: true },
      { id: 'b', label: 'The transaction fails — they must have M-Pesa first', correct: false },
      { id: 'c', label: 'The money returns to your account automatically', correct: false },
      { id: 'd', label: 'They must register for M-Pesa before receiving', correct: false },
    ],
    hint: 'M-Pesa allows sending to non-registered users.',
    explanation: 'Non-registered recipients get an SMS with a withdrawal code. They can collect the cash at any M-Pesa agent within a set timeframe without needing their own M-Pesa.',
  },
  {
    id: 'mm_t2_int_7', skill: 'mobile_money', tier: 2, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'withdrawing',
    question: 'Put these steps in the correct order for withdrawing cash from an M-Pesa agent.',
    questionImage: 'mpesa_agent.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Tell the agent the amount you want to withdraw', order: 1 },
      { id: 's2', label: 'The agent sends you an M-Pesa prompt on your phone', order: 2 },
      { id: 's3', label: 'Enter your M-Pesa PIN on your own phone', order: 3 },
      { id: 's4', label: 'You receive an SMS confirming the withdrawal', order: 4 },
      { id: 's5', label: 'Collect your cash from the agent and count it', order: 5 },
    ],
    hint: 'Tell agent → receive prompt → enter PIN → get SMS → collect and count cash.',
    explanation: 'Withdrawal: tell agent amount → agent sends prompt → you enter PIN on your phone → SMS confirms → collect and count cash before leaving.',
  },

  // Tier 2 / Advanced
  {
    id: 'mm_t2_adv_1', skill: 'mobile_money', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'mpesa_basics',
    question: 'You run a small shop and want to accept M-Pesa payments from customers without giving them your personal number. What should you set up?',
    questionImage: 'mpesa_paybill.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'A Buy Goods Till Number — keeps business and personal separate', correct: true },
      { id: 'b', label: 'Use your personal M-Pesa number for everything', correct: false },
      { id: 'c', label: 'Ask customers to use Paybill instead', correct: false },
      { id: 'd', label: 'Only accept cash to avoid complications', correct: false },
    ],
    hint: 'Till numbers are designed for business payments.',
    explanation: 'A Buy Goods Till Number separates business from personal money, looks more professional, and makes accounting easier. Apply through Safaricom.',
  },
  {
    id: 'mm_t2_adv_2', skill: 'mobile_money', tier: 2, difficulty: 'advanced',
    type: 'fill_blank', topic: 'mpesa_basics',
    question: 'Fuliza charges interest daily on the borrowed amount. If you borrow KES 1,000 and the daily charge is 1%, after 5 days you owe approximately KES ___.',
    questionImage: 'mpesa_fuliza.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'KES 1,050', correct: true },
      { id: 'b', label: 'KES 1,000', correct: false },
      { id: 'c', label: 'KES 1,100', correct: false },
    ],
    hint: '1% of KES 1,000 = KES 10 per day. 5 days = KES 50.',
    explanation: 'KES 1,000 × 1% × 5 days = KES 50 interest. Total owed = KES 1,050. Repay Fuliza quickly to minimise charges.',
  },
  {
    id: 'mm_t2_adv_3', skill: 'mobile_money', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'paybill_buygoods',
    question: 'A customer claims they paid your Till Number KES 3,000 but you have not received it. They show you an SMS. What should you do?',
    questionImage: 'mpesa_sms.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Check your own M-Pesa statement to verify — do not rely on their SMS screenshot', correct: true },
      { id: 'b', label: 'Accept their SMS as proof and give the goods', correct: false },
      { id: 'c', label: 'Call Safaricom immediately without checking', correct: false },
      { id: 'd', label: 'Assume it is pending and give the goods anyway', correct: false },
    ],
    hint: 'SMS screenshots can be faked — always verify in your own statement.',
    explanation: 'Check your own M-Pesa statement or dial *334# to verify receipt. Fake confirmation SMS are a common business scam — never release goods without verification.',
  },
  {
    id: 'mm_t2_adv_4', skill: 'mobile_money', tier: 2, difficulty: 'advanced',
    type: 'true_false', topic: 'mpesa_basics',
    question: 'Using Fuliza regularly for everyday expenses is a healthy financial habit.',
    questionImage: 'mpesa_fuliza.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Fuliza is an overdraft — it charges daily interest.',
    explanation: 'Regular Fuliza use means you are consistently spending more than you earn. The daily interest adds up significantly. Use it only for genuine emergencies.',
  },
  {
    id: 'mm_t2_adv_5', skill: 'mobile_money', tier: 2, difficulty: 'advanced',
    type: 'drag_drop', topic: 'mpesa_basics',
    question: 'Sort these M-Pesa safety practices into Do Always or Never Do.',
    questionImage: 'mpesa_pin.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'p1', label: 'Check SMS confirmation after every transaction', targetZone: 'always' },
      { id: 'p2', label: 'Share your PIN with a trusted family member', targetZone: 'never' },
      { id: 'p3', label: 'Verify recipient number before confirming send', targetZone: 'always' },
      { id: 'p4', label: 'Use the same PIN as your phone lock screen', targetZone: 'never' },
      { id: 'p5', label: 'Report suspicious transactions immediately', targetZone: 'always' },
      { id: 'p6', label: 'Enter PIN while someone is watching over your shoulder', targetZone: 'never' },
    ],
    dropZones: [
      { id: 'always', label: 'Do Always' },
      { id: 'never', label: 'Never Do' },
    ],
    hint: 'Always verify and protect. Never share or expose your PIN.',
    explanation: 'Always: check SMS, verify number, report issues. Never: share PIN, reuse PIN, enter PIN while observed.',
  },
  {
    id: 'mm_t2_adv_6', skill: 'mobile_money', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'sending_receiving',
    question: 'You receive KES 50,000 from a stranger with an SMS saying "Wrong number, please send back." What should you do?',
    questionImage: 'mpesa_sms.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Call Safaricom to verify and let them handle the reversal — do not send directly', correct: true },
      { id: 'b', label: 'Send the money back immediately — they made an honest mistake', correct: false },
      { id: 'c', label: 'Keep the money — you received it legitimately', correct: false },
      { id: 'd', label: 'Send back KES 45,000 and keep KES 5,000 as a handling fee', correct: false },
    ],
    hint: 'This is sometimes a scam — always involve Safaricom in reversals.',
    explanation: 'Some scammers send money and ask for it back, then reverse the original payment — leaving you out of pocket. Call Safaricom to handle the reversal properly.',
  },
  {
    id: 'mm_t2_adv_7', skill: 'mobile_money', tier: 2, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'mpesa_basics',
    question: 'Put these steps in the correct order to link your bank account to M-Pesa.',
    questionImage: 'mpesa_bank.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Dial *334# and go to My Account', order: 1 },
      { id: 's2', label: 'Select "Link Bank Account"', order: 2 },
      { id: 's3', label: 'Choose your bank from the list', order: 3 },
      { id: 's4', label: 'Enter your bank account number', order: 4 },
      { id: 's5', label: 'Confirm with your M-Pesa PIN', order: 5 },
    ],
    hint: '*334# → My Account → Link Bank → choose bank → account number → PIN.',
    explanation: 'Bank linking: *334# → My Account → Link Bank Account → select bank → enter account number → confirm with PIN.',
  },

  // =========================================================================
  // TIER 3 — INDEPENDENCE
  // =========================================================================

  // Tier 3 / Easy
  {
    id: 'mm_t3_easy_1', skill: 'mobile_money', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'mpesa_basics',
    question: 'You are helping an elderly neighbour use M-Pesa for the first time. What is the most important thing to teach them first?',
    questionImage: 'mpesa_pin.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'How to keep their PIN secret and never share it with anyone', correct: true },
      { id: 'b', label: 'How to use all M-Pesa services at once', correct: false },
      { id: 'c', label: 'How to check their statement', correct: false },
      { id: 'd', label: 'How to use Fuliza', correct: false },
    ],
    hint: 'PIN security is the foundation of safe M-Pesa use.',
    explanation: 'PIN security is the most critical lesson. All other M-Pesa safety depends on keeping the PIN private. Teach this before anything else.',
  },
  {
    id: 'mm_t3_easy_2', skill: 'mobile_money', tier: 3, difficulty: 'easy',
    type: 'true_false', topic: 'sending_receiving',
    question: 'You can reverse an M-Pesa transaction yourself through the app without calling Safaricom.',
    questionImage: 'mpesa_send.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'M-Pesa reversals require Safaricom involvement.',
    explanation: 'You cannot reverse M-Pesa transactions yourself. Contact Safaricom on 0722000000 immediately for any wrong transaction. They facilitate the reversal process.',
  },
  {
    id: 'mm_t3_easy_3', skill: 'mobile_money', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'paybill_buygoods',
    question: 'You run a business and notice some customers pay the wrong amount via Till Number — too little or too much. How do you manage this?',
    questionImage: 'mpesa_paybill.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Display the exact amount clearly at point of sale and always verify before releasing goods', correct: true },
      { id: 'b', label: 'Accept whatever amount they pay and adjust later', correct: false },
      { id: 'c', label: 'Stop accepting M-Pesa to avoid the problem', correct: false },
      { id: 'd', label: 'Ask customers to try again if wrong', correct: false },
    ],
    hint: 'Prevention is better than correction — display amounts clearly.',
    explanation: 'Display the exact amount clearly (on a sign or receipt) and verify payment before giving goods. Prevention reduces errors and disputes.',
  },
  {
    id: 'mm_t3_easy_4', skill: 'mobile_money', tier: 3, difficulty: 'easy',
    type: 'fill_blank', topic: 'mpesa_basics',
    question: 'To change your M-Pesa PIN, you go to *334# → My Account → ___.',
    questionImage: 'mpesa_pin.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Change PIN', correct: true },
      { id: 'b', label: 'Reset Account', correct: false },
      { id: 'c', label: 'Security Settings', correct: false },
    ],
    hint: 'The PIN change option is under My Account.',
    explanation: 'To change your M-Pesa PIN: *334# → My Account → Change PIN. You will enter your current PIN then set a new one. Change it regularly for security.',
  },
  {
    id: 'mm_t3_easy_5', skill: 'mobile_money', tier: 3, difficulty: 'easy',
    type: 'true_false', topic: 'mpesa_basics',
    question: 'M-Pesa has a maximum transaction limit — you cannot send more than KES 150,000 in a single transaction.',
    questionImage: 'mpesa_send.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'M-Pesa has both transaction and daily limits.',
    explanation: 'M-Pesa has limits: maximum KES 150,000 per transaction and KES 300,000 daily. For larger amounts, use bank transfers. Limits protect against fraud.',
  },
  {
    id: 'mm_t3_easy_6', skill: 'mobile_money', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'sending_receiving',
    question: 'Someone calls claiming to be from Safaricom and says your M-Pesa will be suspended unless you send them KES 1,000 to "verify" your account. What do you do?',
    questionImage: 'mpesa_pin.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Hang up and call Safaricom on 0722000000 to verify', correct: true },
      { id: 'b', label: 'Send the KES 1,000 — your account needs to stay active', correct: false },
      { id: 'c', label: 'Send half the amount to show goodwill', correct: false },
      { id: 'd', label: 'Give them your PIN to verify your identity', correct: false },
    ],
    hint: 'Safaricom never asks for money or PIN to verify accounts.',
    explanation: 'This is a scam. Safaricom never asks you to send money or share your PIN to verify your account. Hang up and call the official number.',
  },
  {
    id: 'mm_t3_easy_7', skill: 'mobile_money', tier: 3, difficulty: 'easy',
    type: 'sequential_steps', topic: 'mpesa_basics',
    question: 'Put these steps in the correct order to register a new M-Pesa account.',
    questionImage: 'mpesa_agent.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Visit an authorised M-Pesa agent or Safaricom shop', order: 1 },
      { id: 's2', label: 'Present your original national ID', order: 2 },
      { id: 's3', label: 'The agent registers your Safaricom number for M-Pesa', order: 3 },
      { id: 's4', label: 'You receive a confirmation SMS', order: 4 },
      { id: 's5', label: 'Dial *334# to set your PIN and activate the account', order: 5 },
    ],
    hint: 'Visit agent → show ID → agent registers → SMS → set PIN.',
    explanation: 'M-Pesa registration: visit agent → show ID → agent registers → confirmation SMS → dial *334# to set PIN. You need a valid national ID.',
  },

  // Tier 3 / Intermediate
  {
    id: 'mm_t3_int_1', skill: 'mobile_money', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'mpesa_basics',
    question: 'You manage finances for a community self-help group. Members contribute via M-Pesa monthly. How do you best manage incoming payments?',
    questionImage: 'mpesa_paybill.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Set up a group Paybill or Till Number and keep a record of each member\'s payment', correct: true },
      { id: 'b', label: 'Use your personal M-Pesa — it is easier to track', correct: false },
      { id: 'c', label: 'Accept only cash to avoid M-Pesa complications', correct: false },
      { id: 'd', label: 'Let members send to any committee member\'s number', correct: false },
    ],
    hint: 'A dedicated group account keeps funds separate and transparent.',
    explanation: 'A group Paybill or Till Number keeps group money separate from personal funds, creates a clear record, and promotes transparency and accountability.',
  },
  {
    id: 'mm_t3_int_2', skill: 'mobile_money', tier: 3, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'mpesa_basics',
    question: 'Sort these M-Pesa services by their best use case.',
    questionImage: 'mpesa_phone.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'u1', label: 'Send Money — transfer to a friend', targetZone: 'personal' },
      { id: 'u2', label: 'M-Shwari Lock Savings — save for a goal', targetZone: 'saving' },
      { id: 'u3', label: 'Paybill — pay school fees', targetZone: 'bills' },
      { id: 'u4', label: 'Buy Goods — pay at a shop', targetZone: 'shopping' },
      { id: 'u5', label: 'Fuliza — cover a short-term gap', targetZone: 'emergency' },
      { id: 'u6', label: 'Bank to M-Pesa — move money from bank', targetZone: 'personal' },
    ],
    dropZones: [
      { id: 'personal', label: 'Personal transfers' },
      { id: 'saving', label: 'Saving money' },
      { id: 'bills', label: 'Paying bills' },
      { id: 'shopping', label: 'Shopping payments' },
      { id: 'emergency', label: 'Emergency shortfall' },
    ],
    hint: 'Match each service to its primary purpose.',
    explanation: 'Send Money and Bank Transfer: personal. M-Shwari Lock: saving. Paybill: bills. Buy Goods: shopping. Fuliza: emergency shortfall only.',
  },
  {
    id: 'mm_t3_int_3', skill: 'mobile_money', tier: 3, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'mpesa_basics',
    question: 'M-Shwari Lock Savings locks your money for a fixed period and earns ___.',
    questionImage: 'mpesa_bank.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Interest on the locked amount', correct: true },
      { id: 'b', label: 'Airtime rewards', correct: false },
      { id: 'c', label: 'Nothing — it just protects the money', correct: false },
    ],
    hint: 'Locking savings earns a return for keeping money in.',
    explanation: 'M-Shwari Lock Savings earns interest on your locked amount. The longer you lock, the more interest you earn. This rewards disciplined saving.',
  },
  {
    id: 'mm_t3_int_4', skill: 'mobile_money', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'paybill_buygoods',
    question: 'You want to pay rent via M-Pesa Paybill but the landlord\'s Paybill charges you a fee. Your landlord says you should pay the full rent amount and the fee. Is this correct?',
    questionImage: 'mpesa_charges.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Yes — M-Pesa charges are typically the sender\'s responsibility unless agreed otherwise', correct: true },
      { id: 'b', label: 'No — the landlord must absorb all charges', correct: false },
      { id: 'c', label: 'No — M-Pesa Paybill is always free', correct: false },
      { id: 'd', label: 'Yes — but only if the fee is more than KES 50', correct: false },
    ],
    hint: 'Transaction fees are normally paid by the person sending.',
    explanation: 'M-Pesa transaction charges are typically paid by the sender. Unless otherwise agreed, the full rent plus any applicable charges is your responsibility.',
  },
  {
    id: 'mm_t3_int_5', skill: 'mobile_money', tier: 3, difficulty: 'intermediate',
    type: 'true_false', topic: 'mpesa_basics',
    question: 'You can use M-Pesa to pay for goods and services internationally.',
    questionImage: 'mpesa_send.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'M-Pesa has expanded to international payments.',
    explanation: 'M-Pesa supports some international transactions through partnerships. You can also send money to other African countries where M-Pesa operates.',
  },
  {
    id: 'mm_t3_int_6', skill: 'mobile_money', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'mpesa_basics',
    question: 'Your M-Pesa account has been inactive for over a year. What might happen?',
    questionImage: 'mpesa_phone.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'The account may be deactivated and the balance transferred to Safaricom', correct: true },
      { id: 'b', label: 'Nothing — your balance stays forever', correct: false },
      { id: 'c', label: 'Your balance grows with interest automatically', correct: false },
      { id: 'd', label: 'The account is permanently deleted with no recovery', correct: false },
    ],
    hint: 'Inactive accounts have consequences under M-Pesa terms.',
    explanation: 'Long-term inactive M-Pesa accounts can be deactivated. Balances may be held by Safaricom and require formal processes to reclaim. Keep your account active.',
  },
  {
    id: 'mm_t3_int_7', skill: 'mobile_money', tier: 3, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'mpesa_basics',
    question: 'Put these steps for recovering a lost or stolen M-Pesa SIM in the correct order.',
    questionImage: 'mpesa_agent.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Report SIM loss to Safaricom immediately on 0722000000', order: 1 },
      { id: 's2', label: 'Request SIM swap at a Safaricom shop with your ID', order: 2 },
      { id: 's3', label: 'Your number and M-Pesa account transfer to the new SIM', order: 3 },
      { id: 's4', label: 'Change your M-Pesa PIN immediately after recovery', order: 4 },
      { id: 's5', label: 'Check your statement for any unauthorised transactions', order: 5 },
    ],
    hint: 'Report → swap SIM → recover account → change PIN → audit transactions.',
    explanation: 'Lost SIM: call Safaricom immediately → get SIM swap with ID → account transfers to new SIM → change PIN → check for fraud.',
  },

  // Tier 3 / Advanced
  {
    id: 'mm_t3_adv_1', skill: 'mobile_money', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'mpesa_basics',
    question: 'You are setting up M-Pesa for your small business. Which combination gives you the most professional and secure setup?',
    questionImage: 'mpesa_paybill.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'A dedicated business Till Number, separate business SIM, and daily statement review', correct: true },
      { id: 'b', label: 'Your personal M-Pesa number shared with employees', correct: false },
      { id: 'c', label: 'Paybill for everything including retail purchases', correct: false },
      { id: 'd', label: 'Cash only to keep things simple', correct: false },
    ],
    hint: 'Separation, security, and monitoring are the three pillars of business M-Pesa.',
    explanation: 'A dedicated Till Number keeps business separate, a separate SIM limits exposure, and daily statement review catches fraud early. This is the most secure setup.',
  },
  {
    id: 'mm_t3_adv_2', skill: 'mobile_money', tier: 3, difficulty: 'advanced',
    type: 'drag_drop', topic: 'mpesa_basics',
    question: 'Sort these M-Pesa situations into Handle Yourself or Contact Safaricom.',
    questionImage: 'mpesa_phone.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'a1', label: 'Change your PIN', targetZone: 'self' },
      { id: 'a2', label: 'Reverse a wrong transaction', targetZone: 'safaricom' },
      { id: 'a3', label: 'Check your balance', targetZone: 'self' },
      { id: 'a4', label: 'Report fraud or scam', targetZone: 'safaricom' },
      { id: 'a5', label: 'Send money to a contact', targetZone: 'self' },
      { id: 'a6', label: 'Recover a locked account', targetZone: 'safaricom' },
    ],
    dropZones: [
      { id: 'self', label: 'Handle yourself via *334#' },
      { id: 'safaricom', label: 'Contact Safaricom on 0722000000' },
    ],
    hint: 'Routine transactions you handle yourself. Problems need Safaricom.',
    explanation: 'Self: change PIN, check balance, send money. Safaricom: reversals, fraud reports, account recovery. Knowing when to call saves time.',
  },
  {
    id: 'mm_t3_adv_3', skill: 'mobile_money', tier: 3, difficulty: 'advanced',
    type: 'fill_blank', topic: 'mpesa_basics',
    question: 'To avoid Fuliza charges accumulating, you should repay the borrowed amount within ___ to minimise costs.',
    questionImage: 'mpesa_fuliza.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: '24 hours or as soon as possible', correct: true },
      { id: 'b', label: '30 days', correct: false },
      { id: 'c', label: 'A week', correct: false },
    ],
    hint: 'Fuliza charges daily — the sooner you repay, the less you pay.',
    explanation: 'Repay Fuliza within 24 hours to minimise daily interest charges. The longer you hold the balance, the more it costs.',
  },
  {
    id: 'mm_t3_adv_4', skill: 'mobile_money', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'mpesa_basics',
    question: 'A new M-Pesa agent opens near you with unusually high withdrawal limits and low fees compared to all others. What should you be cautious about?',
    questionImage: 'mpesa_agent.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'It may be an unauthorised or fraudulent agent — verify their Safaricom authorisation first', correct: true },
      { id: 'b', label: 'It is a great deal — use them for all transactions', correct: false },
      { id: 'c', label: 'The fees are wrong — report them to Safaricom', correct: false },
      { id: 'd', label: 'Nothing — more competition is always good', correct: false },
    ],
    hint: 'Unusual offers from agents can indicate fraud.',
    explanation: 'Unauthorised agents can steal your money or clone your SIM. Verify agents by checking for the official Safaricom agent certificate displayed at their premises.',
  },
  {
    id: 'mm_t3_adv_5', skill: 'mobile_money', tier: 3, difficulty: 'advanced',
    type: 'true_false', topic: 'mpesa_basics',
    question: 'M-Pesa transaction data can be used as proof of payment in legal disputes.',
    questionImage: 'mpesa_statement.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'M-Pesa generates official transaction records.',
    explanation: 'M-Pesa statements are recognised as proof of payment. Request a certified statement from Safaricom for use in legal or business disputes.',
  },
  {
    id: 'mm_t3_adv_6', skill: 'mobile_money', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'mpesa_basics',
    question: 'You are training new employees on M-Pesa. What is the single most important security rule to emphasise?',
    questionImage: 'mpesa_pin.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Never share your PIN with anyone — not colleagues, managers, or Safaricom agents', correct: true },
      { id: 'b', label: 'Always use Fuliza for business expenses', correct: false },
      { id: 'c', label: 'Check your balance before every transaction', correct: false },
      { id: 'd', label: 'Send money only during business hours', correct: false },
    ],
    hint: 'PIN security is the foundation of all M-Pesa safety.',
    explanation: 'PIN confidentiality is the single most important rule. A shared PIN means anyone can access, send, or withdraw your money. No legitimate person ever needs your PIN.',
  },
  {
    id: 'mm_t3_adv_7', skill: 'mobile_money', tier: 3, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'mpesa_basics',
    question: 'Put these steps in the correct order for setting up M-Pesa for a community savings group.',
    questionImage: 'mpesa_paybill.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Register a group Till Number or Paybill through Safaricom', order: 1 },
      { id: 's2', label: 'Communicate the Till or Paybill number to all members', order: 2 },
      { id: 's3', label: 'Set a clear contribution schedule and amounts', order: 3 },
      { id: 's4', label: 'Designate two authorised signatories for withdrawals', order: 4 },
      { id: 's5', label: 'Review and share the M-Pesa statement with all members monthly', order: 5 },
    ],
    hint: 'Register → communicate → schedule → governance → transparency.',
    explanation: 'Group M-Pesa setup: register account → share details → set schedule → set governance (two signatories) → monthly statement review for transparency.',
  },
]
