// taskData_routine.ts
// Daily Routine — 63 tasks
// 3 Tiers × 3 Difficulties × 7 Tasks = 63

export type TaskRoutine = {
  id: string
  skill: string
  tier: 1 | 2 | 3
  difficulty: 'easy' | 'intermediate' | 'advanced'
  type: 'tap_select' | 'scenario_choice' | 'true_false' | 'fill_blank' | 'sequential_steps' | 'drag_drop'
  topic: string
  question: string
  context?: string
  options?: { id: string; label: string; correct: boolean; image?: string }[]
  steps?: { id: string; label: string; order: number }[]
  dragItems?: { id: string; label: string; targetZone: string }[]
  dropZones?: { id: string; label: string }[]
  hint: string
  explanation: string
  questionImage?: string
  imageLayout?: 'context' | 'options'
}

export const DAILY_ROUTINE_TASKS: TaskRoutine[] = [

  // =========================================================================
  // TIER 1 — FOUNDATION
  // =========================================================================

  // Tier 1 / Easy
  {
    id: 'dr_t1_easy_1', skill: 'daily_routine', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'morning_routine',
    question: 'Which of these should you do first thing in the morning?',
    questionImage: 'morning_wake.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Wake up and get out of bed', correct: true },
      { id: 'b', label: 'Eat lunch', correct: false },
      { id: 'c', label: 'Watch TV', correct: false },
      { id: 'd', label: 'Go to sleep', correct: false },
    ],
    hint: 'Think about the very first thing that happens each morning.',
    explanation: 'The first step of a morning routine is waking up and getting out of bed. Everything else follows from there.',
  },
  {
    id: 'dr_t1_easy_2', skill: 'daily_routine', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'hygiene',
    question: 'You should brush your teeth every day.',
    questionImage: 'brushing_teeth.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Think about how often dentists recommend brushing.',
    explanation: 'You should brush your teeth at least twice a day — morning and night. It keeps teeth healthy and breath fresh.',
  },
  {
    id: 'dr_t1_easy_3', skill: 'daily_routine', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'meal_times',
    question: 'Which meal do you eat in the morning?',
    questionImage: 'breakfast.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Breakfast', correct: true },
      { id: 'b', label: 'Lunch', correct: false },
      { id: 'c', label: 'Dinner', correct: false },
      { id: 'd', label: 'Supper', correct: false },
    ],
    hint: 'The first meal of the day happens in the morning.',
    explanation: 'Breakfast is the morning meal. Lunch is midday. Dinner or supper is in the evening.',
  },
  {
    id: 'dr_t1_easy_4', skill: 'daily_routine', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'hygiene',
    question: 'It is okay to wear the same clothes for a whole week without washing them.',
    questionImage: 'clean_clothes.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Think about what happens to clothes after you wear them.',
    explanation: 'Clothes get dirty and sweaty after wearing. They should be washed regularly to stay clean and hygienic.',
  },
  {
    id: 'dr_t1_easy_5', skill: 'daily_routine', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'bedtime_routine',
    question: 'Which of these is a good thing to do before bed?',
    questionImage: 'bedtime.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Brush teeth and wash face', correct: true },
      { id: 'b', label: 'Eat a very large meal', correct: false },
      { id: 'c', label: 'Play loud music', correct: false },
      { id: 'd', label: 'Drink lots of sugary drinks', correct: false },
    ],
    hint: 'Think about what helps your body get ready for sleep.',
    explanation: 'Brushing teeth and washing face before bed keeps you clean and signals to your body that it is time to sleep.',
  },
  {
    id: 'dr_t1_easy_6', skill: 'daily_routine', tier: 1, difficulty: 'easy',
    type: 'true_false', topic: 'morning_routine',
    question: 'Eating breakfast gives you energy for the morning.',
    questionImage: 'breakfast.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Think about how you feel when you skip breakfast.',
    explanation: 'Breakfast provides energy after a night of sleep. Skipping it can make you feel tired and unable to concentrate.',
  },
  {
    id: 'dr_t1_easy_7', skill: 'daily_routine', tier: 1, difficulty: 'easy',
    type: 'tap_select', topic: 'bedtime_routine',
    question: 'What time is best for going to sleep for a school-age person?',
    questionImage: 'bedtime.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Between 8 PM and 10 PM', correct: true },
      { id: 'b', label: 'Midnight or later', correct: false },
      { id: 'c', label: 'After watching TV until you fall asleep', correct: false },
      { id: 'd', label: 'Whenever you feel like it', correct: false },
    ],
    hint: 'Young people need 8 to 10 hours of sleep per night.',
    explanation: 'Going to bed between 8 PM and 10 PM ensures enough sleep to wake refreshed for school or work.',
  },

  // Tier 1 / Intermediate
  {
    id: 'dr_t1_int_1', skill: 'daily_routine', tier: 1, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'morning_routine',
    question: 'Put these morning routine steps in the correct order.',
    questionImage: 'morning_routine.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Wake up and get out of bed', order: 1 },
      { id: 's2', label: 'Use the toilet and wash hands', order: 2 },
      { id: 's3', label: 'Brush teeth and wash face', order: 3 },
      { id: 's4', label: 'Get dressed', order: 4 },
      { id: 's5', label: 'Eat breakfast', order: 5 },
      { id: 's6', label: 'Leave for school or work', order: 6 },
    ],
    hint: 'Start with getting up, then hygiene, then food, then leave.',
    explanation: 'A good morning routine: wake → toilet → hygiene → dress → eat → leave. This order keeps you clean and fed before going out.',
  },
  {
    id: 'dr_t1_int_2', skill: 'daily_routine', tier: 1, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'meal_times',
    question: 'Sort these foods into the correct meal time.',
    questionImage: 'meal_times.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'f1', label: 'Uji and mandazi', targetZone: 'breakfast' },
      { id: 'f2', label: 'Rice and beans', targetZone: 'lunch' },
      { id: 'f3', label: 'Ugali and sukuma wiki', targetZone: 'dinner' },
      { id: 'f4', label: 'Tea and bread', targetZone: 'breakfast' },
      { id: 'f5', label: 'Chapati and stew', targetZone: 'dinner' },
      { id: 'f6', label: 'Githeri', targetZone: 'lunch' },
    ],
    dropZones: [
      { id: 'breakfast', label: 'Breakfast' },
      { id: 'lunch', label: 'Lunch' },
      { id: 'dinner', label: 'Dinner' },
    ],
    hint: 'Light foods for breakfast, heavier meals for lunch and dinner.',
    explanation: 'Breakfast is usually lighter — uji, tea, bread. Lunch and dinner are heavier meals like rice, ugali, or chapati.',
  },
  {
    id: 'dr_t1_int_3', skill: 'daily_routine', tier: 1, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'hygiene',
    question: 'You have been playing outside and your hands are dirty. Before eating lunch, what should you do?',
    questionImage: 'handwashing.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Wash hands with soap and water', correct: true },
      { id: 'b', label: 'Wipe hands on your clothes', correct: false },
      { id: 'c', label: 'Eat quickly before anyone notices', correct: false },
      { id: 'd', label: 'Use someone else\'s hands to touch the food', correct: false },
    ],
    hint: 'Clean hands prevent germs from getting into your food.',
    explanation: 'Always wash hands with soap and water before eating. Dirty hands carry germs that cause illness.',
  },
  {
    id: 'dr_t1_int_4', skill: 'daily_routine', tier: 1, difficulty: 'intermediate',
    type: 'true_false', topic: 'bedtime_routine',
    question: 'Keeping your bedroom tidy helps you sleep better.',
    questionImage: 'tidy_room.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Think about how a messy vs tidy space makes you feel.',
    explanation: 'A tidy bedroom reduces stress and helps your mind relax before sleep. It also makes it easier to find things in the morning.',
  },
  {
    id: 'dr_t1_int_5', skill: 'daily_routine', tier: 1, difficulty: 'intermediate',
    type: 'tap_select', topic: 'hygiene',
    question: 'How often should you bathe or shower?',
    questionImage: 'bathing.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Every day or at least every other day', correct: true },
      { id: 'b', label: 'Once a week', correct: false },
      { id: 'c', label: 'Only when you smell bad', correct: false },
      { id: 'd', label: 'Once a month', correct: false },
    ],
    hint: 'Regular bathing keeps skin healthy and removes sweat and dirt.',
    explanation: 'Bathing daily or every other day keeps you clean, prevents skin problems, and is respectful to those around you.',
  },
  {
    id: 'dr_t1_int_6', skill: 'daily_routine', tier: 1, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'morning_routine',
    question: 'You wake up late and only have 20 minutes before you need to leave. What is the most important thing to do?',
    questionImage: 'morning_rush.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Quick hygiene — wash face, brush teeth, get dressed', correct: true },
      { id: 'b', label: 'Cook a full breakfast and skip hygiene', correct: false },
      { id: 'c', label: 'Go back to sleep for 10 more minutes', correct: false },
      { id: 'd', label: 'Spend 15 minutes choosing the perfect outfit', correct: false },
    ],
    hint: 'When time is short, prioritise hygiene and getting dressed.',
    explanation: 'Basic hygiene is non-negotiable even when late. A quick wash, brush teeth, and getting dressed should always come first.',
  },
  {
    id: 'dr_t1_int_7', skill: 'daily_routine', tier: 1, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'meal_times',
    question: 'The three main meals of the day are breakfast, ___, and dinner.',
    questionImage: 'meal_times.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Lunch', correct: true },
      { id: 'b', label: 'Snack', correct: false },
      { id: 'c', label: 'Supper', correct: false },
    ],
    hint: 'There is a meal between breakfast and dinner.',
    explanation: 'The three main meals are breakfast (morning), lunch (midday), and dinner or supper (evening).',
  },

  // Tier 1 / Advanced
  {
    id: 'dr_t1_adv_1', skill: 'daily_routine', tier: 1, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'morning_routine',
    question: 'You notice your school uniform is dirty the night before school. What should you do?',
    questionImage: 'clean_clothes.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Wash and hang it to dry tonight so it is ready in the morning', correct: true },
      { id: 'b', label: 'Wear it dirty — no one will notice', correct: false },
      { id: 'c', label: 'Skip school because you have nothing to wear', correct: false },
      { id: 'd', label: 'Wait and wash it in the morning when you are already late', correct: false },
    ],
    hint: 'Plan ahead — washing at night gives time to dry.',
    explanation: 'Washing clothes the night before gives them time to dry. Planning ahead prevents morning problems.',
  },
  {
    id: 'dr_t1_adv_2', skill: 'daily_routine', tier: 1, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'bedtime_routine',
    question: 'Put these bedtime routine steps in the correct order.',
    questionImage: 'bedtime_routine.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Finish homework or tasks for the day', order: 1 },
      { id: 's2', label: 'Prepare clothes and bag for the next day', order: 2 },
      { id: 's3', label: 'Eat a light evening meal if needed', order: 3 },
      { id: 's4', label: 'Brush teeth and wash face', order: 4 },
      { id: 's5', label: 'Get into bed at a consistent time', order: 5 },
    ],
    hint: 'Finish tasks first, then prepare for tomorrow, then wind down.',
    explanation: 'A good bedtime routine: finish work → prepare for tomorrow → light meal → hygiene → sleep. Consistency helps your body clock.',
  },
  {
    id: 'dr_t1_adv_3', skill: 'daily_routine', tier: 1, difficulty: 'advanced',
    type: 'tap_select', topic: 'hygiene',
    question: 'Which of these is the correct order for washing hands properly?',
    questionImage: 'handwashing.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Wet hands → apply soap → scrub 20 seconds → rinse → dry', correct: true },
      { id: 'b', label: 'Apply soap → wet hands → rinse → dry', correct: false },
      { id: 'c', label: 'Rinse → soap → dry', correct: false },
      { id: 'd', label: 'Wet hands → rinse → dry', correct: false },
    ],
    hint: 'Soap must be on wet hands and scrubbed before rinsing.',
    explanation: 'Proper handwashing: wet → soap → scrub 20 seconds → rinse → dry. This order removes germs effectively.',
  },
  {
    id: 'dr_t1_adv_4', skill: 'daily_routine', tier: 1, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'meal_times',
    question: 'You skipped breakfast and now feel dizzy and unable to concentrate in class. What should you do?',
    questionImage: 'breakfast.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Eat a small snack at break time and make sure to eat breakfast tomorrow', correct: true },
      { id: 'b', label: 'Push through — hunger goes away eventually', correct: false },
      { id: 'c', label: 'Eat a huge lunch to make up for it', correct: false },
      { id: 'd', label: 'Ask to go home sick', correct: false },
    ],
    hint: 'Your body needs fuel — a small snack helps now, and planning prevents it tomorrow.',
    explanation: 'Eat a snack when you can and plan to have breakfast every day. Skipping meals affects your concentration and energy.',
  },
  {
    id: 'dr_t1_adv_5', skill: 'daily_routine', tier: 1, difficulty: 'advanced',
    type: 'true_false', topic: 'morning_routine',
    question: 'Preparing your school bag the night before saves time in the morning.',
    questionImage: 'school_bag.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: true },
      { id: 'false', label: 'False', correct: false },
    ],
    hint: 'Think about how much time you spend looking for things in the morning.',
    explanation: 'Packing your bag at night means one less thing to do in the morning. It prevents forgetting important items too.',
  },
  {
    id: 'dr_t1_adv_6', skill: 'daily_routine', tier: 1, difficulty: 'advanced',
    type: 'drag_drop', topic: 'hygiene',
    question: 'Sort these hygiene tasks into Morning or Evening.',
    questionImage: 'morning_routine.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'h1', label: 'Brush teeth', targetZone: 'both' },
      { id: 'h2', label: 'Wash face', targetZone: 'both' },
      { id: 'h3', label: 'Take a shower or bath', targetZone: 'morning' },
      { id: 'h4', label: 'Apply lotion or moisturiser', targetZone: 'morning' },
      { id: 'h5', label: 'Remove shoes before entering home', targetZone: 'evening' },
      { id: 'h6', label: 'Change into home clothes', targetZone: 'evening' },
    ],
    dropZones: [
      { id: 'morning', label: 'Morning only' },
      { id: 'evening', label: 'Evening only' },
      { id: 'both', label: 'Both morning and evening' },
    ],
    hint: 'Some hygiene tasks are done twice a day, others once.',
    explanation: 'Teeth and face: both morning and evening. Shower and lotion: morning. Remove shoes and change clothes: evening.',
  },
  {
    id: 'dr_t1_adv_7', skill: 'daily_routine', tier: 1, difficulty: 'advanced',
    type: 'fill_blank', topic: 'bedtime_routine',
    question: 'Going to bed at the same time every night helps your body build a natural ___.',
    questionImage: 'bedtime.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Clock or rhythm', correct: true },
      { id: 'b', label: 'Habit of staying awake', correct: false },
      { id: 'c', label: 'Reason to wake up late', correct: false },
    ],
    hint: 'Your body has an internal system that regulates sleep.',
    explanation: 'A consistent bedtime trains your body clock. You will fall asleep faster and wake up more easily.',
  },

  // =========================================================================
  // TIER 2 — APPLICATION
  // =========================================================================

  // Tier 2 / Easy
  {
    id: 'dr_t2_easy_1', skill: 'daily_routine', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'morning_routine',
    question: 'You wake up feeling tired and do not want to get up. What is the best thing to do?',
    questionImage: 'morning_wake.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Get up anyway — your routine will help you wake up properly', correct: true },
      { id: 'b', label: 'Stay in bed until you feel ready', correct: false },
      { id: 'c', label: 'Skip the whole day', correct: false },
      { id: 'd', label: 'Ask someone else to do your tasks', correct: false },
    ],
    hint: 'Starting your routine helps your body and mind wake up.',
    explanation: 'Getting up at a regular time even when tired helps maintain your body clock. Movement and light help you wake up quickly.',
  },
  {
    id: 'dr_t2_easy_2', skill: 'daily_routine', tier: 2, difficulty: 'easy',
    type: 'true_false', topic: 'hygiene',
    question: 'Washing hands after using the toilet is optional if your hands look clean.',
    questionImage: 'handwashing.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Germs are invisible — clean-looking hands can still carry them.',
    explanation: 'Always wash hands after using the toilet regardless of how clean they look. Germs are invisible and cause serious illness.',
  },
  {
    id: 'dr_t2_easy_3', skill: 'daily_routine', tier: 2, difficulty: 'easy',
    type: 'tap_select', topic: 'meal_times',
    question: 'You feel hungry between breakfast and lunch. What is the healthiest option?',
    questionImage: 'healthy_snack.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'A piece of fruit or a small healthy snack', correct: true },
      { id: 'b', label: 'A large bag of crisps', correct: false },
      { id: 'c', label: 'Three mandazi', correct: false },
      { id: 'd', label: 'Skip it and wait for lunch', correct: false },
    ],
    hint: 'A small healthy snack keeps your energy stable.',
    explanation: 'A fruit or light snack between meals keeps energy levels stable. Heavy snacks can reduce appetite for proper meals.',
  },
  {
    id: 'dr_t2_easy_4', skill: 'daily_routine', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'bedtime_routine',
    question: 'It is 10 PM and you are still doing homework. You need to wake up at 6 AM. What should you do?',
    questionImage: 'bedtime.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Finish what you can, then sleep — do the rest in the morning', correct: true },
      { id: 'b', label: 'Stay up until all homework is done even if it takes until 2 AM', correct: false },
      { id: 'c', label: 'Skip the homework entirely', correct: false },
      { id: 'd', label: 'Ask to skip school tomorrow', correct: false },
    ],
    hint: 'Sleep is important — a tired mind cannot learn well either.',
    explanation: 'Finish what you reasonably can and sleep. Next time, start homework earlier. A rested mind learns better than an exhausted one.',
  },
  {
    id: 'dr_t2_easy_5', skill: 'daily_routine', tier: 2, difficulty: 'easy',
    type: 'true_false', topic: 'hygiene',
    question: 'Clean water is not necessary for brushing teeth — any water will do.',
    questionImage: 'brushing_teeth.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Think about what happens if you use dirty water on your teeth.',
    explanation: 'Always use clean water for brushing teeth. Dirty water carries bacteria that can cause illness even if you spit it out.',
  },
  {
    id: 'dr_t2_easy_6', skill: 'daily_routine', tier: 2, difficulty: 'easy',
    type: 'tap_select', topic: 'morning_routine',
    question: 'What is the benefit of having a consistent morning routine?',
    questionImage: 'morning_routine.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'It saves time and reduces stress', correct: true },
      { id: 'b', label: 'It makes mornings longer', correct: false },
      { id: 'c', label: 'It means you never need to think', correct: false },
      { id: 'd', label: 'It is only useful for children', correct: false },
    ],
    hint: 'When you do the same things in the same order, you become faster at them.',
    explanation: 'A consistent routine saves mental energy. You do not have to think about what comes next — it becomes automatic.',
  },
  {
    id: 'dr_t2_easy_7', skill: 'daily_routine', tier: 2, difficulty: 'easy',
    type: 'scenario_choice', topic: 'hygiene',
    question: 'You are visiting a friend and notice their toilet has no soap. What should you do?',
    questionImage: 'handwashing.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Wash hands with water only — it is better than nothing', correct: true },
      { id: 'b', label: 'Skip washing hands — no soap means no point', correct: false },
      { id: 'c', label: 'Refuse to use their toilet', correct: false },
      { id: 'd', label: 'Use a tissue to wipe hands instead', correct: false },
    ],
    hint: 'Water alone removes some germs — it is still better than nothing.',
    explanation: 'Water alone removes some germs when there is no soap. Always wash with water at minimum. Carry a small soap or sanitiser when possible.',
  },

  // Tier 2 / Intermediate
  {
    id: 'dr_t2_int_1', skill: 'daily_routine', tier: 2, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'morning_routine',
    question: 'You need to leave by 7:00 AM. Put these tasks in the most efficient order.',
    questionImage: 'morning_rush.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Wake up at 5:30 AM', order: 1 },
      { id: 's2', label: 'Boil water for tea while bathing', order: 2 },
      { id: 's3', label: 'Bathe and do hygiene', order: 3 },
      { id: 's4', label: 'Eat breakfast with tea', order: 4 },
      { id: 's5', label: 'Dress and pack bag', order: 5 },
      { id: 's6', label: 'Leave at 7:00 AM', order: 6 },
    ],
    hint: 'Multi-task where possible — boil water while bathing saves time.',
    explanation: 'Efficient morning: wake early → start water while bathing → eat → dress → leave. Multi-tasking saves time.',
  },
  {
    id: 'dr_t2_int_2', skill: 'daily_routine', tier: 2, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'meal_times',
    question: 'You have been very busy and skipped lunch. It is now 4 PM. What is the best choice?',
    questionImage: 'healthy_snack.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Eat a moderate meal now and a lighter dinner later', correct: true },
      { id: 'b', label: 'Wait until dinner time even though it is 3 hours away', correct: false },
      { id: 'c', label: 'Eat a huge meal to make up for the missed lunch', correct: false },
      { id: 'd', label: 'Drink lots of water to suppress hunger', correct: false },
    ],
    hint: 'Your body needs fuel — a moderate meal now is better than waiting too long.',
    explanation: 'Eat a moderate meal when hungry and adjust dinner accordingly. Starving then overeating disrupts your digestive rhythm.',
  },
  {
    id: 'dr_t2_int_3', skill: 'daily_routine', tier: 2, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'hygiene',
    question: 'Sort these situations into Always Wash Hands or No Need to Wash.',
    questionImage: 'handwashing.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'w1', label: 'After using the toilet', targetZone: 'always' },
      { id: 'w2', label: 'Before eating any food', targetZone: 'always' },
      { id: 'w3', label: 'After touching animals', targetZone: 'always' },
      { id: 'w4', label: 'After watching TV', targetZone: 'noneed' },
      { id: 'w5', label: 'After handling raw meat', targetZone: 'always' },
      { id: 'w6', label: 'After reading a book', targetZone: 'noneed' },
    ],
    dropZones: [
      { id: 'always', label: 'Always wash hands' },
      { id: 'noneed', label: 'No need to wash' },
    ],
    hint: 'Wash hands after contact with germs or before food.',
    explanation: 'Always wash after toilet, before food, after animals, and after raw meat. Reading and watching TV do not require handwashing.',
  },
  {
    id: 'dr_t2_int_4', skill: 'daily_routine', tier: 2, difficulty: 'intermediate',
    type: 'true_false', topic: 'bedtime_routine',
    question: 'Using your phone in bed for an hour before sleep helps you relax.',
    questionImage: 'bedtime.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Phone screens emit blue light that affects sleep quality.',
    explanation: 'Phone screens emit blue light that tricks your brain into thinking it is daytime. This delays sleep and reduces quality.',
  },
  {
    id: 'dr_t2_int_5', skill: 'daily_routine', tier: 2, difficulty: 'intermediate',
    type: 'tap_select', topic: 'morning_routine',
    question: 'Which of these evening habits helps the most with a smooth morning?',
    questionImage: 'bedtime_routine.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Prepare clothes, bag, and breakfast items the night before', correct: true },
      { id: 'b', label: 'Stay up late watching series so you are tired enough to sleep', correct: false },
      { id: 'c', label: 'Leave everything for the morning', correct: false },
      { id: 'd', label: 'Set 10 different alarms just in case', correct: false },
    ],
    hint: 'Preparation at night removes decision-making from the morning.',
    explanation: 'Preparing everything the night before means your morning is faster and calmer. Less decision-making when you are still waking up.',
  },
  {
    id: 'dr_t2_int_6', skill: 'daily_routine', tier: 2, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'hygiene',
    question: 'A family member is sick with a cold and you share a bathroom. What should you do differently?',
    questionImage: 'handwashing.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Wash hands more frequently and avoid touching your face', correct: true },
      { id: 'b', label: 'Nothing different — colds are not serious', correct: false },
      { id: 'c', label: 'Stop using the bathroom until they recover', correct: false },
      { id: 'd', label: 'Use their towel to build immunity', correct: false },
    ],
    hint: 'Colds spread through contact — extra hygiene reduces risk.',
    explanation: 'Wash hands more often and avoid touching your eyes, nose, and mouth. These are the main routes cold viruses enter the body.',
  },
  {
    id: 'dr_t2_int_7', skill: 'daily_routine', tier: 2, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'meal_times',
    question: 'Drinking ___ glasses of water per day is recommended for good health.',
    questionImage: 'healthy_snack.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: '8', correct: true },
      { id: 'b', label: '2', correct: false },
      { id: 'c', label: '20', correct: false },
    ],
    hint: 'Think about how much water health experts recommend daily.',
    explanation: 'About 8 glasses (2 litres) of water per day is recommended. More if you are active or in hot weather.',
  },

  // Tier 2 / Advanced
  {
    id: 'dr_t2_adv_1', skill: 'daily_routine', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'morning_routine',
    question: 'You want to add a 30-minute exercise session to your morning routine. You currently leave at 7:00 AM and wake at 6:00 AM. What should you change?',
    questionImage: 'morning_routine.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Wake up at 5:30 AM to fit exercise before your normal routine', correct: true },
      { id: 'b', label: 'Skip breakfast to make time for exercise', correct: false },
      { id: 'c', label: 'Exercise after work instead', correct: false },
      { id: 'd', label: 'Exercise while getting dressed', correct: false },
    ],
    hint: 'You need 30 extra minutes — the only way is to wake 30 minutes earlier.',
    explanation: 'Wake 30 minutes earlier: 5:30 AM. Exercise 5:30–6:00, then normal routine 6:00–7:00. Skipping breakfast is not a healthy trade-off.',
  },
  {
    id: 'dr_t2_adv_2', skill: 'daily_routine', tier: 2, difficulty: 'advanced',
    type: 'drag_drop', topic: 'meal_times',
    question: 'Sort these foods into Healthy Daily Choice or Occasional Treat.',
    questionImage: 'healthy_snack.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'm1', label: 'Sukuma wiki and ugali', targetZone: 'healthy' },
      { id: 'm2', label: 'Fresh fruit', targetZone: 'healthy' },
      { id: 'm3', label: 'Boiled eggs', targetZone: 'healthy' },
      { id: 'm4', label: 'Soda and crisps', targetZone: 'treat' },
      { id: 'm5', label: 'Mandazi every day', targetZone: 'treat' },
      { id: 'm6', label: 'Boiled groundnuts', targetZone: 'healthy' },
    ],
    dropZones: [
      { id: 'healthy', label: 'Healthy Daily Choice' },
      { id: 'treat', label: 'Occasional Treat' },
    ],
    hint: 'Whole foods are healthy daily choices. High sugar and fried foods are treats.',
    explanation: 'Sukuma wiki, fruit, eggs, and groundnuts are nutritious daily foods. Soda, crisps, and daily mandazi are high in sugar and fat.',
  },
  {
    id: 'dr_t2_adv_3', skill: 'daily_routine', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'hygiene',
    question: 'You notice you have been getting headaches in the afternoon. You drink little water during the day. What is likely happening and what should you do?',
    questionImage: 'healthy_snack.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'You may be dehydrated — start drinking water regularly throughout the day', correct: true },
      { id: 'b', label: 'The headaches are from too much work — rest more', correct: false },
      { id: 'c', label: 'Drink soda to get fluids quickly', correct: false },
      { id: 'd', label: 'Take painkillers every afternoon', correct: false },
    ],
    hint: 'Dehydration is a common cause of afternoon headaches.',
    explanation: 'Not drinking enough water causes dehydration which leads to headaches. Drink water consistently throughout the day — not just when thirsty.',
  },
  {
    id: 'dr_t2_adv_4', skill: 'daily_routine', tier: 2, difficulty: 'advanced',
    type: 'true_false', topic: 'bedtime_routine',
    question: 'Adults need the same amount of sleep as children — 10 hours per night.',
    questionImage: 'bedtime.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Sleep needs change as we grow older.',
    explanation: 'Adults need 7 to 9 hours of sleep. Children and teenagers need 9 to 11 hours. Sleep needs decrease gradually with age.',
  },
  {
    id: 'dr_t2_adv_5', skill: 'daily_routine', tier: 2, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'hygiene',
    question: 'Put these steps for doing laundry in the correct order.',
    questionImage: 'clean_clothes.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Sort clothes by colour and fabric type', order: 1 },
      { id: 's2', label: 'Fill basin or machine with water and add soap', order: 2 },
      { id: 's3', label: 'Wash and scrub clothes thoroughly', order: 3 },
      { id: 's4', label: 'Rinse clothes until water runs clear', order: 4 },
      { id: 's5', label: 'Wring out and hang to dry in the sun', order: 5 },
    ],
    hint: 'Sort first, then wash, rinse, and dry.',
    explanation: 'Laundry: sort → wash with soap → scrub → rinse completely → hang to dry. Sorting prevents colours from running.',
  },
  {
    id: 'dr_t2_adv_6', skill: 'daily_routine', tier: 2, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'morning_routine',
    question: 'Your routine works well on weekdays but you completely abandon it on weekends. What is the effect?',
    questionImage: 'morning_routine.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Monday mornings are harder because your body clock is disrupted', correct: true },
      { id: 'b', label: 'Weekends are for rest — no routine needed', correct: false },
      { id: 'c', label: 'No effect — the body adjusts instantly', correct: false },
      { id: 'd', label: 'It makes your weekday routine stronger', correct: false },
    ],
    hint: 'Your body clock needs consistency to work well.',
    explanation: 'Disrupting your routine on weekends confuses your body clock. You can relax the routine slightly but keeping similar sleep and wake times helps.',
  },
  {
    id: 'dr_t2_adv_7', skill: 'daily_routine', tier: 2, difficulty: 'advanced',
    type: 'fill_blank', topic: 'bedtime_routine',
    question: 'The best temperature for sleeping is ___ — cool but not cold.',
    questionImage: 'bedtime_routine.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Slightly cool — around 18 to 22 degrees', correct: true },
      { id: 'b', label: 'Very warm — like a hot day', correct: false },
      { id: 'c', label: 'Freezing cold', correct: false },
    ],
    hint: 'Your body temperature drops slightly during sleep.',
    explanation: 'A slightly cool room (18–22°C) helps your body temperature drop naturally for sleep. Too hot or too cold disrupts sleep quality.',
  },

  // =========================================================================
  // TIER 3 — INDEPENDENCE
  // =========================================================================

  // Tier 3 / Easy
  {
    id: 'dr_t3_easy_1', skill: 'daily_routine', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'morning_routine',
    question: 'You are responsible for your own morning routine for the first time. What is the most important thing to establish first?',
    questionImage: 'morning_routine.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'A consistent wake-up time and go-to-bed time every day', correct: true },
      { id: 'b', label: 'The perfect breakfast menu for each day', correct: false },
      { id: 'c', label: 'The most stylish morning outfit choices', correct: false },
      { id: 'd', label: 'A different routine every day to keep it interesting', correct: false },
    ],
    hint: 'Consistency in sleep and wake times anchors everything else.',
    explanation: 'Consistent sleep and wake times set your body clock. Everything else — hygiene, meals, tasks — falls into place around this.',
  },
  {
    id: 'dr_t3_easy_2', skill: 'daily_routine', tier: 3, difficulty: 'easy',
    type: 'true_false', topic: 'hygiene',
    question: 'Personal hygiene only matters when you are going out — at home it is not important.',
    questionImage: 'bathing.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Hygiene is about health, not just appearance.',
    explanation: 'Hygiene matters at home too — bacteria and odours build up regardless of whether you go out. Daily hygiene is a health habit, not just a social one.',
  },
  {
    id: 'dr_t3_easy_3', skill: 'daily_routine', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'meal_times',
    question: 'You are living alone and realise you have not eaten a proper meal in two days — only snacks. What should you do?',
    questionImage: 'healthy_snack.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Cook or buy a proper meal now and plan simple meals for the week', correct: true },
      { id: 'b', label: 'Continue with snacks — they are easier', correct: false },
      { id: 'c', label: 'Fast for another day to compensate', correct: false },
      { id: 'd', label: 'Wait until someone cooks for you', correct: false },
    ],
    hint: 'Your body needs proper meals for nutrients — snacks are not enough.',
    explanation: 'Eat a proper meal now and plan ahead for the week. Simple meals like ugali, rice, or boiled eggs are easy and nutritious.',
  },
  {
    id: 'dr_t3_easy_4', skill: 'daily_routine', tier: 3, difficulty: 'easy',
    type: 'tap_select', topic: 'hygiene',
    question: 'You notice your home is getting dirty and smelly. What is the first thing to address?',
    questionImage: 'tidy_room.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Dispose of rubbish and wash dirty dishes', correct: true },
      { id: 'b', label: 'Buy air freshener to cover the smell', correct: false },
      { id: 'c', label: 'Open all windows and hope the smell goes away', correct: false },
      { id: 'd', label: 'Move to a different room', correct: false },
    ],
    hint: 'Remove the source of dirt and smell first.',
    explanation: 'Rubbish and dirty dishes are the most common sources of bad smells. Remove them first before cleaning or freshening the air.',
  },
  {
    id: 'dr_t3_easy_5', skill: 'daily_routine', tier: 3, difficulty: 'easy',
    type: 'true_false', topic: 'bedtime_routine',
    question: 'It is fine to eat a large heavy meal right before sleeping.',
    questionImage: 'bedtime.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Your digestive system is still working while you sleep.',
    explanation: 'Eating heavily right before sleep causes discomfort and disrupts sleep quality. Eat at least 2 hours before bed.',
  },
  {
    id: 'dr_t3_easy_6', skill: 'daily_routine', tier: 3, difficulty: 'easy',
    type: 'scenario_choice', topic: 'morning_routine',
    question: 'You have been struggling to wake up on time for two weeks. What is the most effective long-term solution?',
    questionImage: 'morning_wake.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Go to bed earlier so you get enough sleep before your alarm', correct: true },
      { id: 'b', label: 'Set more alarms', correct: false },
      { id: 'c', label: 'Ask someone to wake you every day', correct: false },
      { id: 'd', label: 'Drink coffee before bed to sleep lightly', correct: false },
    ],
    hint: 'The problem is not waking up — it is not getting enough sleep.',
    explanation: 'If you cannot wake up, you are likely not getting enough sleep. Go to bed earlier — that is the root fix.',
  },
  {
    id: 'dr_t3_easy_7', skill: 'daily_routine', tier: 3, difficulty: 'easy',
    type: 'sequential_steps', topic: 'hygiene',
    question: 'Put these house cleaning tasks in order of priority.',
    questionImage: 'tidy_room.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Dispose of all rubbish', order: 1 },
      { id: 's2', label: 'Wash dirty dishes', order: 2 },
      { id: 's3', label: 'Sweep or mop the floor', order: 3 },
      { id: 's4', label: 'Wipe surfaces and windows', order: 4 },
      { id: 's5', label: 'Arrange furniture and personal items neatly', order: 5 },
    ],
    hint: 'Start with what causes smell and mess, then clean, then organise.',
    explanation: 'Priority cleaning: rubbish → dishes → floor → surfaces → organise. This order removes smell and dirt before tidying.',
  },

  // Tier 3 / Intermediate
  {
    id: 'dr_t3_int_1', skill: 'daily_routine', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'morning_routine',
    question: 'You are caring for a younger sibling in the morning before school. How do you manage both your routine and theirs?',
    questionImage: 'morning_rush.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Wake up 30 minutes earlier to have time for both routines', correct: true },
      { id: 'b', label: 'Let the sibling manage alone — you have your own routine', correct: false },
      { id: 'c', label: 'Skip your own breakfast to have time for theirs', correct: false },
      { id: 'd', label: 'Make them wake up at the same time as you', correct: false },
    ],
    hint: 'Extra responsibility requires extra time — wake earlier.',
    explanation: 'Wake 30 minutes earlier to accommodate both. Do your hygiene first, then help the sibling while your breakfast cooks — multi-task.',
  },
  {
    id: 'dr_t3_int_2', skill: 'daily_routine', tier: 3, difficulty: 'intermediate',
    type: 'drag_drop', topic: 'meal_times',
    question: 'You have KES 200 for the day. Sort these food choices into Nutritious and Worth It or Not Worth It.',
    questionImage: 'healthy_snack.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'n1', label: 'Boiled eggs and bread — KES 50', targetZone: 'worth' },
      { id: 'n2', label: 'Packet of crisps — KES 50', targetZone: 'notworth' },
      { id: 'n3', label: 'Githeri from mama mboga — KES 60', targetZone: 'worth' },
      { id: 'n4', label: 'Soda — KES 60', targetZone: 'notworth' },
      { id: 'n5', label: 'Banana and groundnuts — KES 40', targetZone: 'worth' },
    ],
    dropZones: [
      { id: 'worth', label: 'Nutritious and worth it' },
      { id: 'notworth', label: 'Not the best choice' },
    ],
    hint: 'Choose foods that fill you and give you energy — not just taste.',
    explanation: 'Eggs, githeri, and groundnuts provide protein and energy. Crisps and soda are expensive for the nutrition they provide.',
  },
  {
    id: 'dr_t3_int_3', skill: 'daily_routine', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'hygiene',
    question: 'You live in an area with limited water supply. Water is only available for 2 hours each morning. How do you manage your hygiene routine?',
    questionImage: 'bathing.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Store water in clean containers during the 2 hours for use throughout the day', correct: true },
      { id: 'b', label: 'Only bathe when water is available — skip other hygiene on dry days', correct: false },
      { id: 'c', label: 'Use dirty water for washing since clean water is scarce', correct: false },
      { id: 'd', label: 'Stop maintaining hygiene until water supply improves', correct: false },
    ],
    hint: 'Plan and store water to use throughout the day.',
    explanation: 'Store clean water during supply hours for later use. Prioritise drinking water first, then hygiene. Even limited water can maintain good hygiene with planning.',
  },
  {
    id: 'dr_t3_int_4', skill: 'daily_routine', tier: 3, difficulty: 'intermediate',
    type: 'true_false', topic: 'bedtime_routine',
    question: 'Stress and worry at night are normal and cannot be managed — you just have to wait until you fall asleep.',
    questionImage: 'bedtime_routine.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'There are practical techniques that help calm the mind before sleep.',
    explanation: 'Stress at night can be managed: write down worries in a notebook, do slow breathing, or pray. These techniques signal the brain to calm down.',
  },
  {
    id: 'dr_t3_int_5', skill: 'daily_routine', tier: 3, difficulty: 'intermediate',
    type: 'sequential_steps', topic: 'morning_routine',
    question: 'You are cooking breakfast and getting ready at the same time. Put these steps in the most efficient order.',
    questionImage: 'morning_rush.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Put water or food on the stove to cook', order: 1 },
      { id: 's2', label: 'Bathe and do hygiene while food cooks', order: 2 },
      { id: 's3', label: 'Get dressed while checking food', order: 3 },
      { id: 's4', label: 'Serve and eat breakfast', order: 4 },
      { id: 's5', label: 'Pack bag and leave', order: 5 },
    ],
    hint: 'Start the stove first so food cooks while you prepare yourself.',
    explanation: 'Start cooking first — this is the slowest task. Use cooking time for hygiene and dressing. Then eat and leave.',
  },
  {
    id: 'dr_t3_int_6', skill: 'daily_routine', tier: 3, difficulty: 'intermediate',
    type: 'scenario_choice', topic: 'hygiene',
    question: 'A family member is unwell and you are caring for them at home. What hygiene practices are most important?',
    questionImage: 'handwashing.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Wash hands before and after contact, keep their space clean, and dispose of tissues immediately', correct: true },
      { id: 'b', label: 'Avoid all contact until they recover', correct: false },
      { id: 'c', label: 'Wear a mask only when they are coughing', correct: false },
      { id: 'd', label: 'Clean only when they ask you to', correct: false },
    ],
    hint: 'Frequent handwashing and cleanliness reduce spread.',
    explanation: 'Wash hands before and after contact, keep their environment clean, dispose of tissues promptly, and consider wearing a mask. These reduce risk of spreading illness.',
  },
  {
    id: 'dr_t3_int_7', skill: 'daily_routine', tier: 3, difficulty: 'intermediate',
    type: 'fill_blank', topic: 'meal_times',
    question: 'A balanced meal should include a source of ___, vegetables, and carbohydrates.',
    questionImage: 'healthy_snack.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Protein (meat, eggs, beans, or fish)', correct: true },
      { id: 'b', label: 'Sugar (soda or sweets)', correct: false },
      { id: 'c', label: 'Fat (cooking oil or butter only)', correct: false },
    ],
    hint: 'Think about what your body needs to build and repair itself.',
    explanation: 'A balanced meal: protein (meat/eggs/beans) + vegetables + carbohydrates (ugali/rice/chapati). This combination provides energy, repair, and nutrients.',
  },

  // Tier 3 / Advanced
  {
    id: 'dr_t3_adv_1', skill: 'daily_routine', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'morning_routine',
    question: 'You are starting a new job that begins at 6:00 AM. Your previous routine was built around a 9:00 AM start. How do you adjust?',
    questionImage: 'morning_routine.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Shift your entire routine 3 hours earlier — sleep, wake, and meals all move back', correct: true },
      { id: 'b', label: 'Keep the same sleep time and just wake up 3 hours earlier', correct: false },
      { id: 'c', label: 'Skip the morning routine until you get used to the new time', correct: false },
      { id: 'd', label: 'Rely on coffee to replace sleep', correct: false },
    ],
    hint: 'Your whole body clock needs to shift — not just your alarm.',
    explanation: 'Shift everything: sleep earlier, wake earlier, eat earlier. Your body clock adjusts within 1 to 2 weeks if you are consistent.',
  },
  {
    id: 'dr_t3_adv_2', skill: 'daily_routine', tier: 3, difficulty: 'advanced',
    type: 'drag_drop', topic: 'hygiene',
    question: 'You share a home with 3 others. Sort these hygiene responsibilities into Individual or Shared.',
    questionImage: 'tidy_room.jpg', imageLayout: 'context',
    dragItems: [
      { id: 'r1', label: 'Brushing your own teeth', targetZone: 'individual' },
      { id: 'r2', label: 'Cleaning the shared toilet', targetZone: 'shared' },
      { id: 'r3', label: 'Washing your own clothes', targetZone: 'individual' },
      { id: 'r4', label: 'Sweeping the common living area', targetZone: 'shared' },
      { id: 'r5', label: 'Bathing yourself', targetZone: 'individual' },
      { id: 'r6', label: 'Taking out the shared rubbish', targetZone: 'shared' },
    ],
    dropZones: [
      { id: 'individual', label: 'Individual responsibility' },
      { id: 'shared', label: 'Shared responsibility' },
    ],
    hint: 'Personal hygiene is individual. Common space upkeep is shared.',
    explanation: 'Personal hygiene (teeth, bathing, laundry) is your own responsibility. Common spaces (toilet, living area, rubbish) are shared responsibilities.',
  },
  {
    id: 'dr_t3_adv_3', skill: 'daily_routine', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'meal_times',
    question: 'You are working long hours and often skip meals. After two weeks you feel weak and unwell. What is the underlying problem and solution?',
    questionImage: 'healthy_snack.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Poor nutrition from skipping meals — schedule and prepare simple meals in advance', correct: true },
      { id: 'b', label: 'You are working too hard — reduce your hours', correct: false },
      { id: 'c', label: 'You need vitamin supplements instead of meals', correct: false },
      { id: 'd', label: 'Energy drinks will solve the problem', correct: false },
    ],
    hint: 'Your body needs regular fuel — planning ahead is the solution.',
    explanation: 'Skipping meals causes nutritional deficiency and weakness. Prepare simple meals in advance — boiled eggs, bread, fruit — so eating does not require cooking time.',
  },
  {
    id: 'dr_t3_adv_4', skill: 'daily_routine', tier: 3, difficulty: 'advanced',
    type: 'true_false', topic: 'bedtime_routine',
    question: 'Chronic sleep deprivation (regularly sleeping less than 6 hours) has no serious long-term health effects.',
    questionImage: 'bedtime.jpg', imageLayout: 'context',
    options: [
      { id: 'true', label: 'True', correct: false },
      { id: 'false', label: 'False', correct: true },
    ],
    hint: 'Think about what your body does during sleep — repair, memory, immune function.',
    explanation: 'Chronic sleep deprivation causes serious health problems: weakened immunity, poor memory, increased risk of heart disease, and mental health issues.',
  },
  {
    id: 'dr_t3_adv_5', skill: 'daily_routine', tier: 3, difficulty: 'advanced',
    type: 'sequential_steps', topic: 'hygiene',
    question: 'You are setting up hygiene routines for yourself in a new home. Put these one-time setup steps in the correct order.',
    questionImage: 'tidy_room.jpg', imageLayout: 'context',
    steps: [
      { id: 's1', label: 'Deep clean the entire space before moving anything in', order: 1 },
      { id: 's2', label: 'Set up dedicated hygiene supplies in bathroom — soap, toothbrush, towel', order: 2 },
      { id: 's3', label: 'Designate areas for clean and dirty clothes', order: 3 },
      { id: 's4', label: 'Set up a cleaning schedule — daily, weekly, monthly tasks', order: 4 },
      { id: 's5', label: 'Stock basic cleaning supplies — soap, broom, mop, rubbish bags', order: 5 },
    ],
    hint: 'Clean first, then set up, then organise, then plan maintenance.',
    explanation: 'New home setup: deep clean → hygiene supplies → clothes areas → cleaning schedule → cleaning supplies stocked. This creates a sustainable hygiene system.',
  },
  {
    id: 'dr_t3_adv_6', skill: 'daily_routine', tier: 3, difficulty: 'advanced',
    type: 'scenario_choice', topic: 'morning_routine',
    question: 'You have been maintaining a good routine for 3 months but a period of stress caused you to abandon it for 2 weeks. How do you get back on track?',
    questionImage: 'morning_routine.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Restart the routine immediately — even if imperfect — and rebuild gradually', correct: true },
      { id: 'b', label: 'Wait until the stress is completely gone before restarting', correct: false },
      { id: 'c', label: 'Accept that the routine is lost and start a completely new one', correct: false },
      { id: 'd', label: 'Punish yourself for abandoning the routine', correct: false },
    ],
    hint: 'Progress is not lost — restart immediately, imperfectly.',
    explanation: 'Restart now even if imperfect. Two weeks off does not erase 3 months of habit. Be kind to yourself and rebuild — consistency over perfection.',
  },
  {
    id: 'dr_t3_adv_7', skill: 'daily_routine', tier: 3, difficulty: 'advanced',
    type: 'fill_blank', topic: 'meal_times',
    question: 'Preparing meals in ___ — cooking multiple portions at once — saves time and ensures you always have proper food available.',
    questionImage: 'healthy_snack.jpg', imageLayout: 'context',
    options: [
      { id: 'a', label: 'Batches or bulk', correct: true },
      { id: 'b', label: 'A hurry', correct: false },
      { id: 'c', label: 'Secret', correct: false },
    ],
    hint: 'Cooking once for multiple meals is a practical time-saving strategy.',
    explanation: 'Batch cooking means cooking large portions once and eating across several meals. It saves time, reduces cost, and ensures you always have nutritious food ready.',
  },
]
